cfengine/documentation

enterprise-cfengine-guide/reporting.markdown, examples/enterprise-api-examples/sql-queries.markdown, examples/example-snippets/distribute_ssh_keys.cf, examples/example-snippets/software_and_patch_installation.cf, examples/example-snippets/software_and_patch_installation_1.cf, examples/example-snippets/software_and_patch_installation_1_2.cf, examples/example-snippets/software_and_patch_installation_1_2_3.cf, examples/tutorials/file_comparison.markdown, examples/tutorials/report_inventory_remediate_sec_vulnerabilities.markdown, guide/faq.markdown, guide/glossary.markdown, guide/installation-and-configuration/general-installation/installation-enterprise-free-aws-rhel.markdown, guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown, guide/installation-and-configuration/upgrading-to-36.markdown, guide/latest-release/known-issues.markdown, guide/latest-release/policy-framework-updates.markdown, guide/latest-release/whatsnew.markdown, guide/writing-and-serving-policy/authoring-policy-tools-and-workflow.markdown, guide/writing-and-serving-policy/bundles-best-practices.markdown, guide/writing-and-serving-policy/policy-style.markdown, reference/classes.markdown, reference/functions/bundlesmatching.markdown, reference/functions/getindices.markdown, reference/functions/lsdir.markdown, reference/functions/now.markdown, reference/functions/readstringarrayidx.markdown, reference/promise-types/interfaces.markdown, reference/promise-types/users.markdown
* Fix typos found by codespell.
* Fix "the the" pattern.
=> Fix typos and word duplications

examples/example-snippets/commenting_lines_in_a_file.cf, examples/example-snippets/editing_tabular_files.cf, examples/example-snippets/linking_files.cf, examples/example-snippets/search_and_replace_text.cf
I'm not sure whether this is the intended correction, so please review carefully.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> examples: Fix typo in comments

guide/latest-release/known-issues.markdown, reference/promise-types/edit_xml.markdown, reference/promise-types/processes.markdown, reference/promise-types/users.markdown
Merge after these are merged:
* https://github.com/cfengine/core/pull/2078
* https://github.com/cfengine/enterprise/pull/238
* https://github.com/cfengine/buildscripts/pull/33
=> Redmine #6853: Update platform notes after HPUX fixes.

reference/functions/bundlestate.markdown, reference/functions/datastate.markdown
As proposed in https://github.com/cfengine/core/pull/2074
=> bundlestate: new function

reference/promise-types/packages.markdown
This needs picked to 3.6 as well.
=> Change: Improve addupdate package_policy docs

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
(cherry picked from commit 9fb923f999d9e9d8f8787a9685e32c3226fb650f)
=> Change: Update link to 3.6.4 vagrant env

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
(cherry picked from commit aba04c0a5343f54157633ac7f2a24fdcc713e9b5)
=> Change: Fix link to point to correct location

guide/faq.markdown, reference/promise-types/methods.markdown
This is a frequently asked question.
This should also be picked into 3.6.x
=> Add: How to pass a datacontainer

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
(cherry picked from commit db2d8c40a91efda77d88e2746dcbdeb31c66defd)
=> Change: Update vagrant project to 3.6.5

reference/functions/mergedata.markdown
As implemented in https://github.com/cfengine/core/pull/2145
=> reference/functions/mergedata.markdown: document using mergedata() to wrap containers

enterprise-cfengine-guide/hub_administration.markdown
Ref: https://dev.cfengine.com/issues/6662
=> Add: Documentation to reset Mission Portal admin user

enterprise-cfengine-guide/hub_administration.markdown
Ref: https://dev.cfengine.com/issues/6662
=> Add: Documentation on resetting admin password for Mission Portal

reference/special-variables/sys.markdown
Please hold until cfengine/core#1425 is deemed acceptable and merged.
=> Document sys.statedir special variable

reference/components.markdown
As requested in pull request core@2167
=> components.md: document "bwlimit" feature control

reference/functions/string_mustache.markdown
See https://github.com/cfengine/core/pull/2130 for details
=> Redmine#7031: string_mustache() function

guide/language-concepts/classes.markdown
As requested in https://github.com/cfengine/core/pull/2150
=> Redmine#2504: document variable string contexts

reference.markdown, reference/macros.markdown
Requested in https://github.com/cfengine/core/pull/2176
=> Redmine#7111: @if macro

reference/functions/filestat.markdown
docs for https://github.com/cfengine/core/pull/2193
=> Redmine#7098: document filestat() xattr option

reference/functions/maparray.markdown, reference/functions/mapdata.markdown, reference/functions/maplist.markdown
Documentation for https://github.com/cfengine/core/pull/1485
=> Redmine#4703: document addition of mapdata() and the maparray() changes

reference/promise-types/services.markdown
For https://github.com/cfengine/core/pull/2161
=> Redmine#5646: add enable to service_policy choices

reference/functions/readcsv.markdown, reference/functions/readdata.markdown, reference/functions/readjson.markdown, reference/functions/readyaml.markdown
Docs for https://github.com/cfengine/core/pull/2162
=> Add readdata() function docs

reference/functions/parsejson.markdown, reference/functions/parseyaml.markdown, reference/promise-types/vars.markdown
see https://github.com/cfengine/core/pull/2203 and https://github.com/cfengine/core/pull/2156
=> Redmine#3660: document inline JSON and YAML

guide/latest-release/known-issues.markdown
This is a better index per Maciej. Also updated the markdown to render using
the console brush for a (hopefully) nicer look.
=> Change: Index on Benchmark table

guide/latest-release/known-issues.markdown
(cherry picked from commit 67a5edb28fe3f20b3518c5808edffb48742be7ed)
=> Document 3.6.0/3.6.1 upgrade to 3.6.5 issues.

reference/components/cf-execd.markdown
Superceeds https://github.com/cfengine/documentation/pull/1034
=> Change: Clarify reccomended splay time

reference/functions/data_expand.markdown
As requested in https://github.com/cfengine/core/pull/2207
=> Redmine#7166: data_expand() documentation

guide/faq.markdown
(cherry picked from commit 3a3598536325421a96d82973141011b2c24bb228)
=> Add: FAQ for cf-hub processes

reference/macros.markdown
merge with https://github.com/cfengine/core/pull/2243 for https://dev.cfengine.com/issues/7281
=> Redmine#7281: rename version_after macro to minimum_version

enterprise-cfengine-guide/best-practices.markdown
... and consequently moved to under controls/, too.
Note that the documentation I'm fixing here is mirrored in mission-portal and has a parallel review going there, in which Michael may make some suggestions - so please don't rush to merge, without checking with him !  Otherwise, any fixes he asks me for are just going to be extra work for you ...
=> The config change has moved from update.cf to update_def.cf

guide/writing-and-serving-policy/policy-style.markdown
Ref: https://dev.cfengine.com/issues/7354
=> Add: Policy DEBUG Reports Style

guide/writing-and-serving-policy/policy-style.markdown
Ref: https://dev.cfengine.com/issues/7354
=> Backport Add: Policy DEBUG Reports Style

guide/writing-and-serving-policy/policy-style.markdown
Ref: https://dev.cfengine.com/issues/7354
=> Backport: Add: Policy DEBUG Reports Style

reference/promise-types/files.markdown
@jimis you mentioned this on IRC...
=> Reword description of collapse_destination_dir

reference/promise-types/files.markdown
Ref: https://dev.cfengine.com/issues/7284
=> Fix: Syntax causing incorrect rendering.

reference/promise-types/files.markdown
Manually backport from master, it took several tries to get it right
=> Fix: Rendering of mustache syntax

guide/faq.markdown, guide/writing-and-serving-policy/policy-framework.markdown
Apparently I just can't seem to be able to link to a heading that contains
().
=> Fix: Unresolved Links Removed () around class or variable in bundle heading

guide/faq.markdown, guide/writing-and-serving-policy/policy-framework.markdown
Found that it did work to link to headings with()
=> Fix: Header Links again

guide/writing-and-serving-policy/policy-framework.markdown
Reduced section level headers for bundles so they are shown in the TOC.
=> Change: Adjust Section Headers

guide/latest-release/policy-framework-updates.markdown, guide/writing-and-serving-policy/policy-framework.markdown
This was manually copied from master due to the high number of commits to get
it working.
=> Change: Update policy framework docs for 3.7

reference/enterprise-api-ref/design-center.markdown
* Fix examples not showing.
* Adjust JSON exmaple indentation to 2 tabs to avoid long line wrapping and make it more readable.
* Adjust top page menu to present api function instead row URI. Purpuse is to make it more readable.
=> Adjustments to design-center rest api documentation.

reference/enterprise-api-ref/design-center.markdown
just to test some rendering
to be reverted later
=> Test styling

guide/latest-release/known-issues.markdown, guide/latest-release/policy-framework-updates.markdown
Update known issues Update policy framework updates
=> Change: Documentation updates for 3.7

reference/enterprise-api-ref/changes.markdown, reference/enterprise-api-ref/design-center.markdown, reference/enterprise-api-ref/host.markdown, reference/enterprise-api-ref/query.markdown, reference/enterprise-api-ref/status-settings.markdown, reference/enterprise-api-ref/users-rbac.markdown
(cherry picked from commit c72ebb09164263c6797721750bc53fcbf0ef0048)
=> Change place holder for hub address in REST API documentation

examples/enterprise-api-examples/dc-interaction.markdown
(cherry picked from commit 9d28afc31861fe3849a48030fda49f5088b40142)
=> Fix DC examples

guide/installation-and-configuration/version-control.markdown
(cherry picked from commit f7b66ced9dcdea7b478ca66e50a1c90e8f70ff34)
=> Change: Git url to reflect actual masterfiles repo

reference/promise-types/files.markdown
Show practical usage in addition to example body implementations.
Requires: https://github.com/cfengine/core/pull/2298
=> Change: Improve symlink examples

reference/promise-types/commands.markdown
(cherry picked from commit d9e079a741bb4d5a0663c21b02a1d007d95f66f5)
=> Add: Note requirement for full path to commands

reference/promise-types/commands.markdown
Ref: https://dev.cfengine.com/issues/7497
=> Add: Documentation about cfengine-die

reference/components.markdown
Also added details about individual options.
=> Fix: Default value for protocol version

enterprise-cfengine-guide/enterprise-api.markdown, examples/enterprise-api-examples.markdown, reference/enterprise-api-ref.markdown
(cherry picked from commit fec3c0fa7614a630af61afbd95015d3bc532b3be)
=> Add: Links to cross reference Enterprise API Docs

enterprise-cfengine-guide/high-availability/installation-guide.markdown
Also includes extending HA documentation with 3 nodes setup.
=> Add ordering and colocation constraints to HA documentation.

guide/latest-release/known-issues.markdown
=> Add: Known issue regarding scheduled CSV reports

guide/language-concepts/normal-ordering.markdown
(cherry picked from commit f4803c9946972560a09a42f1b6b4a30e439102ce)
=> Change: Reflow agent pre-eval docs

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
=> Change: Update vagrant docs for 3.7.1 release

reference/promise-types/commands.markdown
as requested for https://github.com/cfengine/core/pull/2248#issuecomment-132905070
=> Redmine#7302: extend module protocol to create persistent classes

cheatsheet.markdown, examples/enterprise-api-examples/changes-api-usage.markdown, guide/writing-and-serving-policy/policy-framework.markdown, reference/promise-types/access.markdown, reference/promise-types/files.markdown
Ref: https://dev.cfengine.com/issues/7559
=> Fix: Version sepecific policy paths

reference/promise-types/guest_environments.markdown
Ref: https://dev.cfengine.com/issues/7570
=> Fix: Documentation example for environment_type

reference/components.markdown, reference/components/cf-serverd.markdown
(cherry picked from commit c2e2e2e8dcebc38d46319d678c6418a3eaf8cb65)
=> Add: Documentation for encryption options related to protocol_version

reference/promise-types/classes.markdown
(cherry picked from commit 179229848885b20dfe58a26a90dd77ee20d02e98)
=> Add: Explination of complete classes promsise statements

reference/components/cf-agent.markdown, reference/promise-types/processes.markdown
- Change: Improve processes promise example
- Change: Make agent control example more relavent
=> Documentation Improvements

reference/components/cf-agent.markdown, reference/promise-types/processes.markdown
- Change: Improve processes promise example
- (cherry picked from commit 8dbf4bf7332e82c2a8416344cde6ed69449d403c)
- Change: Make agent control example more relavent
- (cherry picked from commit 76ada392febea171125d3c02f27887b9a259e5a7)
=> Backport Doc improvements

guide/language-concepts/classes.markdown
see https://github.com/cfengine/core/pull/2255
=> Redmine#7152: Allow whitespace in class expressions

guide/introduction/networking.markdown
(cherry picked from commit 5c88b9a79dd04cb96253e2a5705e6db95a3e01b9)
=> Change: Improve encryption summary in networking doc

reference/standard-library/commands.markdown, reference/standard-library/common.markdown, reference/standard-library/databases.markdown, reference/standard-library/files.markdown, reference/standard-library/monitor.markdown, reference/standard-library/packages.markdown, reference/standard-library/processes.markdown, reference/standard-library/services.markdown, reference/standard-library/storage.markdown, reference/standard-library/users.markdown, reference/standard-library/vcs.markdown
This reverts commit adb0cd2a71b7ddac6192f44baae4347494f60075.
=> Revert "Fix: path to stdlib includes"

reference/promise-types/commands.markdown
(cherry picked from commit fd288f948a0e7fabf0e1b2100c114e029752ce93)
=> Add: Note about environment vars and commands

guide/language-concepts/bodies.markdown, reference/promise-types.markdown
see https://github.com/cfengine/core/pull/2320#issuecomment-141394427
=> Redmine#4309: document body inheritance via inherit_from

reference/promise-types/classes.markdown
Ref: https://dev.cfengine.com/issues/7482
=> Add: Note about select_class special behavior

reference/common-body-attributes-include.markdown, reference/promise-types/commands.markdown, reference/promise-types/databases.markdown, reference/promise-types/edit_line.markdown, reference/promise-types/edit_line/delete_lines.markdown, reference/promise-types/edit_line/field_edits.markdown, reference/promise-types/edit_line/insert_lines.markdown, reference/promise-types/edit_line/replace_patterns.markdown, reference/promise-types/files.markdown, reference/promise-types/guest_environments.markdown, reference/promise-types/measurements.markdown, reference/promise-types/packages-deprecated.markdown, reference/promise-types/packages.markdown, reference/promise-types/processes.markdown, reference/promise-types/reports.markdown, reference/promise-types/services.markdown, reference/promise-types/storage.markdown, reference/promise-types/users.markdown
(cherry picked from commit d9d08356d2322c01069773d5bb5f9f82e925916d)
Conflicts:
reference/promise-types/edit_line/insert_lines.markdown
=> Add: Reference to common body attributes from bodies

reference/promise-types/methods.markdown
Depends on https://github.com/cfengine/core/pull/2357
=> Fix: Broken Link

reference/functions/url_get.markdown
See https://github.com/cfengine/core/pull/2352 and https://github.com/cfengine/core/pull/2152
=> Redmine#1815: libcurl integration

reference/macros.markdown
Document https://github.com/cfengine/core/pull/2340
=> Document @if feature macro

reference/functions/execresult.markdown
Ref: https://dev.cfengine.com/issues/7698
=> Add: Documentation about execresult return limitation

reference/functions.markdown
(cherry picked from commit 3febc5d14b23bdc21bf96a413a8f3d97febd917d)
=> Add: Documentation about function skipping

reference/functions/data_regextract.markdown, reference/functions/regex_replace.markdown, reference/functions/regextract.markdown
requested in https://github.com/cfengine/core/pull/2392#issuecomment-154500081
requires https://github.com/cfengine/core/pull/2397
=> Redmine#7346: add regex_replace docs

reference/promise-types/packages.markdown
- Also added package_module to examples
=> Add: Documenation for version => "latest" in packages

cheatsheet.markdown
It would be nice to be able to use a variable for things we commonly search
and replace.
=> Add liquid variable testing expansion

index.markdown
Turn it into a variable thats defined from _config.yml in the
documentation-generator. This way we can have fewer things to change
during releases.
=> Change: Liquify reference to hard coded branch

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
Make it use site wide variables for more efficient updating.
=> Change: Liquify the vagrant page

reference/promise-types/reports.markdown
(cherry picked from commit 380e65a0b39ac25934760675109c09e81c262efb)
=> Add: Version where showstate was deprecated

guide/installation-and-configuration/upgrading.markdown
Changelog: Updated update procedure for CFEngine 3.8.
=> Redmine #7700 Fix upgrade procedure for 3.8

reference/functions/data_readstringarray.markdown
Ref: https://dev.cfengine.com/issues/6478
=> Change: Clarify comment regex is multiline

reference/promise-types/reports.markdown
- Include more complete example from core
Depends on example in https://github.com/cfengine/core/pull/2411
=> Change: Improve reports type promise docs

reference/promise-types/reports.markdown
Apparently trying to comment out a macro doesn't work.
=> Fix: Attempt to fix build

guide.markdown, index.markdown
- This reverts commit 608457644a8ffbc3a03be1df6de00855d4b78dcf.
- Renaming a top level page isn't as simple as that.
=> Revert "Change: Try out Guide as the index"

reference/functions/mapdata.markdown
As requested in https://github.com/cfengine/core/pull/2425
=> Add "canonify" mode to mapdata().

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
(cherry picked from commit 7f9d498eda5f4cf9cb8256458f81a756a6d6e759)
=> Change: Clarify package matching function docs

reference/functions/not.markdown, reference/functions/or.markdown
(cherry picked from commit c8b9cdf2dc35e873b26ac56c6bf21ed24d238728)
=> Change: Clarify arguments for not and or functions

reference/language-concepts/normal-ordering.markdown
(cherry picked from commit f9e70451ab0ae4912d62042b72baf4850f6fde48)
=> Change: Fix incorrect statement about bundlesequence

guide/installation-and-configuration/general-installation.markdown
Documentation for https://github.com/cfengine/core/pull/2297/files as requested. @nickanderson @kacf please review.
=> Redmine#7453: parse def.json vars, classes, and inputs in C

guide/installation-and-configuration/upgrading.markdown
To fix some incorrect commands and rendering issues
=> Change: Minor fixes to upgrade docs

guide/installation-and-configuration/upgrading.markdown
Bullets still not aligned correctly
=> Fix: rendering

guide/installation-and-configuration/upgrading-to-37.markdown
Bad rendering and incorrect options to commands
=> Fix: Minor issues

examples/example-snippets/promise-patterns/example_edit_motd.markdown
Fix some incorrect output, and render it more beautifully
=> Change: Fixups for motd example

guide/introduction/directory-structure.markdown
(cherry picked from commit ed257c47d4b435e9bac9770d5b6a7611968ae6f4)
=> Add: info about runalerts.sh

reference/promise-types/files.markdown
see https://github.com/cfengine/core/pull/2274
=> libutils/mustache.c: add {{#-top-}} {{/-top-}} for iteration over top container

reference/language-concepts/bodies.markdown
Add documentation for https://github.com/cfengine/core/pull/2469.
=> Add: Document default bodies

guide/latest-release/known-issues.markdown
Usernames with dots are unable to be edited
=> Add: Known issue for directory based users

reference/functions/findprocesses.markdown, reference/functions/processexists.markdown
@pasinskim as requested in https://github.com/cfengine/core/pull/2349
=> Redmine#7633: processexists() and findprocesses()

reference/functions/expandrange.markdown
Add a note on when the expandrange() function was added
=> Document function history

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
(cherry picked from commit e60b7cc79cdc157501e400f3d1a6e7868fb28fc5)
=> Add: Info about diff report resource usage

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
(cherry picked from commit a7ce33f3a4ce060a65f09278fedee7399530ee80)
=> Fix: Correct some grammar

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
One of the commands showed $ instead of # which could confuse someone
that it is a non root console.
=> Change: Improve rendering & fix console example

guide/writing-and-serving-policy/policy-style.markdown
(cherry picked from commit 20c8c25302723a91ba1336a7db138ee76db1c3f5)
=> Add: Style for class naming and promise ordering

guide/faq.markdown, reference/promise-types/files.markdown
@nickanderson please double-check, thanks!
=> Update documentation to show template_data can take @(container)

reference/functions/iprange.markdown, reference/special-variables/sys.markdown
As requested in https://github.com/cfengine/core/pull/2290
=> Reverse mapping from IP to interface and iprange() can look by interface

reference/functions/intersection.markdown, reference/functions/irange.markdown, reference/functions/isvariable.markdown, reference/functions/join.markdown, reference/functions/length.markdown, reference/functions/makerule.markdown, reference/functions/maparray.markdown, reference/functions/mapdata.markdown, reference/functions/maplist.markdown, reference/functions/max.markdown, reference/functions/mean.markdown, reference/functions/mergedata.markdown, reference/functions/min.markdown, reference/functions/none.markdown, reference/functions/nth.markdown, reference/functions/parsejson.markdown, reference/functions/product.markdown, reference/functions/reglist.markdown, reference/functions/reverse.markdown, reference/functions/shuffle.markdown, reference/functions/some.markdown, reference/functions/sort.markdown, reference/functions/storejson.markdown, reference/functions/sublist.markdown, reference/functions/sum.markdown, reference/functions/unique.markdown, reference/functions/url_get.markdown, reference/functions/variance.markdown
Build broken again with the same cryptic message.
=> Revert most recent collection updates

reference/functions/none.markdown
Remove some links that might be causing the unknown error.
=> Fix: build

guide/installation-and-configuration/general-installation.markdown
3.8 version of https://github.com/cfengine/documentation/pull/1381.
=> [3.8] Def.json no autoload 3.8

guide/latest-release/known-issues.markdown
(cherry picked from commit 98e79d2b919d425a078cfe841984383170b152b0)
=> Add: Known Issue for php warning after upgrading from 3.6.x

reference/components.markdown
(cherry picked from commit d4d289828a0e8d5fe2c08e716671aee4b9fd4c5f)
=> Change: Indicate valid bundle types in bundlesequence

reference/functions/bundlestate.markdown
(cherry picked from commit e3f7afa065b897ba3a8b76f3cad3be7850300052)
=> Add: Note about bundlestate() not collecting classes

reference/language-concepts/augments.markdown
(cherry picked from commit ff6bb029c0bba85a9c0ce1a86d2b8a208ad995d5)
=> Change: Improve augments history

reference/promise-types/commands.markdown
docs requested in https://github.com/cfengine/core/pull/2302
=> Add commands arglist attribute, augmenting args attribute

reference/components/cf-agent.markdown
Master docs aren't rendering correctly.
=> Revert "Change: Improve abortclass documentation"

reference/special-variables/sys.markdown
as requested in https://github.com/cfengine/core/pull/2245
=> libenv: add Linux parsing of /proc/net/ data

reference/functions/readintrealstringlist.markdown
(cherry picked from commit d4ec7e64735b08d21826a74bf00993c9ab386293)
=> Change: Indicate comment for readintrealstringlist is multiline regex

reference/functions/readintrealstringarray.markdown
(cherry picked from commit e8d376f05f0f9f067816cd1c29a72f210e49f93d)
=> Change: Indicate read[int|real|string]array comments are multiline regular expressions

reference/functions/readstringarrayidx.markdown
(cherry picked from commit 940460623e7d848738965baf560ef4c8bdab251b)
=> Change: Indicate readstringarrayidx comment is multiline regex

reference/components/cf-agent.markdown
Linked to https://github.com/cfengine/core/pull/2548
=> Document that files in suspiciousnames are skipped

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
(cherry picked from commit c4c654a9e8a6b35ead8487b21121682462230edf)
=> Add: libtld as a pre-requisite

reference/promise-types/reports.markdown
(cherry picked from commit 4d7d0be267dc1a147f01a0ff49bb7f12c1a1fa07)
=> Change: Note old reports promise deprecations

reference/functions/findprocesses.markdown, reference/functions/processexists.markdown, reference/promise-types/processes.markdown
Also clean up the docs a little.
=> CFE-2161: Process matching now only searches within the command line.

reference/functions/callstack_callers.markdown, reference/functions/callstack_promisers.markdown
as requested in https://github.com/cfengine/core/pull/2331#issuecomment-212341037 and https://github.com/cfengine/core/pull/2585 by @kacf
=> Document callstack_callers() and callstack_promisers()

reference/language-concepts/classes.markdown, reference/promise-types/classes.markdown
as requested by @jimis in https://github.com/cfengine/core/pull/2579
=> Clarify JSON boolean handling and improve expression docs

reference/language-concepts/augments.markdown
(cherry picked from commit a055abf05cc5300a291bdac0c0a51c2b29a5f790)
=> Change: Document augments hard class exceptions

reference/language-concepts/classes.markdown, reference/promise-types/classes.markdown
As requested in https://github.com/cfengine/core/pull/2596#issuecomment-215703224
=> New feature: Classes promise: allow classes without an expression to default to defined.

reference/promise-types/packages.markdown
(cherry picked from commit 5bf2ecf82c3e064a55d29d51e0192344b4db7370)
=> Add new package modules in 3.9

reference/enterprise-api-ref.markdown, reference/enterprise-api-ref/status-settings.markdown
(cherry picked from commit 5575a7fbdffae7a6c1927fe99a499f9aa12c9b50)
=> Add: Documentation indicating missing keys are defaulted

guide/special-topics.markdown, guide/special-topics/adopting-cfengine.markdown, guide/special-topics/agility.markdown
So much good information in these even if they are out of date.
=> Begin Resurrecting Special Topics

reference/functions/getfields.markdown
(cherry picked from commit 182b130918236fd2e5be527910ec6c9fc1c5aa13)
=> Clarify that readstringarray & friends don't provide matching lines.

reference/components/cf-agent.markdown, reference/promise-types/edit_line.markdown
(cherry picked from commit 5fc42090fbb12b0c7b83251df47924ca39fce379)
=> CFE-2390 Document 'select_end_match_eof' body agent control option.

reference/promise-types/packages.markdown
(cherry picked from commit 45cf7af49f6d1eb58aad6a0223db2c40ed2ef4d0)
=> Change: Clarify python version requirements for package modules

examples/example-snippets/promise-patterns/example_enable_service.markdown
(cherry picked from commit a21ee37b8e0f0ca8dca21d43c177e5a247bcc204)
=> Change: Refactor services example

reference/functions/ifelse.markdown
This needs picked to 3.7.x and 3.9.x
=> Add: Note special behaviour change for ifelse()

reference/functions/regline.markdown
(cherry picked from commit 981623f639fdf3418a82736b8c1ab4302772330d)
=> Change: Refactor regline example

reference/functions/eval.markdown
For https://github.com/cfengine/core/pull/2645 @jimis
=> Add < <= > >= operators to eval().

reference/functions/iprange.markdown, reference/functions/isipinsubnet.markdown
see https://github.com/cfengine/core/pull/2632 @jimis
=> ENT-7949: New function isipinsubnet()

reference/promise-types/commands.markdown
Signed-off-by: Kristian Amlie <kristian.amlie@cfengine.com>
=> Adapt docs according to fix for CFE-2412.

reference/promise-types/packages.markdown, reference/standard-library/package_modules.markdown
See also https://github.com/cfengine/masterfiles/pull/802
=> CFE-2468 documentation of options attribute

reference/functions/getuserinfo.markdown, reference/functions/getusers.markdown
As requested in https://github.com/cfengine/core/pull/2575 @jimis @nickanderson
=> Add getuserinfo() function documentation.

reference/functions/getuserinfo.markdown, reference/special-variables/sys.markdown
Uses the example from https://github.com/cfengine/core/pull/2713 so they should be merged together.
=> Add documentation for sys.user_data and update getuserinfo() docs.

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
See http://data.grammarbook.com/blog/pronouns/1-grammar-error/
=> Fix its grammar

guide/faq/enterprise-report-collection.markdown
Also reduced header font size and simplified some preexisting info.
=> Zendesk#3204: answer report collection questions.

reference/functions.markdown, reference/functions/execresult.markdown, reference/functions/host2ip.markdown, reference/functions/hubknowledge.markdown, reference/functions/ip2host.markdown, reference/functions/ldaplist.markdown, reference/functions/ldapvalue.markdown, reference/functions/readtcp.markdown, reference/functions/regldap.markdown, reference/functions/remoteclassesmatching.markdown, reference/functions/remotescalar.markdown, reference/functions/returnszero.markdown
(cherry picked from commit 65c147896ed8262e6a65420409d73126f7c067c5)
=> Tag cached functions

reference/functions/string_head.markdown, reference/functions/string_tail.markdown
Signed-off-by: Kristian Amlie <kristian.amlie@cfengine.com>
=> Add docs for functions string_head/tail negative arguments.

reference/common-attributes-include.markdown, reference/promise-types.markdown
Requested in https://github.com/cfengine/core/pull/2788#issuecomment-297273076
Needs https://github.com/cfengine/core/pull/2788 merged first.
=> CFE-1092: add documentation of `with` attribute

reference/promise-types/databases.markdown, reference/promise-types/files.markdown, reference/promise-types/roles.markdown, reference/promise-types/storage.markdown
=> Syntax fixes for assignments in examples

enterprise-cfengine-guide/hub_administration/custom-https-certificate.markdown, guide/faq/show-classes-and-vars.markdown, reference/language-concepts/augments.markdown
As discussed in https://github.com/cfengine/core/pull/2480
=> Document and use optional regex parameter to --show-vars and --show-classes

reference/functions/readenvfile.markdown
=> Newline fixes for readenvfile

reference/enterprise-api-ref/sql-schema.markdown
Improve some details:
- lastseeninterval is measured in minutes.
- LastSeenHosts table is derived from the lastseen database.
- Host table IP address is derived from lastseen database for incoming connection
=> Add additional Enterprise DB details

reference/promise-types/edit_line/insert_lines.markdown
Improve wording of a couple items
=> Clarify insert_lines doc

reference/enterprise-api-ref/ldap-api.markdown
@nickanderson @dmitry84 Plese review
=> Ldap APi documentation was added.

guide/installation-and-configuration/upgrading.markdown
(cherry picked from commit 62872528b002db79af64118de12b79995fd2b390)
=> zd#3599: simplify upgrade process documentation

reference/components/cf-agent.markdown, reference/promise-types/files.markdown
Reverts cfengine/documentation#1659
=> Revert "CFE-2729: Improve edit_backup documentation"

reference/promise-types/files.markdown
(cherry picked from commit 5b58351bf825cd0db1fcafe841828727b80ec0f9)
=> ENT-3480: Note that X which is supported by setfacl is NOT supported by acl body

reference/promise-types/files.markdown
(cherry picked from commit 066dd529a52fd44e57ae8daabca505eeb129be63)
=> ACL doc improvements

reference/enterprise-api-ref/users-rbac.markdown
merge with 
https://github.com/cfengine/mission-portal/pull/495
https://github.com/cfengine/nova/pull/1083
=> ENT-3578: Remove references to cf_vcs role that is no longer used.

examples/example-snippets/packages_examples_solaris.cf, examples/example-snippets/software-adminstration.markdown
They were yum examples accidentally.
=> Fix solairs packages example snippets

reference/language-concepts/classes.markdown
Together with an example of how they look like.
=> CFE-2310: Document the IPv6 network hard classes

reference/language-concepts/classes.markdown
(cherry picked from commit 4ddb1e37c78e8a55ef16ac7a43bdc4cb28d58701)
=> CFE-2310 Document when ipv6 prefixed classes were added

reference/functions/filesexist.markdown
Implemented in cfengine/core#3033
=> filesexist() is now one of the collecting functions

enterprise-cfengine-guide/reporting.markdown
Removing old 3.6.0 references and stale info. Small refactors and x-ref.
=> Small refresh for Enteprise Reporting landing page

guide/faq/why-are-files-not-being-distributed.markdown
(cherry picked from commit e10bc5805f4b2b47b28a5f63130f294f7ee79bd7)
=> Tidy why files arent being distributed faq

guide/installation-and-configuration/secure-bootstrap.markdown
(cherry picked from commit dd316f71d5e0c582e1d41b2662488fe02edc2413)
=> ENT-3695 Refresh secure bootstrap guide

reference/special-variables.markdown
(cherry picked from commit dfc7d8e51c431cd2ecf77593c4d315b1827a5e43)
=> CFE-2791 Add connection vars to special vars landing page

reference/special-variables.markdown
(cherry picked from commit dfc7d8e51c431cd2ecf77593c4d315b1827a5e43)
=> CFE-2791 Add connection vars to special variables landing page

enterprise-cfengine-guide/hub_administration/regenerate-self-signed-cert.markdown
(cherry picked from commit c1389ad500a660237a170c8f19fbad22d8ceda7e)
=> ENT-3707 Add docs for regenerating self signed ssl cert

reference/promise-types.markdown
(cherry picked from commit e1efa16363e2df852a8f7d0f9ff1159701cc11e9)
=> CFE-2795 Improve example for body action background

guide/faq/uninstall-reinstall.markdown
(cherry picked from commit 7c215218a3b96d43332c2e8c4573b73b14d9dea8)
=> ENT-3714 Add doc about uninstalling and reinstalling

reference/promise-types/packages.markdown
(cherry picked from commit 1a1d981832c307b3d7cd55d29882c7778c7059a3)
=> CFE-2806 Document enablerepo and disablerepo yum package_module options

enterprise-cfengine-guide/hub_administration/backup-and-restore.markdown
(cherry picked from commit 25b7398be62ae9d8b0081d80ede2a7ed4469c007)
=> ENT-3750 Backup and restore docs

reference/promise-types/access.markdown
=> ENT-3799 Document when resource_type bundle was introduced

guide/faq/show-classes-and-vars.markdown, guide/special-topics/virtualization.markdown.breaks_build, guide/writing-and-serving-policy/promises-available-in-cfengine.markdown, reference/language-concepts/normal-ordering.markdown, reference/promise-types.markdown, reference/promise-types/guest_environments.markdown
Reverts cfengine/documentation#1806
=> Revert "CFE-2814 Remove deprecated guest_environments"

enterprise-cfengine-guide/settings.markdown
I'd like to get this in and cherry pick it along with the others that I was reviewing for 3.7, 3.10 and 3.12
https://github.com/cfengine/documentation/pull/1826 (3.7)
https://github.com/cfengine/documentation/pull/1827 (3.10)
https://github.com/cfengine/documentation/pull/1828 (3.12)
=> ENT-3849: follow up to fix a couple of small typos and sentence flow.

enterprise-cfengine-guide/settings.markdown
https://github.com/cfengine/documentation/pull/1824
(cherry picked from commit b6c2253a4206714f121da13c262eb6379dfc8766)
=> ENT-3849 Clarify how roles affect shared reports (3.12)

enterprise-cfengine-guide/settings.markdown
https://github.com/cfengine/documentation/pull/1824
(cherry picked from commit b6c2253a4206714f121da13c262eb6379dfc8766)
=> ENT-3849 Clarify how roles affect shared reports (3.7)

enterprise-cfengine-guide/settings.markdown
https://github.com/cfengine/documentation/pull/1824
(cherry picked from commit b6c2253a4206714f121da13c262eb6379dfc8766)
=> ENT-3849 Clarify how roles affect shared reports (3.10)

reference/promise-types/packages.markdown
(cherry picked from commit 8c0ee4ef4edbabd4a89b1f5917f8b91863d7a432)
=> Adding documentation for the Slackpkg package module (3.12)

examples/enterprise-api-examples/changes-api-usage.markdown, reference/enterprise-api-ref/changes.markdown
(cherry picked from commit 2de279d7ce0bed9de09acd6508fdf97fa7e08b65)
=> ENT-3895: Changes/policy api documentation was updated.

guide/faq/unable-to-log-in-mission-portal.markdown, reference/promise-types/databases.markdown
If oauth tokens are not aliged you will be unable to log into mission
portal. This documents how to check and fix alignment.
(cherry picked from commit 5d9876f2c4c76a1c8ed186751d0b7a57a947ef4c)
=> ENT-3908 Document how to align oauth tokens for MP access

reference/promise-types/databases.markdown
(cherry picked from commit d02a902efd0f724fb097b95a3bab8097ac324711)
=> Improve example showing how to promise registry values containing commas

guide/latest-release.markdown
(cherry picked from commit 2d00c4ab6d93297b45bce237c0a337812122a1cb)
=> Remove link to page that no longer exists

reference/promise-types/measurements.markdown
We opened custom measurements to cfengine community. Now everyone can
write their own custom measurement promises.
=> CFE-2862 Document that measurement promises are now open source

reference/promise-types/processes.markdown
(cherry picked from commit 43a147e1f869272f509888a8ae2970565487b164)
=> CFE-2863 Document process promise restrictions about signial pid 1-4 and self

guide/installation-and-configuration/upgrading.markdown
Simplify the upgrade process. Remove un-necessary debugging steps.
=> ENT-3957 Tidy upgrade documentation

reference/promise-types/measurements.markdown
=> a couple of small typo fixes

reference/components/cf-agent.markdown, reference/promise-types.markdown
(cherry picked from commit d331f038db02507140f2ab3694f26bf3c4b93f43)
=> Cross reference max_children and background attributes

reference/functions/string_replace.markdown
=> CFE-2850 Added documentation entry for string_replace

reference/language-concepts/augments.markdown
Ticket: CFE-2883
Changelog: TODO
=> Make augments keys anchors for better navigation

guide/faq/integrate-custom-policy.markdown
=> FAQ: How to integrate custom policy

reference/functions/eval.markdown
(cherry picked from commit af85013128607c9ccb0ba2bb52d84775b8d1d0d9)
=> Tidy formatting for eval history

reference/promise-types/access.markdown, reference/promise-types/commands.markdown, reference/promise-types/databases.markdown, reference/promise-types/edit_line.markdown, reference/promise-types/edit_line/delete_lines.markdown, reference/promise-types/edit_line/field_edits.markdown, reference/promise-types/edit_line/insert_lines.markdown, reference/promise-types/edit_line/replace_patterns.markdown, reference/promise-types/files.markdown, reference/promise-types/guest_environments.markdown, reference/promise-types/measurements.markdown, reference/promise-types/packages-deprecated.markdown, reference/promise-types/packages.markdown, reference/promise-types/processes.markdown, reference/promise-types/reports.markdown, reference/promise-types/services.markdown, reference/promise-types/storage.markdown, reference/promise-types/users.markdown
(cherry picked from commit 06eff3ade2387a0d936e6823a026d0f19cfb5371)
=> Swap common-body-attributes-include with See also xref

examples/enterprise-api-examples/managing-settings.markdown, reference/enterprise-api-ref.markdown, reference/enterprise-api-ref/status-settings.markdown, reference/enterprise-api-ref/users-rbac.markdown
=> ENT-3463: Remove sketches from documentation

reference/promise-types/packages.markdown
Added in cfengine/core@c28fda9e7 and cfengine/core@0668f8b91.
Ticket: CFE-2880
Ticket: CFE-2103
=> Add documentation for the new package_module body attributes

reference/promise-types/access.markdown
=> CFE-2567 Note and warn about using deny_hostnames and sensitivity to DNS

reference/promise-types/access.markdown
(cherry picked from commit 23b405baa8c35a70d1bed64e79e44f27575ea7c6)
=> Fix grammar

reference/enterprise-api-ref/sql-schema.markdown
(cherry picked from commit 5555c81dc976cf39313f7daaac21f09ae3c7d7c2)
=> ENT-4148 Add docs for promiselog table/view

reference/components.markdown, reference/functions/hostsseen.markdown
(cherry picked from commit a7a52091eb4c09567de70cef80eb7732089f4e50)
=> Add cross reference between hostseen() and lastseenexpireafter

reference/components.markdown
(cherry picked from commit 7d5d756a87c59ce5b57305cc3df0631246e59203)
=> Fix name of hostsseen function

guide/installation-and-configuration/upgrading.markdown
Signed-off-by: Ole Herman Schumacher Elgesem <ole.elgesem@northern.tech>
(cherry picked from commit 44514610202a6e627af5ed9c34478409059e77d3)
=> Fixed order of systemctl/service args

reference/promise-types/files.markdown, reference/promise-types/files/edit_xml.markdown
=> Rename bundle edit_xml to just edit_xml

reference/enterprise-api-ref/sql-schema.markdown
=> ENT-3294 Document monitoring tables

enterprise-cfengine-guide/settings.markdown
=> ENT-4373 make subsections for role management settings guide

enterprise-cfengine-guide/hub_administration/reset-admin-creds.markdown
Do not overwrite email and roles in case if admin user exists
=> ENT-4149: Change reset administrative credentials documentation

reference/enterprise-api-ref/inventory.markdown
merge together:
cfengine/documentation#2057
cfengine/mission-portal#739
cfengine/nova#1336
=> ENT-4371: Allow inventory API to use multiple values for one filter.

reference/enterprise-api-ref/export-import-api.markdown
(cherry picked from commit 7f42c8a828e6fa558c4cb126b73705e23396cf1e)
=> ENT-4126 Add Import & Export API documentation (3.12)

guide/faq/enterprise-report-collection.markdown
Ticket: ENT-4462
(cherry picked from commit 3c7d2e92a83ca7ecf997082d795ca4c979573482)
=> Clarify why host count in cf-hub and Mission Portal can differ

reference/enterprise-api-ref/health-diagnostic.markdown
Merge together: 
https://github.com/cfengine/mission-portal/pull/774
https://github.com/cfengine/nova/pull/1369
=> ENT-4444 Add health diagnostic API documentation

reference/enterprise-api-ref/health-diagnostic.markdown
(cherry picked from commit 80988b4adb5a8a80df39fac4c14fe0f34a331af0)
=> ENT-4444 Add health diagnostic API documentation (3.12)

reference/functions.markdown
(cherry picked from commit c60cbb1588177f5e489d8d7c65f523e792eb085a)
=> Fixed syntax error in example (3.12)

reference/functions.markdown
(cherry picked from commit c60cbb1588177f5e489d8d7c65f523e792eb085a)
=> Fixed syntax error in example (3.10)

reference/enterprise-api-ref/health-diagnostic.markdown
https://github.com/cfengine/documentation/pull/2086
https://github.com/cfengine/mission-portal/pull/787
https://github.com/cfengine/nova/pull/1380
=> ENT-3950 Add dismiss possibility to health diagnostic API

guide/installation-and-configuration/upgrading.markdown, guide/introduction/directory-structure.markdown
Changed in cfengine/buildscripts@ab7005a.
Ticket: ENT-4564
=> Adapt to the change of the installation log filename

reference/functions/classfiltercsv.markdown
Ticket: CFE-3021
Blocked by: https://github.com/cfengine/core/pull/3595
=> CFE-3021: Added documentation entry for classfiltercsv

reference/enterprise-api-ref/sql-schema.markdown
=> ENT-4299 Add missing SQL schema documentation

guide/special-topics/content-driven-policy.markdown
=> Note deprecation of cdp_inputs since 3.6.0

guide/introduction/directory-structure.markdown, reference/enterprise-api-ref/sql-schema.markdown
Manually picked from master.
Ticket: ENT-4299
=> Added documentation for Status in sql schema

reference/enterprise-api-ref/sql-schema.markdown
=> ENT-4299 Reorder and add missing SQL schema documentation (3.12)

reference/enterprise-api-ref/federated-reporting-api.markdown
=> ENT-4676 Add Federated reporting API documentation

enterprise-cfengine-guide/hub_administration/extending-query-builder.markdown
=> Change extending-query-builder.markdown code blocks

reference/enterprise-api-ref/users-rbac.markdown
=> ENT-4797 Add parameters to User API create/update sections

reference/promise-types.markdown
https://github.com/cfengine/core/pull/3718
=> CFE-3084/master Clarified behavior of warn and nop in body action action_policy

guide/installation-and-configuration/general-installation/installation-community.markdown
The tutorial itself got removed in 3c85321b10f0a6e91c301e1b57bdb8bef64a8b2c.
=> Remove obsolete notice about tutorial.

enterprise-cfengine-guide/federated-reporting.markdown
=> ENT-4713: Added API and manual Federated Reporting setup docs

enterprise-cfengine-guide/hub_administration/extending-query-builder.markdown
=> ENT-4796 Improve extending query builder documentation

reference/language-concepts/variables.markdown
https://github.com/cfengine/core/pull/3732
=> CFE-3096: Added example showing how to reference values inside a data container

reference/functions/hostrange.markdown
Merge Together:
https://github.com/cfengine/core/pull/3744
=> CFE-3104/master Use hostrange() example from core

reference/functions/url_get.markdown
=> CFE-3107/3.12: Documented default values used for url_get()

reference/functions/url_get.markdown
=> CFE-3107/3.10 Documented default values used for url_get()

guide/installation-and-configuration/general-installation/installation-coreos.markdown
=> Fix CoreOS artifact name (without package release number)

reference/components/cf-check.markdown
Reverts cfengine/documentation#2197
=> Revert "Revert "CFE-3158/master Added cf-check to component documentation""

reference/functions.markdown, reference/promise-types.markdown
* Fixed syntax errors in examples.
* Removed confusing / unnecessary information.
* Since `if` seems to be preferred over `ifvarclass`, all the
information is now under `if`, and `ifvarclass` just tells
you to go to `if` section.
* Clarified the behavior of `if`/`unless` in edge cases, when
variables are never expanded.
* Added more examples.
See: https://tracker.mender.io/browse/CFE-2689
Ticket: CFE-2689
(cherry picked from commit 6b63a0f1db66eb121f1ef3214799e931f519d508)
=> Improved documentation for if/unless and function skipping

reference/functions/readintlist.markdown, reference/functions/readreallist.markdown, reference/functions/readstringlist.markdown
https://github.com/cfengine/core/pull/3878
=> CFE-3172/master Switched to using separate examples for readintlist, readreallist and readstringlist

reference/functions/data_regextract.markdown
=> CFE-3171/3.15: Added references to dotall and multiline modes for data_regextract()

reference/functions/data_regextract.markdown
=> CFE-3171/3.12: Added references to dotall and multiline modes for data_regextract()

reference/promise-types/packages.markdown
=> Added docs for snap package module

enterprise-cfengine-guide/federated-reporting.markdown
(cherry picked from commit a504b0a0362d5f015953c5f3ddbbb489bf589691)
=> Clarified steps for adding 3.12.x feeder to superhub Changelog: None

reference/enterprise-api-ref/file-changes.markdown
=> Added file changes API documentation

enterprise-cfengine-guide/reporting/reporting_ui.markdown
=> Added documentation regarding join strategy in the Query builder

enterprise-cfengine-guide/federated-reporting.markdown
=> Fixed internal links for "without API" sections.

enterprise-cfengine-guide/hosts-health.markdown
Merge together: 
https://github.com/cfengine/core/pull/3907
https://github.com/cfengine/enterprise/pull/557
https://github.com/cfengine/nova/pull/1537
https://github.com/cfengine/mission-portal/pull/930
https://github.com/cfengine/documentation/pull/2229
=> ENT-4406: Updated the explanation of duplicate host detection

reference/masterfiles-policy-framework/cfe_internal-core-watchdog-templates-watchdog.mustache.md, reference/masterfiles-policy-framework/cfe_internal-core-watchdog-watchdog.cf.md
This change integrates the watchdog implementation related files to the MPF
documentation section.
Ticket: ENT-4995
=> ENT-4995/3.12: Watchdog implementation

reference/masterfiles-policy-framework/cfe_internal-core-watchdog-watchdog.markdown, reference/masterfiles-policy-framework/cfe_internal-core-watchdog.markdown
=> ENT-4995/master: Added watchdog to MPF tree

reference/functions/nth.markdown
=> CFE-3194: Documentation for negative indices in Nth

enterprise-cfengine-guide/federated-reporting.markdown
=> Revised uninstall procedure to use target_state set to "off"

examples/example-snippets/promise-patterns/package_bundles.markdown
These names were changed in 3.6.0.
=> CFE-3205: Fixed various references to cfe_package bundles

enterprise-cfengine-guide/federated-reporting.markdown
Ticket: ENT-5108
Merge together:  
https://github.com/cfengine/mission-portal/pull/947
https://github.com/cfengine/system-testing/pull/274
https://github.com/cfengine/nova/pull/1557
https://github.com/cfengine/documentation/pull/2248
=> Changed fr/hub-state API from POST to PUT

enterprise-cfengine-guide/federated-reporting.markdown, reference/masterfiles-policy-framework/cfe_internal-federation-federation.markdown
=> ENT-5124: Added requirement of semanage command being installed to FR docs

reference/promise-types/files.markdown
merge together: https://github.com/cfengine/core/pull/3967
=> CFE-3217/master: Clarified the behavior of include_basedir

reference/promise-types/files.markdown
=> CFE-1782/master: Update reference to ticketing system

reference/promise-types/files.markdown
=> Fixed links

reference/functions/read_module_protocol.markdown, reference/functions/usemodule.markdown, reference/promise-types/commands.markdown
=> CFE-2876/master: Added documentation and cross-references for read_module_protocol()

reference/functions/basename.markdown
https://github.com/cfengine/core/pull/3977
Ticket: CFE-3196
=> CFE-3196/master: Added documentation for new function basename()

reference/promise-types/classes.markdown
=> CFE-3230/master: Added note clarifying when the output of select_class may be expected to change

reference/promise-types/classes.markdown
Ticket: CFE-3230
(cherry picked from commit 4948c0801ea626eede6734cca6724aec0b1ab8e8)
----
#
=> CFE-3230/3.12: Added note clarifying when the output of select_class may be expected to change

reference/promise-types/classes.markdown
Ticket: CFE-3230
(cherry picked from commit 4948c0801ea626eede6734cca6724aec0b1ab8e8)
----
#
=> CFE-3230/3.10: Added note clarifying when the output of select_class may be expected to change

reference/components/cf-hub.markdown
Ticket: CFE-3254
(cherry picked from commit 7a238a359b25e0e98af48cdbafadcfb64a791ab3)
=> CFE-3254/3.15: Added documentation for query_timeout

reference/functions/cf_version_after.markdown, reference/functions/cf_version_at.markdown, reference/functions/cf_version_before.markdown, reference/functions/cf_version_between.markdown, reference/functions/cf_version_maximum.markdown, reference/functions/cf_version_minimum.markdown
Ticket: CFE-3197
Need to merge this first: https://github.com/cfengine/core/pull/4083
=> CFE-3197: Documentation for cf_version functions

reference/functions/validdata.markdown, reference/functions/validjson.markdown
Ticket: CFE-2898
Needs to merge this first: https://github.com/cfengine/core/pull/4084
=> CFE-2898: Documentation entries for validdata and validjson

enterprise-cfengine-guide/federated-reporting.markdown
Not based on any exact research and measurements, but rather on
numbers we have seen in our FR tests and some small amounts of
data we got from our customers. See the ticket for more details.
Ticket: ENT-5132
=> Add a section about FR HW requirements

enterprise-cfengine-guide/federated-reporting.markdown
"If it is close to the configured refresh interval" instead of "If it close to the configured refresh interval"
=> Fixed tiny grammar issue

reference/functions/findfiles.markdown
=> Fixed note about brace expansion in globbing for findfiles()

reference/functions/findfiles.markdown
Ticket: CFE-2606
(cherry picked from commit 486869d2354c4d7309cd6a41a92e18e19c89a740)
=> CFE-2606/3.15: Fixed note about brace expansion in globbing for findfiles()

reference/functions/findfiles.markdown
Ticket: CFE-2606
(cherry picked from commit 486869d2354c4d7309cd6a41a92e18e19c89a740)
=> CFE-2606/3.12: Fixed note about brace expansion in globbing for findfiles()

reference/functions/findfiles.markdown
Ticket: CFE-2606
(cherry picked from commit 486869d2354c4d7309cd6a41a92e18e19c89a740)
=> CFE-2606/3.10: Fixed note about brace expansion in globbing for findfiles()

reference/special-variables/sys.markdown
Added in cfengine/core@7005511250.
=> Document the new $(sys.cf_version_release) variable

reference/components/cf-secret.markdown
=> ENT-5368/master: Added documentation for cf-secret

reference/promise-types/storage.markdown
Merge together: 
https://github.com/cfengine/core/pull/4173
=> Added panfs, cifs mount types

reference/promise-types/files.markdown
Ticket: ENT-5966
(cherry picked from commit 40c54301086278308ce13428970aa866c4d6e1c1)
----
#
=> ENT-5966/3.15: Switched from inline example to core example for illustrating inline mustache

reference/promise-types/files.markdown
Ticket: ENT-5966
(cherry picked from commit 40c54301086278308ce13428970aa866c4d6e1c1)
=> ENT-5966/3.12: Switched from inline example to core example for illustrating inline_mustache

enterprise-cfengine-guide/reporting.markdown
=> ENT-5965/master: Clarify how to control what is or isn't collected by cf-hub

enterprise-cfengine-guide/reporting.markdown
Ticket: ENT-5965
(cherry picked from commit 6e9e90342f214ea439fbf5345594614cade632a1)
----
#
=> ENT-5965/3.15: Clarify how to control what is or isn't collected by cf-hub

enterprise-cfengine-guide/reporting.markdown
Ticket: ENT-5965
(cherry picked from commit 6e9e90342f214ea439fbf5345594614cade632a1)
----
#
=> ENT-5965/3.12: Clarify how to control what is or isn't collected by cf-hub

reference/masterfiles-policy-framework/lib-vcs.markdown
(cherry picked from commit 053bc882125e181d44d705373e059f0def70db97)
=> Fixup lib/vcs example to be proper

guide/faq/enterprise-report-collection.markdown
=> ENT-5313/master: Added instructions for enabling report dumps to troubleshoot Enterprise reporting

reference/enterprise-api-ref/inventory.markdown
Ticket: ENT-6057
Merge together: https://github.com/cfengine/nova/pull/1690
=> Added new regex operators to Inventory API documentation

reference/promise-types/files.markdown
Ticket: ENT-6102
(cherry picked from commit a8faf0ee479084d6f074e483f5e322f265d8deb7)
=> Added note that copy_from preserve does not preserve ownership

guide/latest-release/supported-platforms.markdown
Ticket: ENT-6100
(cherry picked from commit 3efba65289869d0e0cdeb4f6dc39b58252e662f7)
=> Aligned supported platforms with download tables as of 3.15.2

guide/introduction/networking.markdown
(cherry picked from commit d91116ff8663271c6ca318e3878aa1803493394b)
=> small typo fix

enterprise-cfengine-guide/federated-reporting.markdown
(cherry picked from commit b7e83b879ec1881e5b78b5a15d595ee06a6d57cf)
=> Added prohibition on bootstrapping agents to superhub

reference/functions/storejson.markdown
=> CFE-3388/master: Switched storejson example from inline to external from core

guide/faq/mustache-templating.markdown
Ticket: CFE-3400
(cherry picked from commit 33c179b4d2b8108e0452f498a63f50179ccb32fc)
=> CFE-3400/3.15: Added Mustache FAQ entry for CFEngine specific extensions

guide/faq/mustache-templating.markdown
Ticket: CFE-3400
(cherry picked from commit 33c179b4d2b8108e0452f498a63f50179ccb32fc)
=> CFE-3400/3.12: Added Mustache FAQ entry for CFEngine specific extensions

reference/functions/readdata.markdown, reference/functions/readjson.markdown
New functions that are related to the old ones.
=> Add links to validjson/validdata to readjson/readdata respectively

guide/installation-and-configuration/pre-installation-checklist.markdown, guide/installation-and-configuration/pre-installation-checklist/verify-signatures.markdown
=> ENT-4791 Add documentation about verifying packages

guide/installation-and-configuration/pre-installation-checklist.markdown, guide/installation-and-configuration/pre-installation-checklist/verify-signatures.markdown
(cherry picked from commit 584ffa92a0a660ff32a0227ac61661e0cc59cc4d)
----
#
=> ENT-4791 Add documentation about verifying packages - 3.15

guide/installation-and-configuration/pre-installation-checklist.markdown, guide/installation-and-configuration/pre-installation-checklist/verify-signatures.markdown
=> ENT-4791 Add documentation about verifying packages - 3.12

reference/promise-types/vars.markdown
seems the correct value is eleven nines
=> Positive and negative values do not match

reference/enterprise-api-ref/host.markdown
ChangeLog: Extended Host API documentation with an example of getting hosts list grouped by hard classes
Ticket: ENT-6175
=> Extended Host API documentation

reference/enterprise-api-ref/host.markdown
=> Fixed Hosts API documentation formatting

reference/functions/iprange.markdown
Ticket: CFE-3450
(cherry picked from commit 3ae47e3c64c5f8dca5fe42a9635abfb0db37044a)
=> Made more obvious that iprange() interface is optional

reference/components/cf-secret.markdown
=> CFE-2613/master: Added cf-secret history

reference/promise-types/vars.markdown
=> CFE-3462/master: Added documentation about special cases in which variables are defined in foreign bundles

reference/enterprise-api-ref/actions-api.markdown
Ticket: ENT-6179
Merge together: https://github.com/cfengine/nova/pull/1722
=> Added Actions API documentation

reference/enterprise-api-ref/host.markdown
=> Changed the hosts/by-class API call documentation

reference/functions/getusers.markdown
=> CFE-3475/master: Made note about getusers() returning both local and remote users

reference/enterprise-api-ref/host.markdown
ChangeLog: Extended Host API documentation with an example of getting hosts list grouped by hard classes
Ticket: ENT-6175
=> Extended Host API documentation (3.15)

.mailmap
Discovered while running shortlog commands for:
https://cfengine.com/company/blog-detail/2020-retrospective/
=> Added Ihor aliases to mailmap

reference/promise-types/files.markdown
=> CFE-3541/master: Clarified description of depth-search xdev attribute behavior

reference/promise-types/files.markdown
Ticket: CFE-3541
(cherry picked from commit 1eb3b81d57eaaa2e71b98498f1654baa91396cdd)
=> CFE-3541/3.15: Clarified description of depth-search xdev attribute behavior

reference/promise-types/files.markdown
Ticket: CFE-3541
(cherry picked from commit 1eb3b81d57eaaa2e71b98498f1654baa91396cdd)
=> CFE-3541/3.12: Clarified description of depth-search xdev attribute behavior

reference/promise-types/vars.markdown
=> CFE-3551/master: Added inline JSON example

reference/promise-types/vars.markdown
(cherry picked from commit 1f1a232be7321f71001090becfc419edbf04f838)
=> CFE-3551/3.15: Added inline JSON example

reference/promise-types/vars.markdown
(cherry picked from commit 1f1a232be7321f71001090becfc419edbf04f838)
=> CFE-3551/3.12: Added inline JSON example

reference/masterfiles-policy-framework/services-autorun.markdown
=> CFE-3597/master: Clarified use of services/autorun/ in the MPF

reference/masterfiles-policy-framework/services-autorun.markdown
Ticket: CFE-3597
(cherry picked from commit cdcda52a47c8a66cfd358680096d5b2478d9619d)
=> CFE-3597/3.15: Clarified use of services/autorun/ in the MPF

reference/masterfiles-policy-framework/services-autorun.markdown
Ticket: CFE-3597
(cherry picked from commit cdcda52a47c8a66cfd358680096d5b2478d9619d)
=> CFE-3597/3.12: Clarified use of services/autorun/ in the MPF

reference/enterprise-api-ref/actions-api.markdown
=> Added trigger agent run API documentation

examples/tutorials/installing-cfengine-enterprise-policy-server.markdown
(cherry picked from commit 056672da93e6f9cf1cce3a1a098a27ba2906a359)
=> ENT-6853/3.15: Added Installing CFEngine Enterprise Policy Server to tutorials

examples/tutorials/installing-cfengine-enterprise-agent.markdown
(cherry picked from commit 0a1b5fbb2a91f02f315c6132b758b0b76ef5bf9e)
=> ENT-6853/master: Added installing enterprise agent tutorial

examples/tutorials/manage-ntp.markdown
Originally found: https://cfengine.com/learn/managing-network-time-protocol/
=> ENT-6853/master: Refactored and migrated tutorial on managing NTP from cfengine.com/learn

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
=> ENT-7000: Removed references to specific versions of Vagrant and VirtualBox (master)

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
Ticket: ENT-7000
(cherry picked from commit 4e1d279e62aa803804ab55d41f55458f54661af8)
=> ENT-7000: Removed references to specific versions of Vagrant and VirtualBox (3.17)

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
Ticket: ENT-7000
(cherry picked from commit 4e1d279e62aa803804ab55d41f55458f54661af8)
=> ENT-7000: Removed references to specific versions of Vagrant and VirtualBox (3.15)

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
Ticket: ENT-7000
(cherry picked from commit 4e1d279e62aa803804ab55d41f55458f54661af8)
=> ENT-7000: Removed references to specific versions of Vagrant and VirtualBox (3.12)

reference/promise-types.markdown
=> CFE-3636: Switched to live examples from core for body inheritance (master)

reference/functions/string.markdown
=> CFE-3476: Added string() policy function documentation

reference/functions/int.markdown
=> CFE-3616: Added int() policy function documentation

reference/enterprise-api-ref/cmdb-api.markdown
=> Added CMDB API documentation

enterprise-cfengine-guide/high-availability.markdown
(cherry picked from commit 63b15866bd5149c65fef90cc8e9589cfdf9729ab)
=> Corrected headers in HA docs (3.15)

enterprise-cfengine-guide/health.markdown, enterprise-cfengine-guide/hosts-health.markdown, enterprise-cfengine-guide/user-interface.markdown
=> ENT-7285: Separated Hosts and Health in Enterprise docs (master)

enterprise-cfengine-guide/federated-reporting.markdown
=> ENT-7312: Fixed link to federation semanage_installed (master)

reference/promise-types/commands.markdown
=> CFE-3711: Added link to Bundles and Bodies in the MPF related to commands (master)

reference/promise-types/commands.markdown
Ticket: CFE-3711
(cherry picked from commit 78d5f60b113b0a99581c729ba0edfe2c43979a79)
=> CFE-3711: Added link to Bundles and Bodies in the MPF related to commands (3.18)

reference/promise-types/commands.markdown
Ticket: CFE-3711
(cherry picked from commit 78d5f60b113b0a99581c729ba0edfe2c43979a79)
=> CFE-3711: Added link to Bundles and Bodies in the MPF related to commands (3.15)

reference/promise-types/files.markdown
Ticket: CFE-3718
(cherry picked from commit f16a787eacfffab141f73179efb3b385d632725a)
=> CFE-3718: Replaced snippet with full example from core (3.18)

reference/promise-types/files.markdown
Ticket: CFE-3718
(cherry picked from commit f16a787eacfffab141f73179efb3b385d632725a)
=> CFE-3718: Replaced snippet with full example from core (3.15)

guide/special-topics/security.markdown
I made some tweaks which should help pass the build, and I added a comment with
the text from the old cfengine.com/learn section on security. The comment
includes the link to the youtube video presentation where Diego discusses
security. Since the video is private, I figured that this was the best place to
leave a bread crumb.
=> ENT-6853:Published special topics Security

guide/special-topics/security.markdown
=> ENT-6853: Added video presentation to security special topic

guide/special-topics/security.markdown
(cherry picked from commit b254c363d061ddc3bbce301953cf2ca4ee9b8b6b)
=> Added video presentation to security special topic

guide/special-topics/security.markdown
(cherry picked from commit b254c363d061ddc3bbce301953cf2ca4ee9b8b6b)
=> ENT-6853: Added video presentation to security special topic (3.15)

reference/masterfiles-policy-framework/services-autorun.markdown
Trying to keep the docs closer to the implementation.
Ticket: CFE-3716
=> CFE-3716: Switched services/autorun docs to include from masterfiles

enterprise-cfengine-guide/federated-reporting.markdown
=> ENT-7492 Fixup psql command for upgrading superhub

reference/masterfiles-policy-framework/services-autorun.markdown
Trying to keep the docs closer to the implementation.
Ticket: CFE-3716
(cherry picked from commit b7b3da7e78496f34e92006dadbd788d499fa9aa4)
=> CFE-3716: Switched services/autorun docs to include from masterfiles (3.18)

reference/language-concepts/augments.markdown
=> CFE-3730: Added examples for augments inputs

reference/language-concepts/augments.markdown
Ticket: CFE-3730
(cherry picked from commit d729e61d6b7cd5a28f838aa9f9155eb3d22bff02)
=> CFE-3730: Added examples for augments inputs (3.18)

enterprise-cfengine-guide/federated-reporting.markdown
=> ENT-7492 Add superhub upgrade instructions (3.15)

enterprise-cfengine-guide/federated-reporting.markdown
=> ENT-7492 Add superhub upgrade instructions (3.18)

reference/functions/mergedata.markdown
=> CFE-3733: Added docs indicating that the last key wins when using mergedata()

reference/enterprise-api-ref/host.markdown
=> ENT-7469: Added documentation for Deleted hosts list API call

reference/enterprise-api-ref/host.markdown
Ticket: ENT-7469
(cherry picked from commit 35ff0ea9985da65b81fd5ecae4f10f077bebc787)
=> Added documentation for Deleted hosts list API call (3.18)

reference/language-concepts/augments.markdown
=> CFE-3730: Added examples for augments inputs (3.15)

reference/language-concepts/modules.markdown, reference/language-concepts/modules/package-module-api.markdown
=> ENT-7560: Added Modules as a language concept

guide/additional-resources.markdown
=> ENT-7627: Changed IRC channel reference from freenode to libera.chat

guide/additional-resources.markdown
Ticket: ENT-7627
(cherry picked from commit 5a5a54871b2ae1e78059bd2dc757d37541da5b5d)
=> ENT-7627: Changed IRC channel reference from freenode to libera.chat (3.18)

guide/additional-resources.markdown
Ticket: ENT-7627
(cherry picked from commit 5a5a54871b2ae1e78059bd2dc757d37541da5b5d)
=> ENT-7627: Changed IRC channel reference from freenode to libera.chat (3.15)

reference/components.markdown
=> ENT-7594: Added docs for system_log_level in body common control

examples.markdown, examples/tutorials/custom_inventory.markdown, examples/tutorials/distribute-files-from-a-central-location.markdown, guide/faq/fix-undefined-body-error.markdown, guide/faq/integrate-custom-policy.markdown, guide/faq/manual-execution.markdown, guide/installation-and-configuration/general-installation.markdown, guide/installation-and-configuration/secure-bootstrap.markdown, guide/introduction/networking.markdown, index.markdown, reference.markdown, reference/components.markdown, reference/components/cf-agent.markdown, reference/components/cf-serverd.markdown, reference/components/file_control_promises.markdown, reference/functions/hostsseen.markdown, reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown, reference/language-concepts/augments.markdown, reference/language-concepts/bodies.markdown, reference/promise-types.markdown, reference/promise-types/access.markdown, reference/promise-types/files.markdown, reference/promise-types/packages.markdown, reference/special-variables/connection.markdown
=> ENT-7572: Renamed Components and Common Control to Components

examples.markdown, examples/tutorials/custom_inventory.markdown, examples/tutorials/distribute-files-from-a-central-location.markdown, guide/faq/fix-undefined-body-error.markdown, guide/faq/integrate-custom-policy.markdown, guide/faq/manual-execution.markdown, guide/installation-and-configuration/general-installation.markdown, guide/installation-and-configuration/secure-bootstrap.markdown, guide/introduction/networking.markdown, index.markdown, reference.markdown, reference/components.markdown, reference/components/cf-agent.markdown, reference/components/cf-serverd.markdown, reference/components/file_control_promises.markdown, reference/functions/hostsseen.markdown, reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown, reference/language-concepts/augments.markdown, reference/language-concepts/bodies.markdown, reference/promise-types.markdown, reference/promise-types/access.markdown, reference/promise-types/files.markdown, reference/promise-types/packages.markdown, reference/special-variables/connection.markdown
Ticket: ENT-7572
(cherry picked from commit 49a921bedcd42dc868fc072ca03016b19cf1c352)
=> ENT-7572: Renamed Components and Common Control to Components (3.18)

examples.markdown, examples/tutorials/custom_inventory.markdown, examples/tutorials/distribute-files-from-a-central-location.markdown, guide/faq/fix-undefined-body-error.markdown, guide/faq/integrate-custom-policy.markdown, guide/faq/manual-execution.markdown, guide/installation-and-configuration/general-installation.markdown, guide/installation-and-configuration/secure-bootstrap.markdown, guide/introduction/networking.markdown, index.markdown, reference.markdown, reference/components.markdown, reference/components/cf-agent.markdown, reference/components/cf-serverd.markdown, reference/components/file_control_promises.markdown, reference/functions/hostsseen.markdown, reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown, reference/language-concepts/augments.markdown, reference/language-concepts/bodies.markdown, reference/promise-types.markdown, reference/promise-types/access.markdown, reference/promise-types/files.markdown, reference/promise-types/packages.markdown, reference/special-variables/connection.markdown
Ticket: ENT-7572
(cherry picked from commit 49a921bedcd42dc868fc072ca03016b19cf1c352)
=> ENT-7572: Renamed Components and Common Control to Components (3.15)

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
=> CFE-3775: Added link from packagesmatching* functions to related MPF tunables

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
=> CFE-3775: Added link from packagesmatching* functions to related MPF tunables (3.15)

reference/functions/and.markdown, reference/functions/not.markdown, reference/functions/or.markdown
=> CFE-3777: Added history about return type change

reference/functions/and.markdown, reference/functions/not.markdown, reference/functions/or.markdown
Ticket: CFE-3777
(cherry picked from commit fdb2edcf6b495e080fc5c9d77a45ff990c3a1e0b)
=> CFE-3777: Added history about return type change (3.18)

reference/functions/and.markdown, reference/functions/not.markdown, reference/functions/or.markdown
Ticket: CFE-3777
(cherry picked from commit fdb2edcf6b495e080fc5c9d77a45ff990c3a1e0b)
=> CFE-3777: Added history about return type change (3.15)

reference/functions/and.markdown, reference/functions/not.markdown, reference/functions/or.markdown
Reverts cfengine/documentation#2552
=> Revert "CFE-3777: Added history about return type change (3.15)"

reference/functions/data_sysctlvalues.markdown
=> CFE-3783: Switched to runable example from core

reference/functions/classfiltercsv.markdown
Ticket: CFE-3796
(cherry picked from commit b5eec7f1e4ea0dc57b51432077319446b735051d)
=> CFE-3796: Added note about classfiltercsv() being RFC 4180 compliant (3.18)

reference/enterprise-api-ref/export-import-compliance-report-api.markdown
=> Added Export/Import compliance reports API documentantion

reference/enterprise-api-ref/export-import-compliance-report-api.markdown
Ticket: ENT-6470
(cherry picked from commit aec229386ef2edc5d384835656034ac8c8382862)
=> ENT-6470: Added Export/Import compliance reports API documentantion (3.18)

reference/enterprise-api-ref/host.markdown
=> Added inventoryFile parameter to the Hosts by class API documentation

reference/enterprise-api-ref/host.markdown
Ticket: ENT-7664
(cherry picked from commit ee3f506db582b23a39893ccc183fd57b5a655d31)
=> ENT-7764: Added inventoryFile parameter to the Hosts by class API documentation (3.18)

reference/enterprise-api-ref/host.markdown
https://github.com/cfengine/documentation/pull/2560/files#r742348283
=> Fixed typo; wby -> by

reference/enterprise-api-ref/host.markdown
(cherry picked from commit 2e46e012475c4b647515f9857a7bb8f612b480b3)
=> Fixed typo; wby -> by (3.18)

enterprise-cfengine-guide/federated-reporting.markdown
=> ENT-8241 Add needed steps to removing FR feeder deletion steps

enterprise-cfengine-guide/federated-reporting.markdown
Ticket: none
(cherry picked from commit 5d8e5011edf3e4ef0d9c749c62959b05ec7e93df)
=> ENT-8241: Add needed steps to removing FR feeder deletion steps (3.18)

enterprise-cfengine-guide/federated-reporting.markdown
Ticket: none
(cherry picked from commit 5d8e5011edf3e4ef0d9c749c62959b05ec7e93df)
=> ENT-8241 Add needed steps to removing FR feeder deletion steps (3.15)

reference/masterfiles-policy-framework/modules-packages-vendored-WiRunSQL.vbs.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-apk.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-apt_get.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-freebsd_ports.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-msiexec-list.vbs.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-msiexec.bat.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-nimclient.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-pkg.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-pkgsrc.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-slackpkg.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-snap.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-yum.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored-zypper.mustache.markdown, reference/masterfiles-policy-framework/modules-packages-vendored.markdown, reference/masterfiles-policy-framework/modules-packages.markdown, reference/masterfiles-policy-framework/modules-promises.markdown, reference/masterfiles-policy-framework/modules.markdown
=> Added documentation for masterfiles modules directory

enterprise-cfengine-guide/federated-reporting.markdown, reference/enterprise-api-ref/federated-reporting-api.markdown
=> Adjsuted FR documentation

enterprise-cfengine-guide/hub_administration/reset-admin-creds.markdown
=> ENT-7742 Added MP and CFE_ROBOT credentials rotation docs

enterprise-cfengine-guide/hub_administration/reset-admin-creds.markdown
Ticket: ENT-7742
(cherry picked from commit 1e2384db6eb5802e7bad3f9f60c38568981c7643)
=> ENT-7742 Added MP and CFE_ROBOT credentials rotation docs (3.15)

enterprise-cfengine-guide/hub_administration/reset-admin-creds.markdown
Ticket: ENT-7742
(cherry picked from commit 1e2384db6eb5802e7bad3f9f60c38568981c7643)
=> ENT-7742 Added MP and CFE_ROBOT credentials rotation docs (3.18)

reference/promise-types/packages.markdown
=> CFE-3568: Added docs for new pkg module features (master)

reference/promise-types/packages.markdown
Ticket: CFE-3568
(cherry picked from commit d231a44d5a8af0aba5cedebe5f78b0cf59dd1e92)
=> CFE-3568: Added docs for new pkg module features (3.18)

reference/enterprise-api-ref/sql-schema.markdown
=> ENT-8389: Fixed grammar, missing word

guide/getting-started-with-cfengine-build/developing-modules.markdown
=> Getting started: Fixed a typo

guide/faq/what-did-cfengine-change.markdown
=> ENT-7713: Added explanations of the content in the page

reference/promise-types/files.markdown
=> CFE-951: Changed default value for rxdirs

guide/faq/what-did-cfengine-change.markdown
Ticket: ENT-7713
(cherry picked from commit a1d24c57968ae16b9573ecdd79f609e847af6156)
=> ENT-7713: Added explanations of the content in the page (3.18)

index.markdown
=> Changed index.markdown content

guide/getting-started-with-cfengine-build/developing-modules.markdown, guide/getting-started-with-cfengine-build/reporting-and-web-ui.markdown, guide/getting-started-with-cfengine-build/writing-policy.markdown
- Getting started: Reworded bad sentence
- Getting started: Simplified a cf-remote deploy command
- Getting started: Added a tip about modules vs CMDB
- Getting started: Fixed dead links
=> Getting started: Smaller fixes

reference/promise-types/processes.markdown
Ticket: ENT-5899
Ticket: CFE-2207
=> Introduce the new syntax for sleeps between signals

enterprise-cfengine-guide/federated-reporting.markdown
- Removed trailing whitespace
- Updated link to cf-remote
=> Updated link to cf-remote

enterprise-cfengine-guide/federated-reporting.markdown
(cherry picked from commit 57095397f267aee14c0b2c80092a23934b177d53)
=> Updated link to cf-remote (3.15)

enterprise-cfengine-guide/reporting.markdown
Since 3.6.0 there has been no capability to influence variable collection based
on variable names.
=> ENT-8547: Redacted mention of underscore prefixed variables

reference/functions/packagesmatching.markdown
Ticket: ENT-8616
(cherry picked from commit f16d323fd50560d3a87b1486ee3061f7b65de804)
=> ENT-8616: Fixed typo in packagesmatching() docs (3.15)

reference/language-concepts/augments.markdown
Merge Together:
- https://github.com/cfengine/core/pull/4956
=> CFE-3975: Added note about behavior of concurrent vars and variables keys in Aguments

reference/language-concepts/namespaces.markdown
(cherry picked from commit 3abe1edfd64dd9c2b20d04b0af07220a89d1e816)
=> add missing but to make the sentance make sense.

reference/language-concepts/modules.markdown
=> ENT-8793: Added notes about caonification and namespaces with respect toclasses and vars modules

reference/language-concepts/modules.markdown
Ticket: ENT-8793
(cherry picked from commit 0323541034576593462a82a285e1c4bfdcdedb11)
=> ENT-8793: Added notes about caonification and namespaces with respect toclasses and vars modules (3.18)

enterprise-cfengine-guide/federated-reporting.markdown
https://github.com/cfengine/documentation/pull/2734
=> ENT-8832 Add Distributed cleanup utility documentation 

enterprise-cfengine-guide/federated-reporting.markdown
Ticket: ENT-8832
(cherry picked from commit 7f6eefdb53963a5cb2ab3ad256702a8d75cac9eb)
=> ENT-8832 Add Distributed Cleanup details to Federated Reporting docs (3.18)

guide/faq/bootstrap-failed.markdown
=> ENT-8949: Added FAQ page for bootstrapping

versions.markdown
Added page where all versions will be listed
Ticket: ENT-8786
=> Added versions page

enterprise-cfengine-guide/user-interface.markdown
Adjusted old images sizes on the dashboard page
Ticket: ENT-8869
Changelog: Resized the images on the dashboard page
=> ENT-8869: Resized the images size on the Dashboard page (master)

enterprise-cfengine-guide/measurements.markdown
Resized the image on the Measurements app page
Ticket: ENT-8881
Changelog: Resized the image on the Measurements app page
=> ENT-8881: Resized the images size on the Measurements page (master)

enterprise-cfengine-guide/settings.markdown
Adjusted image sizes on the setting page
Ticket: ENT-8876
Changelog: Resized the images on the setting page
=> ENT-8876: Resized the images size on the setting page (master)

enterprise-cfengine-guide.markdown
Ticket: n/a
Changelog: Resized image on the CFEngine Enterprise page (master)
=> Resized image on the CFEngine Enterprise page (master)

enterprise-cfengine-guide/reporting/reporting_ui.markdown
Resized images on the [Reporting UI page.](https://docs.cfengine.com/docs/master/enterprise-cfengine-guide-reporting-reporting_ui.html)
Ticket: ENT-8879
Changelog: Resized images on the Reporting UI page.
=> ENT-8879: Resized images on the Reporting UI page (master)

enterprise-cfengine-guide/federated-reporting.markdown
Resized the images on the [Federated reporting page.](https://docs.cfengine.com/docs/master/enterprise-cfengine-guide-federated-reporting.html)
Ticket: ENT-8880
Changelog: Resized the image on the Federated reporting page
=> ENT-8880: Resized images on the Federated reporting page (master)

index.markdown
lts_versions_list.html contain pre-generated LTS versions list
=> Included lts_versions_list.html into index.markdown

reference/promise-types/files.markdown, reference/promise-types/files/edit_line.markdown, reference/special-variables/edit.markdown
=> ENT-5866: Added documentation for edit.empty_before_use special variable

reference/special-variables/edit.markdown
=> CFE-4016: Added examples showing special edit vars

web-ui/hub_administration/extending-query-builder.markdown
Resized the images in [Extend query page](https://docs.cfengine.com/docs/master/web-ui-hub_administration-extending-query-builder.html)
Ticket: ENT-8883
Changelog: Resized the images in Extend query page
=> ENT-8883: Resized the images in Extend query page

web-ui/hub_administration/extending-mission-portal.markdown
Resized the image size on the Extending Mission Portal page.
Ticket: ENT-8882
Changelog: Resized the image size on the Extending Mission Portal page(master).
=> ENT-8882: Resized the image on the Extending Mission Portal page(master)

web-ui/hosts.markdown
Resized the images on the hosts page.
Ticket: ENT-9017
Changelog: Resized the images on the hosts page.
=> ENT-9017: Resized the images on the hosts page

reference/components/cf-monitord.markdown
=> ENT-9073: Added standard measurements that were not mentioned

reference/components/cf-monitord.markdown
Ticket: ENT-9073
(cherry picked from commit c2829c4d7263699d68ac0e5e9bc757f97bcb4d9a)
=> ENT-9073: Added standard measurements that were not mentioned (3.18)

reference/components/cf-monitord.markdown
Ticket: ENT-9073
(cherry picked from commit c2829c4d7263699d68ac0e5e9bc757f97bcb4d9a)
=> ENT-9073: Added standard measurements that were not mentioned (3.15)

reference/promise-types/custom.markdown
Ticket: CFE-3433
https://github.com/cfengine/core/pull/5018
https://github.com/cfengine/documentation/pull/2842
=> Add docs for the 'action_policy' custom module feature

reference/promise-types/custom.markdown
=> [3.18.x] Add docs for the 'action_policy' custom module feature

reference/components/cf-monitord.markdown
I have added what I could scrape from the code.
But, I am very unsure about what I have so need someone with an eye for C to review this closely.
=> ENT-9074: Added preliminary documentation about statistical classes

reference/components/cf-monitord.markdown
At least the available suffixes and prefixes
Ticket: ENT-9074
(cherry picked from commit d0826865a38a269d513e2abfaf9e307988eb27fb)
=> ENT-9074: Added preliminary documentation about statistical classes (3.18)

reference/components/cf-monitord.markdown
At least the available suffixes and prefixes
Ticket: ENT-9074
(cherry picked from commit d0826865a38a269d513e2abfaf9e307988eb27fb)
=> ENT-9074: Added preliminary documentation about statistical classes (3.15)

generator/_assets/js/custom.js, generator/_assets/styles/less/menu.less, generator/_plugins/navigation.rb, generator/build/main.sh
Open nested menu when click on arrows instead of opening page
=> Changed left desktop menu behaviour

web-ui.markdown
Ticket: ENT-9117
Changelog: Fixed the typo
=> ENT-9117: Fixed the typo

generator/_assets/js/custom.js, generator/_assets/js/dropdown.js
=> Fixed navigation on build previews

generator/_assets/css/style.css
=> ENT-9118: Fix fonts/3.18

generator/_assets/css/style.css
Ticket: ENT-9118
(cherry picked from commit 906c63ac4b3ddaa594f5405be0c8d2709abba58f)
=> ENT-9118: Added monospace, sans-serif alternatives for pre elements (3.15)

generator/build/search/createIndex.js
=> Added document headers to search index

generator/_assets/js/custom.js, generator/_assets/styles/less/base.less
=> Added links to articles sections

generator/_assets/js/custom.js
=> Fixed JS minification

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
=> Added more specific information about packages*matching functions

reference/promise-types/files.markdown
Ticket: ENT-9194
(cherry picked from commit bc2e964862a10de603676ba507f66a8f4522028c)
=> ENT-9194: Cleaned up history for acl attribute

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
=> ENT-9080: Corrected package*matching docs re: --file rather than --bundlesequence

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
Ticket: ENT-9080
(cherry picked from commit fd95328cf7f1ae27de61deb44884ccadd5775bd2)
=> ENT-9080: Added more specific information about packages*matching functions (3.18)

generator/_includes/head.html, index.markdown
- Removed one extra space in page titles
- Fixed typo in home page
=> Fixed small typos

generator/_includes/breadcrumbs.html
=> Fixed the last breadcrumbs item url

reference/language-concepts/augments.markdown
Backports of:
https://github.com/cfengine/documentation/pull/2740
https://github.com/cfengine/documentation/pull/2741
=> Improved title and content around augments and MPF (3.18)

api/enterprise-api-examples/changes-api-usage.markdown
=> ENT-9347: Fixed changes API example syntax for include[]

examples/enterprise-api-examples/changes-api-usage.markdown
Ticket: ENT-9347
(cherry picked from commit 26e1e3aee0d8c8b7b16dcc77d25add0e1c142fc3)
=> ENT-9347: Fixed changes API example syntax for include[] (3.18)

examples/enterprise-api-examples/changes-api-usage.markdown
Ticket: ENT-9347
(cherry picked from commit 26e1e3aee0d8c8b7b16dcc77d25add0e1c142fc3)
=> ENT-9347: Fixed changes API example syntax for include[] (3.15)

overview/directory-structure.markdown, resources/additional-topics/security.markdown
=> ENT-8107: Redacted mentions of twin from docs

guide/introduction/directory-structure.markdown, guide/special-topics/security.markdown
Ticket: ENT-8107
(cherry picked from commit 76b4f64ae61218be92c098ae0578807d18315af8)
=> ENT-8107: Redacted mentions of twin from docs (3.18)

guide/introduction/directory-structure.markdown, guide/special-topics/security.markdown
Ticket: ENT-8107
(cherry picked from commit 76b4f64ae61218be92c098ae0578807d18315af8)
=> ENT-8107: Redacted mentions of twin from docs (3.15)

reference/language-concepts/classes.markdown
=> CFE-4063: Added link targets for variable class expressions and automatic canonification

reference/language-concepts/classes.markdown
Ticket: CFE-4063
(cherry picked from commit c7fd53c92db359a890cdcecb9e0b5ec6f50751d0)
=> CFE-4063: Added link targets for variable class expressions and automatic canonification (3.18)

reference/language-concepts/classes.markdown
Ticket: CFE-4063
(cherry picked from commit c7fd53c92db359a890cdcecb9e0b5ec6f50751d0)
=> CFE-4063: Added link targets for variable class expressions and automatic canonification (3.15)

api/enterprise-api-ref/build-api.markdown
This change also should add missing headings into the TOC
=> Changed Build API nested headings from h1 to h2

generator/_assets/styles/less/article.less, generator/_assets/styles/less/font.less, generator/_assets/styles/less/home.less, generator/build/main.sh
=> Added red hat text font

getting-started/modules-from-cfengine-build.markdown
We got feedback that this module is maybe too advanced for someone who is just getting started.
=> ENT-9173: Getting started: Replaced HTTP module with the easier all-packages-upgraded

examples/tutorials/writing-and-serving-policy/authoring-policy-tools-and-workflow.markdown, web-ui/hub_administration/policy-deployment.markdown
=> ENT-9094: Added notes about excluding cf_promises* generated files from VCS

enterprise-cfengine-guide/hub_administration/policy-deployment.markdown, guide/writing-and-serving-policy/authoring-policy-tools-and-workflow.markdown
Ticket: ENT-9094
(cherry picked from commit b9ff971aedd327ec44ade2c4654ea983649a7ccb)
=> ENT-9094: Added notes about excluding cf_promises* generated files from VCS (3.18)

resources/faq/tuning-postgresql.markdown
=> ENT-9553: Added FAQ page about tuning PostgreSQL config

generator/_assets/js/custom.js, generator/_assets/styles/less/article.less, generator/_assets/styles/less/base.less, generator/_assets/styles/less/home.less
Changed home page links weight
Fixed images view under li elements
Ticket: ENT-9537
ChangeLog: None
=> Adjusted styles

examples/enterprise-api-examples/browsing-host-information.markdown, reference/enterprise-api-ref/host.markdown
Ticket: ENT-9577
(cherry picked from commit b1b9633d9ca02a73798350d2f96c73ff48cf13de)
=> ENT-9577: Added cross-reference linking host deletion example and API (3.18)

examples/enterprise-api-examples/browsing-host-information.markdown, reference/enterprise-api-ref/host.markdown
Ticket: ENT-9577
(cherry picked from commit b1b9633d9ca02a73798350d2f96c73ff48cf13de)
=> ENT-9577: Added cross-reference linking host deletion example and API (3.15)

reference/functions/accumulated.markdown, reference/functions/ago.markdown, reference/functions/irange.markdown, reference/functions/now.markdown, reference/promise-types/files.markdown, reference/promise-types/processes.markdown
=> CFE-4095: Added cross references for function irange()

generator/_config.yml
=> ENT-9294: Bumped version for 3.15.7

generator/_assets/js/custom.js
=> Removed trailing newlines from the copy to clipboard text

generator/_assets/styles/less/base.less, generator/_assets/styles/less/home.less, generator/_assets/styles/less/pages.less
=> Centered docs for smaller than 951px width

api/enterprise-api-ref/build-api.markdown
=> Added Build module input API documentation

.github/workflows/markdowner.yml
=> GH Action: Updated python to 3.7

generator/_scripts/cfdoc_macros.py
=> Fixed broken reference to Common Attributes

generator/_scripts/cfdoc_macros.py
Ticket: CFE-4128
(cherry picked from commit cb4ed3c8defba6cef24739795143282b368c85af)
=> CFE-4128: Added description from syntax description to function attributes macro (3.18)

generator/_scripts/cfdoc_macros.py
(cherry picked from commit a90167a715b18a6bd83bc39984518ea9861e5238)
=> CFE-4127: Fixed function attributes macro description for list of options

generator/_scripts/cfdoc_macros.py
(cherry picked from commit a90167a715b18a6bd83bc39984518ea9861e5238)
=> CFE-4127: Fixed function attributes macro description for list of options (3.18)

generator/_assets/styles/less/header.less, generator/_includes/header_nav.html
=> Made search icon clickable

generator/_assets/styles/less/header.less, generator/_includes/header_nav.html
Ticket: ENT-9599
(cherry picked from commit d0287cee7ee2a12612fefac8f25a3b84057e5502)
=> Made search icon clickable (3.21)

generator/_assets/styles/less/base.less
=> Do not show code title for the default code blocks

generator/_assets/styles/less/base.less
Ticket: ENT-9306
(cherry picked from commit c5c753f7599c230ba6fb4b561f114df5f2837886)
=> Do not show code title for the default code blocks (3.21)

generator/_scripts/cfdoc_macros.py
Ticket: CFE-4119
(cherry picked from commit 1aa87969d2c20d963bfd362b67bc4200a1bee4f0)
=> Fixed common attributes links selecting when a promise type with the same name exists (3.21)

generator/_scripts/cfdoc_macros.py
Ticket: CFE-4119
(cherry picked from commit 1aa87969d2c20d963bfd362b67bc4200a1bee4f0)
=> Fixed common attributes links selecting when a promise type with the same name exists (3.18)

generator/_scripts/cfdoc_patch_header_nav.py
Ticket: ENT-9754
(cherry picked from commit 3d3b5fd4a553088413edd338cf258da02d99a19d)
=> Preserve same page on version switching (3.21)

reference/functions/findfiles_up.markdown
Ticket: CFE-4144
(cherry picked from commit 1e6f042ad425ab4aea144a65acd86d14168885f0)
=> CFE-4144: Fixed typos in findfiles_up() description (3.21)

reference/functions/findfiles_up.markdown
Ticket: CFE-4144
(cherry picked from commit 1e6f042ad425ab4aea144a65acd86d14168885f0)
=> CFE-4144: Fixed typos in findfiles_up() description (3.18)

reference/language-concepts/augments.markdown
=> CFE-4158: Clarified that Augments does not expand CFEngine variables

reference/functions/parsejson.markdown
=> CFE-4162: Added note that parsejson() does not parse primitives

getting-started/installation/upgrading.markdown
=> ENT-9924: Added extra note about the importance of the MPF upgrade

guide/installation-and-configuration/upgrading.markdown
=> ENT-9942: Added extra note about the importance of the MPF upgrade

generator/_assets/styles/less/menu.less
Ticket: ENT-9756
ChangeLog: None
=> Fixed wrong position of the menu arrow

generator/_assets/styles/less/menu.less
Ticket: ENT-9756
ChangeLog: None
=> ENT-976: Fixed wrong position of the menu arrow (3.21)

reference/functions/parsejson.markdown
=> CFE-4162: Added note that parsejson() does not parse primitives (3.18)

.github/workflows/markdowner.py, examples/tutorials/custom_inventory.markdown, examples/tutorials/distribute-files-from-a-central-location.markdown, examples/tutorials/integrating-alerts-with-pager-duty.markdown, examples/tutorials/integrating-with-sumo-logic.markdown, examples/tutorials/writing-and-serving-policy.markdown, generator/_scripts/cfdoc_bootstrap.py, generator/_scripts/cfdoc_environment.py, generator/_scripts/cfdoc_git.py, generator/_scripts/cfdoc_linkresolver.py, generator/_scripts/cfdoc_macros.py, generator/_scripts/cfdoc_metadata.py, generator/_scripts/cfdoc_patch_header_nav.py, generator/_scripts/cfdoc_postprocess.py, generator/_scripts/cfdoc_preprocess.py, generator/_scripts/cfdoc_printsource.py, generator/_scripts/cfdoc_qa.py, generator/_scripts/cfdoc_sourcelinks.py, overview/directory-structure.markdown, reference/language-concepts.markdown, reference/language-concepts/variables.markdown, release-notes/whatsnew/changelog-core.markdown, resources/additional-topics/glossary.markdown, resources/external-resources.markdown, web-ui/federated-reporting.markdown, web-ui/hub_administration/extending-query-builder.markdown, web-ui/settings.markdown
- Normalized capitalization of changelog
- Removed duplicate table of contents
- Reformatted python files with black
- Changed more headings to be sentence case
- Removed non-ascii non-breaking space character
=> More cleanups of capitalization, table of contents, etc.

overview/glossary.markdown
- Glossary: Added some details on classes and class guards
- Glossary: Reformatted markdown for nicer editing / review
- Glossary: Fixed capitalization, grammar, markup
=> Improvements to the CFEngine glossary

generator/_config.yml
=> ENT-10110: Updated versions for 3.21.2 (3.21)

api/enterprise-api-ref/personal-groups.markdown, api/enterprise-api-ref/shared-groups.markdown
=> Added Groups API documentation

generator/_config.yml
=> ENT-10317: Updated master to 3.23

redirects.conf
=> ENT-9747: Moved redirects from infra repo

overview/how-cfengine-works.markdown
(cherry picked from commit d7974a3cc2e8e8b2318521984e0443f4ab8127d5)
=> How CFEngine works: Small improvements on markup and heading levels (3.21)

resources/additional-topics/hierarchies.markdown
* fix accidental code quotes
* remove code TOC at the end
* mark headers to be included in TOC
=> Improve rendering on hierarchies page

generator/_includes/footer.html, legal.markdown
(cherry picked from commit ab6d26ed0eb808a53fbdacaec7e2a4a7e99c6f7d)
=> Fixed capitalization in legal page (3.21)

examples/tutorials/masterfiles_policy_framework_upgrade.markdown
This document was authored in org-mode as a literate document. It was exported
to markdown
=> Updated MPF upgrade tutorial/example

examples/tutorials/masterfiles_policy_framework_upgrade.markdown
This document was authored in org-mode and exported to markdown. Org-id links
were manually culled after export.
=> Updated MPF upgrade example

generator/_config.yml
=> ENT-10546: Updated current release version for 3.21.3 (3.21)

generator/_config.yml
=> ENT-10572: Updated current release version to 3.18.6 (3.18)

generator/_assets/styles/less/article.less, generator/_assets/styles/less/base.less, generator/_assets/styles/less/header.less, generator/_assets/styles/less/home.less, generator/_assets/styles/less/pages.less
See:
https://github.com/cfengine/website/pull/890
=> Added fallback fonts to reduce differences while red hat font is loading

api/enterprise-api-ref/export-import-api.markdown
=> Small typo in import API example

reference/enterprise-api-ref/export-import-api.markdown
Ticket: none
(cherry picked from commit 751f11dfc2113184121450ad9a29fc87068fa538)
=> Small typo in import API example (3.18)

api/enterprise-api-ref/export-import-api.markdown
Ticket: none
(cherry picked from commit 751f11dfc2113184121450ad9a29fc87068fa538)
=> Small typo in import API example (3.21)

reference/language-concepts/classes.markdown
- https://github.com/cfengine/core/pull/5357
- https://github.com/cfengine/masterfiles/pull/2750
=> ENT-9402: Added note about ignore_interfaces.rx preferred location change

reference/components/cf-agent.markdown
(cherry picked from commit 4575f29cf9989c4c71ad00f8e3fe33470895fccb)
=> Added documentation for --simulate

reference/masterfiles-policy-framework/modules-mustache.markdown
- https://github.com/cfengine/masterfiles/pull/2747
Ticket: ENT-10793
=> ENT-10793: Added documentation for modules/mustache

cheatsheet.markdown, examples/tutorials/writing-and-serving-policy/controlling-frequency.markdown, overview/directory-structure.markdown, reference/components/cf-agent.markdown
Ticket: ENT-10930
(cherry picked from commit f5c0dc6fad864f2b9d3e0d061acacb6bd5a3cf73)
=> ENT-10903: Added notes about lock purging (3.23)

cheatsheet.markdown, examples/tutorials/writing-and-serving-policy/controlling-frequency.markdown, overview/directory-structure.markdown, reference/components/cf-agent.markdown
Ticket: ENT-10930
(cherry picked from commit f5c0dc6fad864f2b9d3e0d061acacb6bd5a3cf73)
=> ENT-10903: Added notes about lock purging (3.21)

reference/promise-types.markdown
(cherry picked from commit 805d139f63defaf1b5167dcf8a0f0c8d624001af)
=> ENT-10903: Fixed list formatting (3.21)

reference/promise-types.markdown
(cherry picked from commit 805d139f63defaf1b5167dcf8a0f0c8d624001af)
=> ENT-10903: Fixed list formatting (3.18)

generator/_assets/styles/less/article.less
Ticket: ENT-9832
(cherry picked from commit 782101a7bb753bc1cb986b3f85c1153a7f5c2902)
=> ENT-9832: Long title text causes disposition of the gh button (3.21)

generator/_assets/styles/less/base.less
=> ENT-9833: navigation table margin fix

generator/_assets/styles/less/base.less
Ticket: ENT-9833
(cherry picked from commit 54077da28454373d4146f0ea5a19539a47cbaa77)
=> ENT-9833: navigation table margin fix (3.21)

generator/_assets/styles/less/menu.less
Ticket: ENT-9834
(cherry picked from commit 8a9ac842b0100f5871668ae1e9e7a58f5147ef2b)
=> ENT-9834: long text items jump to second line (3.21)

reference/functions/regex_replace.markdown
(cherry picked from commit 725080af8360b40b44f8e096a2f23f41df6eafe0)
=> Add 'g' and its meaning to the list of options for regex_replace() (3.21)

reference/functions/regex_replace.markdown
(cherry picked from commit 725080af8360b40b44f8e096a2f23f41df6eafe0)
=> Add 'g' and its meaning to the list of options for regex_replace() (3.18)

generator/_assets/js/custom.js
=> ENT-10971: copying link didn't update the url

generator/_assets/js/custom.js
Ticket: ENT-10971
(cherry picked from commit f2dc3a4d0ae0be6021d562f6b42766553550a191)
=> ENT-10971: copying link didn't update the url (3.21)

getting-started/developing-modules.markdown, getting-started/installation/general-installation.markdown, getting-started/installation/general-installation/installation-coreos.markdown, getting-started/installation/general-installation/installation-enterprise-free-aws-rhel.markdown, getting-started/installation/general-installation/installation-enterprise-free.markdown, getting-started/installation/general-installation/installation-enterprise-generic-tarball.markdown, getting-started/installation/general-installation/installation-enterprise-vagrant.markdown, getting-started/installation/general-installation/installation-enterprise.markdown, getting-started/installation/local-virtual-machine.markdown, getting-started/installation/pre-installation-checklist/verify-signatures.markdown, getting-started/installation/pre-installation-checklist/vi-quick-start-guide.markdown, getting-started/installation/version-control.markdown, getting-started/modules-from-cfengine-build.markdown, getting-started/writing-policy.markdown
=> ENT-10971: new file and command component usage across markdown in getting started section

generator/_assets/js/custom.js
=> fix: version select dropdown

generator/build/main.sh, generator/build/search/createIndex.js, generator/package-lock.json, generator/package.json, generator/webpack.config.js
Signed-off-by: Ihor Aleksandrychiev <ihor.aleksandrychiev@northern.tech>
(cherry picked from commit 5d54b8cb7ebf8b70a701888c982cdda37b1aaf28)
=> Moved build commands from main.sh to npm scripts (3.21)

generator/_assets/js/custom.js
Ticket: -
(cherry picked from commit 67354b032565a28c4bfe094c43aecdf325c22991)
=> fix: version select dropdown (3.21)

getting-started/developing-modules.markdown, getting-started/installation/general-installation.markdown, getting-started/installation/general-installation/installation-coreos.markdown, getting-started/installation/general-installation/installation-enterprise-free-aws-rhel.markdown, getting-started/installation/general-installation/installation-enterprise-free.markdown, getting-started/installation/general-installation/installation-enterprise-generic-tarball.markdown, getting-started/installation/general-installation/installation-enterprise-vagrant.markdown, getting-started/installation/general-installation/installation-enterprise.markdown, getting-started/installation/local-virtual-machine.markdown, getting-started/installation/pre-installation-checklist/verify-signatures.markdown, getting-started/installation/pre-installation-checklist/vi-quick-start-guide.markdown, getting-started/installation/version-control.markdown, getting-started/modules-from-cfengine-build.markdown, getting-started/writing-policy.markdown
Ticket: ENT-10940
(cherry picked from commit f1df9517b943145002960b0538159678d08dfa36)
=> ENT-10971: new file and command component usage across markdown files (3.21)

generator/_scripts/_run_jekyll.sh
=> Do not process the `published: false` documents

generator/_scripts/_run_jekyll.sh
Ticket: ENT-10284
Signed-off-by: Ihor Aleksandrychiev <ihor.aleksandrychiev@northern.tech>
(cherry picked from commit 915ccd45a5034bd1b646153dc9aff839497d0482)
=> Do not process the `published: false` documents (3.21)

release-notes/supported-platforms.markdown
=> ENT-10347: Added Debian 12 to supported platforms

guide/latest-release/supported-platforms.markdown
=> Added el9 to supported platforms for Hosts (3.18)

guide/latest-release/supported-platforms.markdown
=> ENT-8813: Added Debian 11 arm64 to supported platforms both hub and agent (3.18)

generator/_config.yml
=> ENT-11068: Updated current version (3.21)

generator/_config.yml
=> ENT-11019: Updated current version (3.18)

overview/glossary.markdown, reference/language-concepts/augments.markdown
=> ENT-11196: Fixed cases where `data` linked when verbatium was desired

overview/glossary.markdown, reference/language-concepts/augments.markdown
Ticket: ENT-11196
(cherry picked from commit 68734630ebd0651d249dae44c52fd3fe62442d78)
=> ENT-11196: Fixed cases where `data` linked when verbatium was desired (3.21)

reference/language-concepts/augments.markdown
Ticket: ENT-11196
(cherry picked from commit 68734630ebd0651d249dae44c52fd3fe62442d78)
=> ENT-11196: Fixed cases where `data` linked when verbatium was desired (3.18)

generator/_includes/footer.html
Was working before due to redirect. Might as well go directly.
=> Updated legal link in footer

generator/_assets/js/custom.js, generator/_assets/styles/less/pages.less
Ticket: ENT-11202
(cherry picked from commit 32993a9cdd62b447c06f10695bf2b97fbc060761)
=> ENT-11202: TOC scrolls with view (3.21)

generator/_assets/js/custom.js
Ticket: ENT-11202 ENT-11335 ENT-11305
(cherry picked from commit 4263f15d47ea6b2bbe4235a686f010e922efb4df)
=> fix: TOC bug-fixes (3.21)

cheatsheet.markdown, generator/_scripts/cfdoc_linkresolver.py
- Fixed anchor generation when ' - ' is found
- Added cheatsheet information about link special characters handling
=> Fixed anchor generation when ' - ' is found (3.21)

reference/functions/findfiles.markdown, reference/functions/findfiles_up.markdown
- Updated docs with new features and bug fixes on findfiles()
- Updated docs with new features and bug fixes on findfiles_up()
- Fixed typo in docs on findfiles_up()
- Fixed white space in docs on findfiles()
=> Update docs with new glob features and bug fixes

generator/_assets/styles/less/article.less
=> ENT-11294: h4, h5 font-size decreased

generator/_assets/styles/less/base.less
=> ENT-11294: long word line break in code elements

generator/_assets/styles/less/base.less
Ticket: ENT-11412
(cherry picked from commit ad1d4c5bd6da4e280f0c7024f0ee8f44d7170f25)
=> ENT-11412: long word line break in code elements (3.21)

release-notes/supported-platforms.markdown
=> ENT-11458: Fixed terminology for Hub and Clients on supported platforms page

release-notes/supported-platforms.markdown
Ticket: ENT-11458
(cherry picked from commit fda4ea5ab417d94f98192cc149271dc5a25a534d)
=> ENT-11458: Fixed terminology for Hub and Clients on supported platforms page (3.21)

guide/latest-release/supported-platforms.markdown
Ticket: ENT-11458
(cherry picked from commit fda4ea5ab417d94f98192cc149271dc5a25a534d)
=> ENT-11458: Fixed terminology for Hub and Clients on supported platforms page (3.18)

generator/_assets/styles/less/article.less, generator/_assets/styles/less/base.less
=> ENT-11429: Adjust margins for headers in articles

generator/_assets/styles/less/article.less, generator/_assets/styles/less/base.less
Ticket: ENT-11429
(cherry picked from commit 0472b68d5dc5c016182a301c7ac359ffda868ab0)
=> ENT-11429: adjust margins for headers in articles (3.21)

examples/tutorials/installing-cfengine-enterprise-agent.markdown, reference/language-concepts/augments.markdown, reference/language-concepts/namespaces.markdown, reference/macros.markdown, reference/promise-types/files.markdown
* Ensure unordered lists are rendered
* Do not link to cfengine homepage for cfengine class/file template_method
=> Fix some format issues

reference/language-concepts/augments.markdown
(cherry picked from commit 3e985b749190860a1f52ab609276dc3a45bef1b9)
=> Fix unordered lists format (3.18)

reference/language-concepts/augments.markdown
(cherry picked from commit 3e985b749190860a1f52ab609276dc3a45bef1b9)
=> Fix unordered lists format (3.21)

generator/_scripts/cfdoc_linkresolver.py
Ticket: ENT-11806
- https://github.com/cfengine/masterfiles/pull/2888
=> ENT-11806: Striped double dashes resulting from stripping other characters

generator/_assets/js/custom.js
=> ENT-11373: navigation tree collapse issue

generator/_assets/js/custom.js
Ticket: ENT-11373
(cherry picked from commit 92068ae3aeed83acb9f4de5263f066a53ff4d82a)
=> ENT-11373: navigation tree collapse issue (3.21)

generator/_references.md, reference/language-concepts/augments.markdown, reference/promise-types/files.markdown
(cherry picked from commit d72f71348147d4533995f64119cae3af986a3597)
=> Stopped autolinking "cfengine" to cfengine.com (3.21)

getting-started/installation/upgrading.markdown
=> ENT-11836: Added note about free space required for hub upgrade

getting-started/installation/upgrading.markdown
Ticket: ENT-11836
(cherry picked from commit 1802f9d0461f8f43cd99a79a03c39161b65117db)
=> ENT-11836: Added note about free space required for hub upgrade (3.21)

guide/installation-and-configuration/upgrading.markdown
Ticket: ENT-11836
(cherry picked from commit 1802f9d0461f8f43cd99a79a03c39161b65117db)
=> ENT-11836: Added note about free space required for hub upgrade (3.18)

getting-started/developing-modules.markdown
Ticket: ENT-11810
(cherry picked from commit 93c977123be8768ea57f7ef369f3e701e2b1f1c7)
=> ENT-11810: Fixed link target for custom promise type docs (3.21)

generator/_config.yml
=> ENT-11619: Updated versions for 3.18.8 release (3.18)

generator/_config.yml
=> ENT-11670: Updated versions for 3.21.5 release (3.21)

reference/components/cf-serverd.markdown
=> CFE-4413: Added documentation for log level influencing signals for cf-serverd

reference/components/cf-serverd.markdown
=> CFE-4413: Added documentation for log level influencing signals for cf-serverd (3.21)

generator/_config.yml
=> ENT-11721: Fixed version for doc generator (3.24)

reference/promise-types/files/edit_line/field_edits.markdown
=> CFE-4424: Clarified that sub-separator is value_separator (3.18)

reference/promise-types/files/edit_line/field_edits.markdown
=> CFE-4424: Clarified that sub-separator is value_separator (3.21)

reference/promise-types/files/edit_line/field_edits.markdown
=> CFE-4424: Clarified that sub-separator is value_separator (3.24)

reference/promise-types/files/edit_line/field_edits.markdown
=> CFE-4424: Clarified that sub-separator is value_separator

examples/example-snippets/user-management.markdown, examples/tutorials/write-cfengine-policy.markdown, examples/tutorials/writing-and-serving-policy.markdown, reference/components/cf-agent.markdown, reference/language-concepts/normal-ordering.markdown, reference/masterfiles-policy-framework.markdown, reference/promise-types/commands.markdown
Fix some lists, headings and typos.
=> Fix formatting

getting-started/installation/upgrading.markdown
=> ENT-12087: Added note to upgrade docs that BACKUP_DIR should be removable

getting-started/installation/upgrading.markdown
=> ENT-12087: Added note to upgrade docs that BACKUP_DIR should be removable (3.21)

reference/promise-types/files.markdown
=> ENT-12118: Clarified that ./ is not specific to explicit create attribute

reference/promise-types/files.markdown
=> ENT-12118: Clarified that ./ is not specific to explicit create attribute (3.24)

reference/promise-types/files.markdown
=> ENT-12118: Clarified that ./ is not specific to explicit create attribute (3.21)

api/enterprise-api-ref/two-factor-authentication.markdown, api/enterprise-api-ref/users-rbac.markdown
Ticket: ENT-10838
Signed-off-by: Ihor Aleksandrychiev <ihor.aleksandrychiev@northern.tech>
(cherry picked from commit 9d9dc5f077fc3aebd9a544e0b271d171bcfdb01b)
=> Added Two-factor authentication API documentation (3.24)

getting-started/developing-modules.markdown
This comes in handy when you are working on a PR in a branch such as for cfengine/modules
=> Mention that you can add a module by repo AND commit

generator/_layouts/default.html, generator/_layouts/index.html, resources/external-resources.markdown
=> ENT-12106: Changed links from libera.chat to Matrix (3.24)

generator/_layouts/default.html, generator/_layouts/index.html, resources/external-resources.markdown
=> ENT-12106: Changed links from libera.chat to Matrix (3.21)

api/enterprise-api-ref/audit-logs-api.markdown
=> ENT-11977: Updated Audit log API documentation

redirects.conf
=> ENT-12339: Updated redirects for /latest/ to point to 3.25.0

overview/directory-structure.markdown
=> ENT-12569: Added documentation about promise_execution.log, variable.cache.tmp, and context.cache.tmp state files

overview/directory-structure.markdown
=> ENT-12569: Added documentation about promise_execution.log, variable.cache.tmp, and context.cache.tmp state files (3.24)

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
(cherry picked from commit b4e8c771ded872f148aea3908089dd96e824c463)
=> functions: Fix formatting for package*matching (3.24)

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
(cherry picked from commit b4e8c771ded872f148aea3908089dd96e824c463)
=> functions: Fix formatting for package*matching (3.21)

overview/directory-structure.markdown
=> ENT-11839: Added more documentation references for ignore_interfaces.rx

overview/directory-structure.markdown
=> ENT-11839: Added more documentation references for ignore_interfaces.rx (3.24)

reference/functions/getbundlemetatags.markdown
https://github.com/cfengine/core/pull/5703
https://github.com/cfengine/documentation/pull/3402
=> Added getbundlemetatags policy function

getting-started/installation/general-installation/installation-community.markdown, reference/components/cf-monitord.markdown, reference/functions/accumulated.markdown, reference/functions/ago.markdown, reference/functions/canonifyuniquely.markdown, reference/functions/data_expand.markdown, reference/functions/dirname.markdown, reference/functions/execresult.markdown, reference/functions/findfiles.markdown, reference/functions/findfiles_up.markdown, reference/functions/getclassmetatags.markdown, reference/functions/getenv.markdown, reference/functions/grep.markdown, reference/functions/is_type.markdown, reference/functions/lsdir.markdown, reference/functions/maplist.markdown, reference/functions/strftime.markdown, reference/functions/sum.markdown, reference/functions/type.markdown, reference/functions/variance.markdown, reference/promise-types/access.markdown, reference/special-variables.markdown
* Remove some trailing garbage
* Add and update some formatting
* Fix title for is_type()
=> Fix some minor issues

reference/special-variables/sys.markdown
=> Add docs for sys.cpusockets

reference/macros.markdown
=> CFE-3371: Add pam to feature macro

reference/functions/isconnectable.markdown
https://github.com/cfengine/core/pull/5721
https://github.com/cfengine/documentation/pull/3407
=> Added documentation for isconnectable function

reference/functions/hostswithclass.markdown, reference/functions/hostswithgroup.markdown
https://github.com/cfengine/enterprise/pull/834
https://github.com/cfengine/core/pull/5741
https://github.com/cfengine/nova/pull/2403
https://github.com/cfengine/documentation/pull/3416
=> ENT-11325: Added documentation for hostswithgroup() policy function

reference/functions/findlocalusers.markdown
https://github.com/cfengine/core/pull/5714
https://github.com/cfengine/documentation/pull/3406
=> Added documentation for findlocalusers() policy function

api/enterprise-api-ref/first-time-setup.markdown, api/enterprise-api-ref/sql-schema/cfsettings.markdown
together: https://github.com/cfengine/nova/pull/2402
=> ENT-12185: Added the First time setup API documentation

reference/language-concepts/classes.markdown
=> Added note about cfengine hard classes for versions

generator/_config.yml
=> ENT-12901: Updated documentation metadata for 3.26.0 (3.26)

redirects.conf
=> Updated docs.cfengine.com/latest/ to point to 3.6

reference/functions/useringroup.markdown
=> ENT-12721: Added documentation for useringroup()

reference/functions/useringroup.markdown
=> ENT-12721: Added documentation for useringroup() (3.26)

generator/_scripts/cfdoc_references_resolver.py
=> CFE-4566: Fixed ssue in `cfdoc_references_resolver.py` where functions were processed twice

Jenkinsfile
=> Forgot to change the temporary location of create-revisions-file.sh, now fixed.
