cfengine/documentation

reference/special-variables/sys.markdown
harware -> hardware
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Fix typo in documentation

examples/enterprise-api-examples/browsing-host-information.markdown
The host id includes SHA= in the front. API commands need to include that as
well or the queries will give incorrect results.
=> Change: Fix api docs for host operations

reference/classes.markdown
This documents the provenance of am_policy_hub and policy_server. People
frequently ask how it is known, and how it gets set.
=> Change: Improve am_policy_hub description

reference/promise-types/files.markdown
This brings the description of the default comparison in line with what is
noted as the default value.
=> Change: Improve copy_from comparison documentation

reference/promise-types/files.markdown
Links using hard brackets are only used for known links. Must use parentheses
for adhoc links.
=> Fix: Link to issue

guide/language-concepts/normal-ordering.markdown
Because of lack of some new lines list was created wrongly on
normal ordering description page.
=> Fix list containing detailed evaluation steps.

reference/functions/eval.markdown
Document what's implemented in https://github.com/cfengine/core/pull/2149#issuecomment-88020076
=> reference/functions/eval.markdown: explain new "class" mode

reference/functions/file_hash.markdown, reference/functions/hash.markdown
Docs for the `file_hash()` function.  Require https://github.com/cfengine/core/pull/2189 for the example.  Should be backported to 3.6.
=> reference/functions/file_hash.markdown: add docs

reference/enterprise-api-ref/sql-schema.markdown
The VariablesLog table contains variables, not contexts.
=> Fix: Description of VariablesLog

enterprise-cfengine-guide/best-practices.markdown
You need to run the git config commands as cfapache; and the git
config commands to set user.email and user.name should be passed the
--global flag.
=> Fix broken instructions on how to set up git config.

guide/faq.markdown, guide/latest-release/policy-framework-updates.markdown, guide/writing-and-serving-policy/policy-framework.markdown
Sections with () in the title are problematic to link to, try without
().
=> Fix: Links to sections

enterprise-cfengine-guide/high-availability/installation-guide.markdown
This reflects changes made in 3.7 and latest recommendations from RHEL.
It also obsoletes crmsh which is not used by default by RHEL and uses
pcs for cluster configuration and management instead.
=> Improved and fixed documentation for HA.

reference/functions/packagesmatching.markdown
Now using example from core repository instead of inline text.
Ref: https://dev.cfengine.com/issues/7380
=> Fix: packagesmatching() example

reference/functions/packagesmatching.markdown
Now using example from core repository instead of inline text.
=> Backport Fix: packagesmatching() example

reference/promise-types/vars.markdown
Constant variables have not worked in quite some time. Implementation fix was
attempted multiple times without success. It was decided to fix the
documentation.
Ref: https://dev.cfengine.com/issues/1492
This should go into 3.6, and 3.7
=> Fix: Documenation about constant variables

guide/faq.markdown, guide/latest-release/known-issues.markdown
This is more appropriate for the FAQ as it works as intended within the
design limitations.
=> Change: Move information about cf-promsies --show classes to faq

guide/faq.markdown, guide/latest-release.markdown, guide/latest-release/known-issues.markdown, guide/latest-release/policy-framework-updates.markdown
Fix: Remove outdated references to 3.6
(cherry picked from commit 11932eab604064ec77b53c05e3ce6bce0fdbce76)
Change: Move information about cf-promsies --show classes to faq
This is more appropriate for the FAQ as it works as intended within the
design limitations.
(cherry picked from commit b9b01ad6849034a596330982feca7365f10839a9)
Change: Documentation updates for 3.7
Update known issues Update policy framework updates
(cherry picked from commit 3dd83a5e5f0b116ba4c8756c8418a469e8f84dcd)
=> Update documentation for policy framework changes in 3.7

guide/installation-and-configuration/version-control.markdown
Using lowercase upstream is a bit confusing. Instead we show using
masterfiles from our own masterfiles repository.
ref: https://dev.cfengine.com/issues/7449
=> Change: Improve example source for masterfiles policy

reference/components/file_control_promises.markdown
Explain how namespaces apply until the next namespace definition or
until the end of the file, similar to how class expression work.
=> Change: Improve namespace description

reference/promise-types/commands.markdown
(cherry picked from commit e76ef11bbaa294a66c411059a6c594de5382a8bb)
Conflicts:
reference/promise-types/commands.markdown
=> Add: Documentation about cfengine-die

reference/components.markdown
Also added details about individual options.
(cherry picked from commit 227a71bc61fca921e34fc8c906aa245c96255cb1)
=> Fix: Default value for protocol version

reference/promise-types.markdown
- Use the CFEngine_include_example macro so that users can easily
download the example from github.
- Update the description for better clarity
- Ref: https://dev.cfengine.com/issues/5462
=> Change: Update depends_on description and example

reference/components.markdown, reference/components/cf-serverd.markdown, reference/promise-types/access.markdown, reference/promise-types/files.markdown
- protocol 2 causes noop for following attributes:
- ifencrypted
- logencryptedtransfers
- encrypt
- crosslink
- ifencryped
- logencruptedtransfers
- encrypt
- tls_ciphers
- tls_min_version
- allowciphers
- allowtlsversion
- protocol_version
=> Add: Crosslinking of encrypt related attributes

reference/components/cf-serverd.markdown
(cherry picked from commit 11a9422034dbbe818af83e8da2a0d75381469988)
=> Add: Note about logencryptedtransfers being noop with protocol_version 2

reference/promise-types/edit_line/insert_lines.markdown
(cherry picked from commit 23009dde35dda0b0287f4e14ebf466f24458c72d)
Conflicts:
reference/promise-types/edit_line/insert_lines.markdown
=> Add: Crossreference to bodies in the stdlib

reference/standard-library/package_modules.markdown
Update the doc to be consistent with actual cfengine behavior.
=> get-package-data passes File as input, not Name

reference/common-body-attributes-include.markdown, reference/promise-types.markdown
- inherit_from slipped in accidentally from 3.8
- The common body attribute section was missing
=> Fix: Common body attributes

guide/reporting/command-line-reports.markdown
(cherry picked from commit 57079f40bbebdc517f86c4103bd6fe8e58cbc939)
=> Backport typo fix

guide/reporting/command-line-reports.markdown
(cherry picked from commit 57079f40bbebdc517f86c4103bd6fe8e58cbc939)
=> Backport typo fix for log_string

guide/reporting/command-line-reports.markdown
(cherry picked from commit 57079f40bbebdc517f86c4103bd6fe8e58cbc939)
=> Backport log_string typo fix

reference/functions/variablesmatching.markdown
Ref: https://dev.cfengine.com/issues/7253
=> Fix: variablesmatching uses an  anchored regex

cheatsheet.markdown
Trying to solve:
18:45:24 Liquid Exception: Unknown tag 'CFE_manuals_version' in
cheatsheet.markdown
=> Remove markup that might be causing failure

cheatsheet.markdown
Trying to get rid of: 20:41:00 Liquid Exception: Unknown tag 'site' in
cheatsheet.markdown
=> Remove tag potentially causing build errors

reference/components/cf-serverd.markdown
This default value was changed for performance reasons.
=> Add: Historical default value for collect_window

index.markdown
Turn it into a variable thats defined from _config.yml in the
documentation-generator. This way we can have fewer things to change
during releases.
(cherry picked from commit fbb769bb3702c6c70f6a7cd9c6d2836e5bd916be)
Conflicts:
index.markdown
=> Change: Liquify reference to hard coded branch

reference/enterprise-api-ref/host.markdown
They were inverted, examples showed the correct usage.
=> Fix: host API context query parameters

examples/tutorials/nfs_and_containers.markdown, reference/functions/string_mustache.markdown
The tutorial/example showed some really ugly policy, and it also did not include any instructions to use it so it was unpublished, probably it should just be removed all together.
Another page was missing a closing tag.
=> Cleanup bad example and fixing tags

reference/functions/string_mustache.markdown
We must encapsulate in raw or mustache examples will not be rendered properly due to being interpreted by jekyll (part of our doc build system)
=> Fix: string_mustache doc rendering

reference/promise-types/files.markdown
Pending merge of cfengine/core#2194, this change adds documentation for the ability to create fifos through policy.
=> Add docs about file_type option added in cfengine/core#2194

examples/tutorials/nfs_and_containers.markdown
The policy used in this example is really bad, and the instructions to run it are also
missing so it's being unpublished.
(cherry picked from commit 437f1ea2ee29a80c64cd27e89c727dddfa3f64b7)
=> Remove: Bad example

reference/functions/data_readstringarray.markdown
Ref: https://dev.cfengine.com/issues/6478
(cherry picked from commit b9ded6442f73c092071d330e44dbd65177e43195)
=> Change: Clarify comment regex is multiline

reference/promise-types/reports.markdown
The [%CFEngine_promise_attribute()%] macro depends on being in an expected
location within the tree. The build is failing when using it after incluion of
the common body attribute stub.
=> Fix: Attempt to fix ability to use attribute macro

reference/functions/sort.markdown
Trying to use regex ends up badly
=> fix a typo in sort() attributes

reference/promise-types/packages.markdown
=> Make it clear that Python is required for new package modules.

reference/functions/and.markdown, reference/functions/not.markdown, reference/functions/or.markdown
(cherry picked from commit f9eeb5e17172867576790674266129f4f38f0962)
=> Change: Clarify potential return strings from and, not, and or functions

examples/example-snippets/active_directory.markdown, examples/example-snippets/file_permissions.markdown, examples/example-snippets/user-management.markdown
The ACL and Directory examples were not user management related so they
were moved to their own pages.
=> Change: Reorganize user management examples

reference/functions/data_expand.markdown, reference/functions/length.markdown, reference/functions/mapdata.markdown, reference/functions/mean.markdown, reference/functions/mergedata.markdown, reference/functions/parsejson.markdown, reference/functions/url_get.markdown, reference/functions/variance.markdown
As requested in https://github.com/cfengine/core/pull/2454
This is a snapshot of the current state, putting all the docs in `mergedata()`. But when https://dev.cfengine.com/issues/7871 is done, we'll add a new `Inline JSON` section to the vars documentation and move all this information there. We can't do it yet because not all functions have been converted.
=> Allow some functions to take inline JSON: mapdata, mergedata, and others

reference/promise-types/classes.markdown
Instead of saying 'host identity' explicitly list out the 3 properties that are use to create the hash select_class will use to pick a class.
=> Document the host properties used by select_class

examples/tutorials/nfs_and_containers.cf
I'm unsure if this PR is needed as I've never heard to CGEngine, but I'm also new to cfengine. I'm assuming this is  a typo as G is next to F and could be an easy mistake to make.
=> Fixed typo in example cf file

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
Also fixup many references to /var/cfengine, with $(sys.workdir).
=> Change: Reflow enterprise install guide

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
One of the commands showed $ instead of # which could confuse someone
that it is a non root console.
(cherry picked from commit f3eea31c3106af8ca1e5309b78e6a003e50117aa)
=> Change: Improve rendering & fix console example

reference/functions/hostswithclass.markdown
It's important to document the timescale for this function. In earlier
enterprise versions (2.x) this was based on any class that had been
defined within lastseenexpireafter.
=> Add: Note about time horizon for hostswithclass()

reference/functions.markdown
This begins to restore the work done by ted in commit
e2247d4efd8710f5528e4b7088b8d5a0b9142e5c which ended up breaking the doc
build.
=> Add: Collecting Functions description

reference/special-variables/def.markdown
def is special in that it can be defined by the augments file, or from
policy.
=> Add: def to special variables

guide/writing-and-serving-policy/policy-framework.markdown
A change to the MPF to not parse .cf files found in services/autorun
necessitates that the services_autorun class be defined from the very
beginning of agent execution.
=> Change: services_autorun should be defined by augments

reference/functions/peerleader.markdown, reference/functions/peerleaders.markdown, reference/functions/peers.markdown
(cherry picked from commit b558fc5764901eaef13acf3c864f310c82470f0b)
=> Change: Indicate multiline regex for peer functions

reference/functions/parsestringarrayidx.markdown
(cherry picked from commit 1259548972e6470645e86a97ca84f76b7a2760ad)
=> Change: Indicate parsestringarrayidx comment is a multiline regex

reference/functions/parseintrealstringarray.markdown
(cherry picked from commit ed95883d28794d13b5f3aaaa498d1a006d13f852)
=> Change: Indicate parse array function comment fields are multiline regex

reference/functions/network_connections.markdown
As implemented in https://github.com/cfengine/core/pull/2495
=> Document network_connections() function that parses /proc/net

guide/installation-and-configuration/upgrading.markdown
3.6 will be no longer compatible with 3.9 and higher.
Some typos fixed.
=> Add section in upgrading guide about lack of compatibility for 3.6.

enterprise-cfengine-guide/hub_administration.markdown, enterprise-cfengine-guide/hub_administration/adjusting-schedules.markdown, enterprise-cfengine-guide/hub_administration/custom-https-certificate.markdown, enterprise-cfengine-guide/hub_administration/enable-plain-http.markdown, enterprise-cfengine-guide/hub_administration/reset-admin-creds.markdown
Split hub administration tasks into individual pages.
Add instructions for enabling plain http for Mission Portal.
Add instructions for installing custom SSL Certificates.
=> Change: Hub administration docs orginization

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
My testing shows that this is indeed an anchored regular expression and
not an unanchored regular expression. Some discussion with Eystein
results in the conculsion that the implementation is correct, and the
documentation needs updating.
=> Fix: description of regular expression matching for packagesmatching functions

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
functions
My testing shows that this is indeed an anchored regular expression and not
an unanchored regular expression. Some discussion with Eystein results in
the conculsion that the implementation is correct, and the documentation
needs updating.
(cherry picked from commit d2285ae1d0ba48256964e5ba50379dfba1ec9fd6)
=> Fix: description of regular expression matching for packagesmatching

reference/promise-types/packages.markdown, reference/standard-library/package_modules.markdown
=> Fix incorrect syntax documentation for packages -> options.

reference/functions/eval.markdown, reference/functions/sort.markdown
(cherry picked from commit 310261ec2600bb264ce7f7aec1f50a650e93bd2e)
=> Change: Improve history for sort() and eval()

examples/example-snippets/promise-patterns/example_enable_service.markdown
(cherry picked from commit 3341b5433a6478517737d85d63d2bdf285c6bd6e)
=> Fix: Syntax error in markdown

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
(cherry picked from commit 268ff42bfee4b59ba5f8f28de6929073d1784230)
=> Fix typo in Enterprise Installation Guide. (Too many m's in "recommmended")

guide/introduction/directory-structure.markdown
cf-consumer is still missing a man page and page under the components
section.
=> Add: Description of cf-hub and cf-consumer

reference/promise-types.markdown
According to ChangeLog in core, if/unless were introduced in 3.7.0,
not in 3.6.1:  https://github.com/cfengine/core/blob/master/ChangeLog#L759-L760
=> Fix history on if/unless in ifvarclass section

reference/functions/variablesmatching.markdown, reference/functions/variablesmatching_as_data.markdown
Added in https://github.com/cfengine/core/pull/2471
Requires https://github.com/cfengine/core/pull/2708
=> Redmine#7885: add documentation and links for variablesmatching_as_data

reference/functions.markdown, reference/functions/maparray.markdown, reference/functions/mapdata.markdown, reference/functions/maplist.markdown
For https://github.com/cfengine/core/pull/2683#event-814928613
=> ARCHIVE-1619: allow maplist(), maparray(), and mapdata() to evaluate function calls during iteration

reference/functions/getclassmetatags.markdown, reference/functions/getvariablemetatags.markdown
@nickanderson docs for https://github.com/cfengine/core/pull/2647
=> Allow getvariablemetatags() and getclassmetatags() to get a specific tag key

guide/installation-and-configuration/upgrading.markdown
The version split libraries were re-consolidated in 3.8.
=> Change: Fix path in upgrade docs

examples/example-snippets/all_hosts_the_same.cf, examples/example-snippets/promise-patterns/example_updating_from_central_hub.markdown, examples/example-snippets/updating_from_a_central_hub.cf, examples/example-snippets/variation_in_hosts.cf, reference/components/cf-serverd.markdown
* be clear on supported syntax
* remove hostnames from examples as they are not supported
* modify examples to use CIDR notation for subnets
=> zendesk#3295: allowconnects, allowallconnects, trustkeysfrom

reference/enterprise-api-ref/query.markdown
HostContext filters take array not string.
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
=> Fix missleading documentation about Query API parameters.

reference/functions/data_sysctlvalues.markdown, reference/functions/sysctlvalue.markdown
@kacf as requested in https://github.com/cfengine/core/pull/2743
=> CFE-2513: New sysctlvalue() and data_sysctlvalues() functions from /proc/sys

reference/functions/readcsv.markdown, reference/functions/readdata.markdown, reference/functions/readenvfile.markdown, reference/functions/readfile.markdown, reference/functions/readjson.markdown, reference/functions/readyaml.markdown
Example does not work yet, see: https://tracker.mender.io/browse/CFE-2656
=> Added documentation for readenvfile() (CFE-2650)

guide/latest-release/known-issues.markdown
=> Redact known issue for editing directory users with dots in username

reference/promise-types/commands.markdown
(cherry picked from commit cb8c1564ec6b61bfb561e3be4159440d950de50a)
=> CFE-2725: Note that modules can only define classes and vars in the default namespace

reference/components/cf-agent.markdown
(cherry picked from commit 179568fabbb73e47fe30c248ab3028d0dd49a637)
=> The timeout parameter is actually a connection + read timeout

reference/enterprise-api-ref/sql-schema.markdown
This is minor, but it is wrong and confusing to use frequency about a length of time. (This is from a support case).
@nickanderson Please review.
=> Don't use frequency about a time interval

examples/enterprise-api-examples/managing-users-and-roles.markdown
The data previously contained a trailing comma which will not work
because it is invalid JSON.
(cherry picked from commit e2be23c7ac22233f410aa3bf06a5f683c6b79938)
=> Fix invalid data in api example

reference/functions/parseintarray.markdown, reference/functions/parserealarray.markdown, reference/functions/parsestringarray.markdown, reference/functions/readintarray.markdown, reference/functions/readrealarray.markdown, reference/functions/readstringarray.markdown
This is inteneded to make it easier to find the functions in the
reference manual.
=> Seperate parse*array and read*array into seperate documents

reference/functions/classesmatching.markdown
(cherry picked from commit d81ab6996dccf9d6f98c6b56d0505089ef7dbaf2)
=> CFE-2743: Classesmatching uses anchored regular expressions

examples/example-snippets/packages_examples_solaris.cf, examples/example-snippets/software-adminstration.markdown
They were yum examples accidentally.
(cherry picked from commit bdccfe90d5b7fdb67b52b2b0e0580973e7d389af)
=> Fix solairs packages example snippets

guide/installation-and-configuration/upgrading.markdown
(cherry picked from commit 17ab0b9011afcd6a5da0e090eb84c3bae496a94c)
=> ENT-3592: Added instructions to upgrade procedure for undefining trigger_upgrade

reference/components/cf-agent.markdown
This was removed in 3.6.0, but the documentation was never updated.
=> CFE-2722: Document removal of body agent control syslog

reference/components/cf-agent.markdown
This was removed in 3.6.0, but the documentation was never updated.
(cherry picked from commit bfcd07e8b0cb26a1135598c419368ed87c93222f)
=> CFE-2772: Document removal of body agent control syslog

reference/functions/mapdata.markdown
The result of mapdata() is not deterministic. So the example
needs to use a trick to show some deterministic example data
instead.
=> Adapt to the changes in the mapdata() example

reference/functions/filesexist.markdown
Implemented in cfengine/core#3033
(cherry picked from commit 39c16e66174bb06de1910030eeb1c9afa437d812)
=> CFE-2744: filesexist() is now one of the collecting functions

reference/functions/fileexists.markdown, reference/functions/filestat.markdown, reference/functions/isdir.markdown, reference/functions/islink.markdown, reference/functions/isplain.markdown, reference/functions/returnszero.markdown
The fileexists() function tells you if a file exists, if it is checking
a broken symlink, that broken symlink exists and therefore the function
returns true.
Checking if a symlink is broken or if it resolves to a specific target
can be accomplished using filestat() combined with fileexists or by
calling out to test binary with returnszero().
=> CFE-1120: Improve docs related to detecting if files are symlinks

reference/functions/fileexists.markdown, reference/functions/filestat.markdown, reference/functions/isdir.markdown, reference/functions/islink.markdown, reference/functions/isplain.markdown, reference/functions/returnszero.markdown
The fileexists() function tells you if a file exists, if it is checking
a broken symlink, that broken symlink exists and therefore the function
returns true.
Checking if a symlink is broken or if it resolves to a specific target
can be accomplished using filestat() combined with fileexists or by
calling out to test binary with returnszero().
(cherry picked from commit e0ddd80313f12c5decda6444d7d9b3a94b63f305)
=> CFE-1120 Backport improved docs related to detecting if files are symlinks

reference/functions/fileexists.markdown, reference/functions/filestat.markdown, reference/functions/isdir.markdown, reference/functions/islink.markdown, reference/functions/isplain.markdown, reference/functions/returnszero.markdown
The fileexists() function tells you if a file exists, if it is checking
a broken symlink, that broken symlink exists and therefore the function
returns true.
Checking if a symlink is broken or if it resolves to a specific target
can be accomplished using filestat() combined with fileexists or by
calling out to test binary with returnszero().
(cherry picked from commit e0ddd80313f12c5decda6444d7d9b3a94b63f305)
=> CFE-1120: Backport improved docs related to detecting if files are symlinks

guide/installation-and-configuration/secure-bootstrap.markdown
Refresh the guide to include the new --trust-key option.
=> ENT-3695 Refresh secure bootstrap guide

reference/promise-types/databases.markdown
(cherry picked from commit bc5ffb1bf7f5a0d29c858b1e24d609f486bce26b)
=> explain that commas may be escaped for column values in database_rows constraint

guide/faq/unable-to-log-in-mission-portal.markdown
ENT-3908 Document how to align oauth tokens for MP access
If oauth tokens are not aliged you will be unable to log into mission
portal. This documents how to check and fix alignment.
(cherry picked from commit 5d9876f2c4c76a1c8ed186751d0b7a57a947ef4c)
=> Troubleshooting inability to log in to mission portal

guide/faq/unable-to-log-in-mission-portal.markdown
Page titles have heading level 1 by default, so the headings inside the page
should be level 2 or greater.
=> Fix heading level

guide/faq/unable-to-log-in-mission-portal.markdown
If oauth tokens are not aliged you will be unable to log into mission
portal. This documents how to check and fix alignment.
(cherry picked from commit 5d9876f2c4c76a1c8ed186751d0b7a57a947ef4c)
=> ENT-3908 Document how to align oauth tokens for MP access

guide/latest-release/supported-platforms.markdown
We will continue to try to have it work, but we cannot guarantee that these olde
releases are possible to support for the next full three years.
Changelog: AIX 5.3 and Solaris 9 are not supported platforms as of 3.12.0
=> ENT-3923 Remove AIX 5.3 and Solaris 9 from list of supported platforms

reference/promise-types/packages.markdown
This shows users how to specify enable and disable at the same time. Particularly the quoting is important to show.
=> CFE-2837 Improve yum package module options example

guide/latest-release/supported-platforms.markdown
Support for the following platform versions was removed because they have not been supported by their vendor for at least one year.
- AIX 5.3, 6 (PowerPC)
- CentOS/RHEL 4 (x86-64, x86)
- HP-UX 11.23 (Itanium)
- SLES 10 (x86-64, x86)
- Solaris 9 (UltraSparc)
- Ubuntu 10.04, 12.04 (x86-64, x86)
=> ENT-3945 Update supported platforms for 3.12.x

reference/functions/regex_replace.markdown
The documentation previously claimed that the trivial option `T'
disabled searching for regex patterns, only searching for exact
strings. What it is supposed to do, as per what PCRE defines, is
remove backreferences and special characters in the replacement
string.
Ticket: CFE-2850
=> CFE-2850: Fixed wrong explanation of trivial option in regex_replace

reference/promise-types/access.markdown, reference/promise-types/commands.markdown, reference/promise-types/databases.markdown, reference/promise-types/edit_line.markdown, reference/promise-types/edit_line/delete_lines.markdown, reference/promise-types/edit_line/field_edits.markdown, reference/promise-types/edit_line/insert_lines.markdown, reference/promise-types/edit_line/replace_patterns.markdown, reference/promise-types/files.markdown, reference/promise-types/guest_environments.markdown, reference/promise-types/measurements.markdown, reference/promise-types/packages-deprecated.markdown, reference/promise-types/packages.markdown, reference/promise-types/processes.markdown, reference/promise-types/reports.markdown, reference/promise-types/services.markdown, reference/promise-types/storage.markdown, reference/promise-types/users.markdown
The thought is that this will greatly improve readability for promise body attributes.
=> Swap common-body-attributes-include with See also xref

reference/promise-types/files.markdown
While the example is technically correct, using the body name from the stdlib will encourage use of existing bodies instead of duplicating them as someone trying to copy/paste will receive a duplicate definition of body error.
=> CFE-2915 Align example in docs with bodies that exist in the stdlib

examples/enterprise-api-examples/managing-settings.markdown
Patch is more usable since you do not have to provide the complete settings. For
one-liner commands and examples using PATCH should be much better.
=> ENT-4165 Use PATCH method in settings API example

reference/promise-types/commands.markdown
Module protocol extensions (lines that start with ^) apply until the end of the module execution unless they are explicitly set to something else.
=> CFE-2928 Clarify behavior of module protocol extensions

reference/functions/getindices.markdown
As indicated in CFE-1893 and core commit f235637ccfa756d91f042f5254f44631a8840389, the function will always return a list.
=> CFE-2929 Note that getindices() always returns a list

reference/language-concepts/augments.markdown
cfengine/core@5214d9347 changed the order in which things are
evaluated so now even the `am_policy_hub` and `policy_server`
hard classes can be used in augments.
Ticket: CFE-2941
=> Remove an old exception in hard classes usable in augments

reference/language-concepts/augments.markdown
cfengine/core@5214d9347 changed the order in which things are
evaluated so now even the `am_policy_hub` and `policy_server`
hard classes can be used in augments.
Ticket: CFE-2941
(cherry picked from commit d3d1a1534c600f00fd6498b4ecbcc755fa7aa04f)
=> [3.12.x] Remove an old exception in hard classes usable in augments

reference/components/cf-execd.markdown, reference/components/cf-serverd.markdown
This behavior was added in 3.7.0 as part of CFE-1698
=> CFE-2853 Note that cf-execd and cf-serverd respond to SIGHUP

reference/components/cf-execd.markdown, reference/components/cf-serverd.markdown
This behavior was added in 3.7.0 as part of CFE-1698
(cherry picked from commit a9482bd34e12c1b15c0da04f43c9094786b3a0ea)
=> CFE-2853 Note that cf-execd and cf-serverd respond to SIGHUP 3.10.x

reference/components/cf-execd.markdown, reference/components/cf-serverd.markdown
This behavior was added in 3.7.0 as part of CFE-1698
(cherry picked from commit a9482bd34e12c1b15c0da04f43c9094786b3a0ea)
=> CFE-2853 Note that cf-execd and cf-serverd respond to SIGHUP 3.7.x

reference/functions/bundlesmatching.markdown
=> Fix note about regular expression for bundlesmatching being unanchored

reference/components/cf-agent.markdown, reference/language-concepts/normal-ordering.markdown, reference/masterfiles-policy-framework/lib-files.markdown, reference/promise-types/files.markdown, reference/promise-types/files/edit_line.markdown, reference/promise-types/files/edit_line/delete_lines.markdown, reference/promise-types/files/edit_line/field_edits.markdown, reference/promise-types/files/edit_line/insert_lines.markdown, reference/promise-types/files/edit_line/replace_patterns.markdown
This change renames the bundle edit_line page to edit_line as well as associated
references. It brings the page in line with other page titles.
=> Replace bundle edit_line with edit_line

reference/components/cf-agent.markdown
The anchors used happen to be pointing to an included markdown snippet, maybe
it's too much inception, lets try the pages without the link targets.
=> Remove link anchors, possibly breaking build

reference/promise-types/files/edit_line/select_region-include.markdown
I have used this before, when the prep section doesn't render inside the pre
section as expected.
=> Fix rendering of prep section

reference/promise-types.markdown
This attribute was removed for 3.6.0 as part of a massive cleanup. Related
attributes that were removed at the same time include value_kept, value_notkept,
and value_repaired.
They were intended to allow the encoding of business value into the policy, but
were removed to improve maintainability, and because at the time, there was a
low level of utilization, finally, similar data can be tracked in other metadata
like meta tags, comments, and promisees/stakeholders.
(cherry picked from commit 40268b3b42ee9fcdad9021133dbfd43431741411)
=> Fix documentation for audit in action bodies

reference/functions/classesmatching.markdown, reference/functions/classmatch.markdown, reference/functions/countclassesmatching.markdown, reference/language-concepts/augments.markdown
Especially with regard to defining classes based on classes not being defined
yet using negative lookahead.
=> CFE-2954 Clarify how classes are defined from augments

guide/installation-and-configuration/general-installation/installation-enterprise.markdown
The minimum recommended amount of memory for a customized PostgreSQL
configuration is 3 GB, below 2GB we warn about not being able to use large
buffers and the default PostgreSQL configuration is used.
(cherry picked from commit 108c5b45b1d4b855189b5da438d7a1f5fd51abd2)
=> ENT-4343 Clarify documentation for minimum hub memory 3.7

reference/special-variables/sys.markdown
sys.fqhost links to sys.uqhost, but the link is broken. Probably because it
falls later on the same page and it isn't properly resolved. We have had to do
similar for sys.policy_entry_dirname and sys.policy_entry_filename in the past.
This change alters the link target to use a reference from _references.md in the
documentation-generator repository.
(cherry picked from commit 80e98004d5628f42759d98a16dd9a77aff622168)
=> CFE-2965 Fix link to sys.uqhost on same page

reference/enterprise-api-ref/inventory.markdown
(cherry picked from commit 07fed6e0d7088980756d1ed1a24cb874862f3ee2)
https://github.com/cfengine/nova/pull/1349
https://github.com/cfengine/mission-portal/pull/752
=> ENT-4371: Allow inventory API to use multiple values for one filter (3.12)

reference/promise-types/commands.markdown
Since forward slash will be added in
https://github.com/cfengine/core/pull/3472, I have altered the
documentation entry to no longer point to CFE-2478, and added
that forward slash is allowed.
Ticket: CFE-2478
Blocked by cfengine/core#3472
=> CFE-2478: Fixed documentation entry for `module`

reference/components/cf-runagent.markdown, reference/components/cf-serverd.markdown, reference/promise-types/access.markdown
When your looking at one of these things, you might need to know about
the other.
=> CFE-2995 Crossreferences for cf-runagent, resource_type, and cfruncommand

reference/promise-types/commands.markdown
Since forward slash will be added in
https://github.com/cfengine/core/pull/3472, I have altered the
documentation entry to no longer point to CFE-2478, and added
that forward slash is allowed.
Ticket: CFE-2478
(cherry picked from commit c72c38eb6b4ed0c4aff742968d3e3cee73c125ee)
=> CFE-2478: Fixed documentation entry for `module` 3.12

reference/promise-types/commands.markdown
Since forward slash will be added in
https://github.com/cfengine/core/pull/3472, I have altered the
documentation entry to no longer point to CFE-2478, and added
that forward slash is allowed.
Ticket: CFE-2478
(cherry picked from commit c72c38eb6b4ed0c4aff742968d3e3cee73c125ee)
=> CFE-2478: Fixed documentation entry for `module` 3.10

reference/special-variables/sys.markdown
This change corrects the documented expected value of sys.policy_hub, fixes some
small formatting issues and removes the duplicate entry for sys.policy_hub in
the docs.
(manually picked from commit fb853c7)
=> CFE-3033 Document correct expected value and provenance of sys.policy_hub (3.10)

reference/functions/lsdir.markdown
The previous tip would actually omit all files whose names start with a period, not just "." and ".."
=> Fix tip in lsdir documentation

reference/functions/lsdir.markdown
The previous tip would actually omit all files whose names start with a period, not just "." and ".."
(cherry picked from commit 3f4819e2f5da20b140c1539ea9eebb94430ae87a)
=> Fix tip in lsdir documentation (3.10)

guide/installation-and-configuration/upgrading.markdown
The BACKUP_DIR environment variable overrides the default location to backup the
PostgreSQL database during package upgrade. It's important to have enough space
to properly complete the automated backup and restore for database migration to
complete successfully.
=> Note BACKUP_DIR in hub upgrade docs

reference/promise-types/processes.markdown
process_owner is not an attribute, it's part of the process_select body.
Ticket: CFE-3040
=> CFE-3040: Fix process promise example (3.10)

reference/promise-types/processes.markdown
process_owner is not an attribute, it's part of the process_select body.
Ticket: CFE-3040
=> CFE-3040: Fix process promise example (3.12)

guide/special-topics/content-driven-policy.markdown
Hello,
The page on Content-Driven Policy was added 3 years ago, and needs to be updated.
I'm opening this pull request to initiate that.  I've fixed a few obvious typos.
Here is what's left to fix:
1. Fix reference to cdp_inputs which is no longer present in "masterfiles".
Git history shows:
```
[d511695@cfedevdevlabc02:~/git/masterfiles] master+ 2s 141 ± git log -i -S  cdp_inputs
commit f9e45090dcf9220eac70f67b8d50d7317fd864ca
Author: Mikhail Gusarov <mikhail.gusarov@cfengine.com>
Date:   Tue Aug 9 10:50:33 2011 +0000
Move Nova-specific masterfiles to Nova
commit f3b877d98978be5684c5dad92ca87480a69b1b77
Author: Mark Burgess <mark@cfengine.com>
Date:   Wed Jun 29 20:32:31 2011 +0000
Put CDP back
commit 4d05f6154098624bc042fe02ff7a9d25b7a16b44
Author: Mark Burgess <mark@cfengine.com>
Date: …
```
=> Fix typos and update the page on Content Driven Policies 

guide/faq/enterprise-report-collection.markdown, guide/introduction/directory-structure.markdown
Redis cache was refactored out in 3.12 LTS.
=> Remove reference to Redis cache from Enterprise documentation

reference/functions/now.markdown
Ticket: CFE-3075
(cherry picked from commit 79630216e9cc0b2c7b197be87cc9be45d612e172)
=> Improved examples to show  how now() can be used to get agent start time

reference/functions/eval.markdown
(cherry picked from commit 460ae930c71cbab14d57475ecbcac504347badfa)
=> CFE-3097: Switch eval() to use example and output from core/examples (3.12)

reference/functions/eval.markdown
(cherry picked from commit 460ae930c71cbab14d57475ecbcac504347badfa)
=> CFE-3097: Switch eval() to use example and output from core/examples (3.10)

reference/functions/hostrange.markdown
The documentation of the behavior and formats of arguments needs
to be as precise as possible.
Ticket: CFE-3104
=> Add some details about the hostrange() function

reference/functions/data_regextract.markdown
https://github.com/cfengine/core/pull/3871
=> CFE-3171/master: Added references to dotall and multiline modes for data_regextract()

reference/functions.markdown, reference/language-concepts/classes.markdown, reference/promise-types.markdown
`unless` was recently changed in 2 ways:
* Fixed evaluation when there are unresolved variables in early
evaluation passes.
* Removed confusing error message when there are function calls
which never resolve. Made the constraint work as intended;
opposite of `if`.
=> CFE-3160: Clarified behavior of if/unless after recent changes

enterprise-cfengine-guide.markdown
added article before word 'datacenter' in sentence: 'Achieve repeatable, error-free and automated deployment of middleware and application components to datacenter or cloud-based infrastructure.'
new sentence: Achieve repeatable, error-free and automated deployment of middleware and application components to a datacenter or cloud-based infrastructure.
=> missing article

examples/example-snippets/promise-patterns/package_bundles.markdown
Reverts cfengine/documentation#2249
Turns out this file is not published, it's the "old" version of the docs. Should probably delete the file. That's why we have version control, right?
=> Revert "CFE-3205: Fixed various references to cfe_package bundles"

reference/special-variables/sys.markdown
Ticket: CFE-3225
(cherry picked from commit 088c00c45ec4e38a90d6e2c2d598b4be068591ff)
=> CFE-3225/3.12: Added note indicating interface names are canonified in some sys vars

reference/special-variables/sys.markdown
Ticket: CFE-3225
(cherry picked from commit 088c00c45ec4e38a90d6e2c2d598b4be068591ff)
=> CFE-3225/3.10: Added note indicating interface names are canonified in some sys vars

guide/latest-release/supported-platforms.markdown
- Dropped Enterprise Hub support on Ubuntu 14 and Debian 8
- Dropped standard support for EL5 and Debian 7
- Added standard support for EL8 (*except enterprise hubs)
=> Updated supported platforms for 3.15.0

guide/installation-and-configuration/general-installation/installation-enterprise-generic-tarball.markdown
The previous filename does not exist, the filename contains either i386 or x86_64.
=> Specify different unpack for 32/64 bit tarball

reference/components/cf-hub.markdown
When using single backticks, the documentation generator tries
to create automatic links (As explained in README). This goes
horribly wrong somehow, and so after looking at other parts
of the docs, it seems we usually use triple backticks for
command line options, to prevent automatic linking.
=> CFE-3254: Fixed docs rendering of --query-timeout

enterprise-cfengine-guide/high-availability/installation-guide.markdown
1) Reformatted the file to not use horribly long lines.
2) Rearranged the steps so they follow the logical order of
setting the base things *before* the things that build on top
of the base. So now the cluster is built first then the
PostgreSQL replication is setup then the PG replication is
integrated with the cluster and finally CFEngine is pulled
into the game with its own stuff.
3) Modified the steps to use our tailored Resource Agent which
supports both RHEL 6 and PostgreSQL 10 and to avoid some
issues with things happening automatically in the background
in between the individual steps.
4) Simplified some steps and tried to make it clearer which
commands need to be run where.
(cherry picked from commit 1e488ea2e396c8507516cbe9c3b54ac6ca559f35)
=> ENT-4090: Fix/update the HA installation guide

enterprise-cfengine-guide/federated-reporting.markdown
Need this for pre 3.14 hubs in order to enable federated reporting manually.
=> Added "target_state" to federation-config.json

enterprise-cfengine-guide/federated-reporting.markdown
re-ordered `sudo` arg to correct place for latest `cf-remote`.
fixed typo of `CLOUDUSER` versus `CLOUD_USER`
Ticket: none
=> Improved manual feeder setup slightly

reference/promise-types/storage.markdown
https://github.com/cfengine/core/pull/4174
Added cifs and panfs mount types new in 3.15.0.
Ticket: CFE-3187
(cherry picked from commit 5d0d5cce03d7dda82da4afdbda194c9cf6dc6cca)
=> Added panfs, cifs mount types

examples.markdown
The criteria used is:
- When instructing the user to run a command, format it as console but
do not prepend the console prompt.
- When showing the result of a command, format it also as console and
prepend the prompt.
Minor adjustment in other snippet missing cf3 format.
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
=> Unify commands and console snippets in examples

enterprise-cfengine-guide/hub_administration/policy-deployment.markdown, guide/writing-and-serving-policy.markdown, reference/promise-types/packages.markdown
* Properly format as a nested list
Without the blank line, both lists are showed in the same line.
* Fix two typos
=> Properly format as a nested list + Fix two typos

reference/functions/execresult.markdown, reference/functions/execresult_as_data.markdown
https://github.com/cfengine/core/pull/4268
https://github.com/cfengine/nova/pull/1695
https://github.com/cfengine/documentation/pull/2344
=> Added documentation for new function, execresult_as_data()

reference/functions/execresult_as_data.markdown
There is no prep section in the example, this causes the doc build to fail:
,#+begin_example
18:44:59 Unexpanded macro in '/home/jenkins/workspace/build-documentation-master/label/DOCUMENTATION_x86_64_linux_ubuntu_16/documentation/reference/functions/execresult_as_data.markdown', html-line '<p>[%CFEngine_include_snippet(execresult_as_data.cf, #+begin_src prep, .*end_src)%]</p>
18:44:59 '
18:44:59
18:44:59       Exception: (<type 'exceptions.Exception'>, Exception('1 errors while processing HTML files',), <traceback object at 0x7fc70a5b1bd8>)
18:44:59 + '[' 1 -gt 0 ']'
,#+end_example
=> Removed rendering of prep section for example

enterprise-cfengine-guide/federated-reporting.markdown, reference/masterfiles-policy-framework/cfe_internal-enterprise-federation-federation.markdown
Mention two augments available: auto install semanage and handle duplicate hostkeys during import.
Ticket: ENT-6035
Changelog: title
merge together:
https://github.com/cfengine/masterfiles/pull/1828
https://github.com/cfengine/documentation/pull/2361
=> Added overview of Federated Reporting policy

examples/example-snippets/all_hosts_the_same.cf, examples/example-snippets/client-server_example.cf, examples/example-snippets/copy_and_flatten_directory.cf, examples/example-snippets/promise-patterns/example_updating_from_central_hub.markdown, examples/example-snippets/updating_from_a_central_hub.cf, examples/example-snippets/variation_in_hosts.cf, examples/tutorials/distribute-files-from-a-central-location.markdown, guide/introduction/networking.markdown, guide/special-topics/distributed-scheduling.markdown, guide/special-topics/file-integrity-monitoring.markdown.breaks_build, guide/special-topics/modularity.markdown, guide/special-topics/role-based-access-control.markdown.breaks_build, reference/components/cf-serverd.markdown, reference/promise-types/access.markdown, reference/promise-types/roles.markdown
This change is intended to help clarify the fact that users can (and should)
define their own server bundles instead of modifying the vendored policy and
that bundle server access_rules is not a special name.
Merge with: https://github.com/cfengine/masterfiles/pull/1839
=> CFE-3427/master: Changed references from bundle server access_rules to my_access_rules

cheatsheet.markdown
The `endraw` tag is wrong and leads to the following error when running `jekyll build`:
Liquid Exception: Liquid syntax error (line 518): 'raw' tag was never closed in cheatsheet.markdown
=> fix endraw tag

reference/functions/iprange.markdown
Ticket: CFE-3450
(cherry picked from commit 3ae47e3c64c5f8dca5fe42a9635abfb0db37044a)
=> CFE-3450/3.12: Made more obvious that iprange() interface is optional

examples/example-snippets/ensure_running_1.cf
This example disagrees with itself, referencing both
"component" and "components". The other examples call the
slist "component" so I went for that.
=> CFE-3472: ensure_running_1.c: Fixed components -> component

reference/promise-types/packages.markdown
- Removed unnecessary specification of package_module in example snippets
- Added reference about platforms where yum package module is the default
- Added note and example illustrating how yum will downgrade packages
=> CFE-3479/master: Improved yum package_module docs

reference/promise-types/vars.markdown
CFEngine doesn't interpret \n in strings as a newline, if a newline is needed,
$(const.n) should be used.
=> CFE-3551/master: Fixed syntax in example inline yaml

reference/promise-types/vars.markdown
CFEngine doesn't interpret \n in strings as a newline, if a newline is needed,
$(const.n) should be used.
(cherry picked from commit ae175d98e72b10c93aac1c826e865badce015063)
=> CFE-3551/3.15: Fixed syntax in example inline yaml

reference/promise-types/vars.markdown
CFEngine doesn't interpret \n in strings as a newline, if a newline is needed,
$(const.n) should be used.
(cherry picked from commit ae175d98e72b10c93aac1c826e865badce015063)
=> CFE-3551/3.12: Fixed syntax in example inline yaml

enterprise-cfengine-guide/high-availability/installation-guide.markdown
RHEL/CentOS 6 is EOL so we shouldn't encourage users to build
their HA setups on it.
Ticket: ENT-6825
=> Update HA installation instructions to RHEL/CentOS 7

enterprise-cfengine-guide/high-availability/installation-guide.markdown
RHEL/CentOS 6 is EOL so we shouldn't encourage users to build
their HA setups on it.
Ticket: ENT-6825
=> [3.15] Update HA installation instructions to RHEL/CentOS 7

reference/promise-types/files.markdown
It's been 4349 days (~12 years ago) since CFEngine 2 has seen a release. It's
not a good reference any more.
Ticket: CFE-3605
=> CFE-3605/master: Removed old reference to cf2 actionsequence

reference/promise-types/files.markdown
It's been 4349 days (~12 years ago) since CFEngine 2 has seen a release. It's
not a good reference any more.
Ticket: CFE-3605
(cherry picked from commit 01928921826b1863cc1e9e2806de1cbf93b85f5e)
=> CFE-3605/3.15: Removed old reference to cf2 actionsequence

reference/promise-types/files.markdown
It's been 4349 days (~12 years ago) since CFEngine 2 has seen a release. It's
not a good reference any more.
Ticket: CFE-3605
(cherry picked from commit 01928921826b1863cc1e9e2806de1cbf93b85f5e)
=> CFE-3605/3.12: Removed old reference to cf2 actionsequence

reference/promise-types/files.markdown
Reverts cfengine/documentation#2418
=> Revert "CFE-3605/3.15: Removed old reference to cf2 actionsequence"

reference/promise-types/files.markdown
Reverts cfengine/documentation#2419
=> Revert "CFE-3605/3.12: Removed old reference to cf2 actionsequence"

legal.markdown
To have more clean and sharp-looking icons within the mission portal, we would like to include Bootstrap's icon set in the MP UI design. 
Ticket: ENT-7059
Changelog: Added Bootstrap icon license reference
=> ENT-7059: Added Bootstrap icon license reference (master)

reference/promise-types/custom.markdown
I'd like to split up the content and add some more information
and links, but for this iteration 0, I've just copy-pasted the
entire file from core.
=> Added Custom promise types documentation from core

reference/functions/parseintarray.markdown, reference/functions/parserealarray.markdown, reference/functions/parsestringarray.markdown
merge together: https://github.com/cfengine/core/pull/4668
Ticket: CFE-3673
=> CFE-3673: Switched to correct examples from core for parse*array functions (master)

examples/tutorials/dashboard-alerts.markdown
Fixed the typo in the successful alert creation paragraph. 
Changelog: Fixed typo of zeor to zero
=> Fixed typo of zeor to zero

guide.markdown
The page is called just "upgrading" now, without version.
=> ENT-7355 fix upgrading link in guide

reference/promise-types/commands.markdown
Running the bellow bundle indicates that the default
value is not false but true, as output is reported.
```
bundle agent main
{
commands:
"/bin/touch /tmp/module_cache";  # expect output
"/bin/cat /tmp/module_cache"  # expect no output
inform => "false";
}
```
Command: `sudo cf-agent -KI inform.cf`
Output:
```
info: Executing 'no timeout' ... '/bin/touch /tmp/module_cache'
info: Completed execution of '/bin/touch /tmp/module_cache'
```
Ticket: None
=> Changed commands' attribute inform default value to true

reference/promise-types/measurements.markdown
Specifically:
- Where measurements with history_type log are recorded.
- What history_type values are and aren't collected by Enterprise Reporting
Ticket: ENT-4768
=> ENT-4768: Added details about measurements (master)

reference/promise-types/measurements.markdown
Specifically:
- Where measurements with history_type log are recorded.
- What history_type values are and aren't collected by Enterprise Reporting
Ticket: ENT-4768
(cherry picked from commit 6b36fcb89ec7216af14e3f39db4f810d377ca2fa)
=> ENT-4768: Added details about measurements (3.18)

reference/promise-types/measurements.markdown
Specifically:
- Where measurements with history_type log are recorded.
- What history_type values are and aren't collected by Enterprise Reporting
Ticket: ENT-4768
(cherry picked from commit 6b36fcb89ec7216af14e3f39db4f810d377ca2fa)
=> ENT-4768: Added details about measurements (3.15)

guide/special-topics/security.markdown
I made some tweaks which should help pass the build, and I added a comment with
the text from the old cfengine.com/learn section on security. The comment
includes the link to the youtube video presentation where Diego discusses
security. Since the video is private, I figured that this was the best place to
leave a bread crumb.
(cherry picked from commit d8cdd96b729d742a1cc3b5753482f715403625ff)
=> ENT-6853: Published special topics Security (3.18)

enterprise-cfengine-guide/federated-reporting.markdown
This is a hack and not needed. If no access is desired it would
be better to do this in access rules policy.
Ticket: ENT-7492
=> ENT-7492 Remove reference to bootstrapping superhub to localhost

reference/functions/packagesmatching.markdown, reference/functions/packageupdatesmatching.markdown
=> CFE-3775: Added link from packagesmatching* functions to related MPF tunables (3.18)

reference/language-concepts/augments.markdown
To make it easier to link to specific things about augments, like host specific
data.
Ticket: CFE-3789
(cherry picked from commit 1444c8b889dd64aafac7b55d47dff345fabc1fce)
=> CFE-3789 Added sections for files in Augments docs (3.18)

reference/special-variables/const.markdown
The example covers all const variables in addition to the new const.at variable.
Ticket: CFE-3793
=> CFE-3793: Added docs and example for const.at

reference/language-concepts/variables.markdown
Ticket: CFE-3794
(cherry picked from commit 96843faa376dc59146e89c7f897b57ffd7075567)
=> CFE-3794: Removed indication that associative arrays are being deprecated (3.15)

reference/enterprise-api-ref/host.markdown
3.18 has the deleted column in the __hosts table which is updated with the
timestamp of the host deletion. This record is retained and is used to prevent
further collection from the deleted identity.
=> ENT-8313: Redacted notes indicating a deleted host could re-appear automatically

reference/enterprise-api-ref/host.markdown
3.18 has the deleted column in the __hosts table which is updated with the
timestamp of the host deletion. This record is retained and is used to prevent
further collection from the deleted identity.
Ticket: ENT-8313
(cherry picked from commit f3847ff73388d8cb98cac870009a86ff7b257a08)
=> ENT-8313: Redacted notes indicating a deleted host could re-appear automatically (3.18)

reference/components/cf-serverd.markdown
=> ENT-5313: Added note about enable_report_dumps magic file to cf-serverd component page

reference/components/cf-serverd.markdown
Ticket: ENT-5313
(cherry picked from commit fe632f9ab0b0be901171ae6d18ac10f1dbe84611)
=> ENT-5313: Added note about enable_report_dumps magic file to cf-serverd component page (3.18)

reference/enterprise-api-ref/cmdb-api.markdown
Noticed when reading the docs and using the API.
=> Remove an extra 'Parameters' section in Update CMDB API docs

reference/enterprise-api-ref/cmdb-api.markdown
Noticed when reading the docs and using the API.
(cherry picked from commit e017ae59452c1d59051dcff0e2be75dd175eed70)
=> Remove an extra 'Parameters' section in Update CMDB API docs (3.18)

examples/example-snippets/promise-patterns/example_ssh_keys.markdown, guide/faq/enterprise-report-collection.markdown, guide/faq/unable-to-log-in-mission-portal.markdown, guide/introduction/networking.markdown, reference/enterprise-api-ref/host.markdown, reference/enterprise-api-ref/sql-schema.markdown, reference/language-concepts/classes.markdown
* https://github.com/cfengine/misc/pull/147
* https://github.com/cfengine/documentation/pull/2662
By default Virtualbox only allows host-only networking on 192.168.56.0/24.
This change is done to make instructions and example output comport with the
same change in our Vagrant Quickstart environment.
Ticket: CFE-3952
Changelog: Switched Vagrant Quickstart Environment subnet from 192.168.33.0/24 to 192.168.56.0/24 in order to better align with Virtualbox defaults
=> CFE-3952: Switched to 192.168.56.0/24 from 192.168.33.0/24

examples/tutorials/manage-ntp.markdown, reference/functions/bundlestate.markdown, reference/functions/datastate.markdown, reference/promise-types/files.markdown
The automatic link target was resolving to a tutorial instead of the promise
attribute on the files type promise page. This change makes the link target
explicit based on the page title.
Ticket: CFE-3957
=> CFE-3957: Fixed link target for template_method

examples/tutorials/manage-ntp.markdown, reference/functions/bundlestate.markdown, reference/functions/datastate.markdown, reference/promise-types/files.markdown
The automatic link target was resolving to a tutorial instead of the promise
attribute on the files type promise page. This change makes the link target
explicit based on the page title.
Ticket: CFE-3957
(cherry picked from commit 2e5f664ff3cc347a47a6575b3ad818037daa8869)
=> CFE-3957: Fixed link target for template_method (3.18)

examples/tutorials/manage-ntp.markdown, reference/functions/bundlestate.markdown, reference/functions/datastate.markdown, reference/promise-types/files.markdown
The automatic link target was resolving to a tutorial instead of the promise
attribute on the files type promise page. This change makes the link target
explicit based on the page title.
Ticket: CFE-3957
(cherry picked from commit 2e5f664ff3cc347a47a6575b3ad818037daa8869)
=> CFE-3957: Fixed link target for template_method (3.15)

guide/additional-resources.markdown, guide/writing-and-serving-policy/policy-style.markdown
=> ENT-8542: Fixed links to page detailing editors with CFEngine support

guide/additional-resources.markdown, guide/writing-and-serving-policy/policy-style.markdown
Ticket: ENT-8542
(cherry picked from commit 6de0df83a9838118616d7dcdf1915b9c1965cb50)
=> ENT-8542: Fixed links to page detailing editors with CFEngine support (3.18)

guide/additional-resources.markdown, guide/writing-and-serving-policy/policy-style.markdown
Ticket: ENT-8542
(cherry picked from commit 6de0df83a9838118616d7dcdf1915b9c1965cb50)
=> ENT-8542: Fixed links to page detailing editors with CFEngine support (3.15)

reference/functions/readfile.markdown
Ticket: CFE-3958
(cherry picked from commit dccdf95bac74f4d93cff5a0f804a63bfde9462e1)
=> CFE-3958: Removed stale notes and updated history for readfile() (3.18)

reference/functions/readfile.markdown
Ticket: CFE-3958
(cherry picked from commit dccdf95bac74f4d93cff5a0f804a63bfde9462e1)
=> CFE-3958: Removed stale notes and updated history for readfile() (3.15)

reference/promise-types/access.markdown
This change simply removes attribute sections for report_data_select attribtues
that were removed back in 3.6.0. Now, instead of each of them having their own
section, they are all listed as removed in the main history for report_data_select.
=> ENT-8549: Moved deprecated report_data_select attributes to History

reference/promise-types/access.markdown
This change simply removes attribute sections for report_data_select attribtues
that were removed back in 3.6.0. Now, instead of each of them having their own
section, they are all listed as removed in the main history for report_data_select.
(cherry picked from commit 7bf8eb43eb89d0dee70f8de0d6da5141c1defab1)
=> ENT-8547: Moved deprecated report_data_select attributes to History (3.18)

reference/promise-types/access.markdown
This change simply removes attribute sections for report_data_select attribtues
that were removed back in 3.6.0. Now, instead of each of them having their own
section, they are all listed as removed in the main history for report_data_select.
=> ENT-8547: Moved deprecated report_data_select attributes to History (3.15)

enterprise-cfengine-guide/install-get-started.markdown
The inline examples contained outdated information about underscore prefixed
variables. Instead of updating the inline examples this change points users to
the Masterfiles Policy Framework Reference which covers how to use Augments for
configuring which measurements are collected for central reporting.
=> ENT-8547: Replaced inline examples in install guide with link to configuration reference

enterprise-cfengine-guide/install-get-started.markdown
The inline examples contained outdated information about underscore prefixed
variables. Instead of updating the inline examples this change points users to
the Masterfiles Policy Framework Reference which covers how to use Augments for
configuring which measurements are collected for central reporting.
(cherry picked from commit 701d9451dd08a0e1b3c5e9d08e3100ab15af0ddc)
=> ENT-8547: Replaced inline examples in install guide with link to configuration reference (3.18)

enterprise-cfengine-guide/install-get-started.markdown
The inline examples contained outdated information about underscore prefixed
variables. Instead of updating the inline examples this change points users to
the Masterfiles Policy Framework Reference which covers how to use Augments for
configuring which measurements are collected for central reporting.
(cherry picked from commit 701d9451dd08a0e1b3c5e9d08e3100ab15af0ddc)
=> ENT-8547: Replaced inline examples in install guide with link to configuration reference (3.15)

enterprise-cfengine-guide/reporting.markdown
Since 3.6.0 there has been no capability to influence variable collection based
on variable names.
(cherry picked from commit e3b0d091c57f576c44d67d2263b14983e418c89a)
=> ENT-8547: Redacted mention of underscore prefixed variables (3.18)

enterprise-cfengine-guide/reporting.markdown
Since 3.6.0 there has been no capability to influence variable collection based
on variable names.
(cherry picked from commit e3b0d091c57f576c44d67d2263b14983e418c89a)
=> ENT-8547: Redacted mention of underscore prefixed variables (3.15)

guide/writing-and-serving-policy/policy-style.markdown
This section was misleading. The reference to underscore prefixed variables
related to a default related to Enterprise Reporting that has not been true
since 3.6.0.
=> ENT-8547: Removed section about "internal" variables and classes from policy style guide

guide/writing-and-serving-policy/policy-style.markdown
This section was misleading. The reference to underscore prefixed variables
related to a default related to Enterprise Reporting that has not been true
since 3.6.0.
(cherry picked from commit 3b6189eb38c4c523fd2dea9722e3675e3f373a6f)
=> ENT-8547: Removed section about "internal" variables and classes from policy style guide (3.18)

guide/writing-and-serving-policy/policy-style.markdown
This section was misleading. The reference to underscore prefixed variables
related to a default related to Enterprise Reporting that has not been true
since 3.6.0.
(cherry picked from commit 3b6189eb38c4c523fd2dea9722e3675e3f373a6f)
=> ENT-8547: Removed section about "internal" variables and classes from policy style guide (3.15)

enterprise-cfengine-guide/hub_administration/lookup-license-info.markdown
Using the --show-license option is much nicer than starting cf-hub daemon and
grepping the output. It's been available since 3.15.0.
Ticket: ENT-8552
=> ENT-8552: Switched to using cf-hub --show-license instead of grepping log output

enterprise-cfengine-guide/hub_administration/lookup-license-info.markdown
Using the --show-license option is much nicer than starting cf-hub daemon and
grepping the output. It's been available since 3.15.0.
Ticket: ENT-8552
(cherry picked from commit 8662389bdfdb9ae86c07422b29b283f1ad056d4a)
=> ENT-8552: Switched to using cf-hub --show-license instead of grepping log output (3.18)

enterprise-cfengine-guide/hub_administration/lookup-license-info.markdown
Using the --show-license option is much nicer than starting cf-hub daemon and
grepping the output. It's been available since 3.15.0.
Ticket: ENT-8552
(cherry picked from commit 8662389bdfdb9ae86c07422b29b283f1ad056d4a)
=> ENT-8552: Switched to using cf-hub --show-license instead of grepping log output (3.15)

reference/components.markdown
We neglected to update the documentation after releasing protocol_version 3,
this is just back-filling those details.
Ticket: ENT-8560
=> ENT-8560: Updated docs on protocol_version

reference/components.markdown
We neglected to update the documentation after releasing protocol_version 3,
this is just back-filling those details.
=> ENT-8560: Updated docs on protocol_version (3.18)

reference/components.markdown
We neglected to update the documentation after releasing protocol_version 3,
this is just back-filling those details.
=> ENT-8560: Updated docs on protocol_version (3.15)

reference/promise-types/methods.markdown, reference/promise-types/reports.markdown
This change simply makes it easier to hop back and forth between related things
in the documentation.
=> ENT-8792: Added cross-reference between reports bundle_return_value_index and methods useresult attributes

reference/promise-types/methods.markdown, reference/promise-types/reports.markdown
This change simply makes it easier to hop back and forth between related things
in the documentation.
=> ENT-8792: Added cross-reference between reports bundle_return_value_index and methods useresult attributes (3.18)

reference/promise-types/methods.markdown, reference/promise-types/reports.markdown
This change simply makes it easier to hop back and forth between related things
in the documentation.
=> ENT-8792: Added cross-reference between reports bundle_return_value_index and methods useresult attributes (3.15)

enterprise-cfengine-guide/federated-reporting.markdown
And, in particular, make the last 'curl' invocation bold because
it's easy to miss.
Ticket: ENT-8851
=> Make instructions for feeder uninstallation clearer

reference/language-concepts/augments.markdown
In my experience, it is very common for people to encounter the
Augments file format for the first time when they want to
interact with the MPF, commonly by changing some value,
or to add bundles and inputs.
The Augments documentation was not very helpful in this aspect,
it barely mentioned the MPF or any of the "most common" ways to
use Augments.
To fix this I added a short section with an explanation and
example to the beginning, and a link to the MPF documentation,
which is maybe what a lot of people actually need.
=> Added a section about MPF to the beginning of the Augments documentation

reference/language-concepts/augments.markdown
I thought this title gives a more high level, goal oriented view
on it. Also, we use modify / edit many times in the text, so
a header with different wording might be nice.
=> Changed title of MPF section in Augments docs

reference/components/cf-execd.markdown, reference/components/cf-runagent.markdown
Ticket: ENT-6182
(cherry picked from commit 8e9630df01c722a363555807e920c993618a8cce)
=> ENT-6182: Added docs referencing cf-runagent socket activation (3.18)

reference/components/cf-execd.markdown
=> ENT-6182: Added documentation for runagent_socket_allow_users attribute in body executor control

enterprise-cfengine-guide/federated-reporting.markdown
Without a blank line things run together and the ls commands are seen as level 1
headings, super ugly.
Ticket: ENT-8989
=> ENT-8989: Fixed rendering

enterprise-cfengine-guide/federated-reporting.markdown
Without a blank line things run together and the ls commands are seen as level 1
headings, super ugly.
Ticket: ENT-8989
(cherry picked from commit 9e0c594512efaba7fdd84d4173c967001d6fb545)
=> ENT-8989: Fixed rendering (3.20)

enterprise-cfengine-guide/federated-reporting.markdown
Without a blank line things run together and the ls commands are seen as level 1
headings, super ugly.
Ticket: ENT-8989
(cherry picked from commit 9e0c594512efaba7fdd84d4173c967001d6fb545)
=> ENT-8989: Fixed rendering (3.18)

reference/special-variables/sys.markdown
Added in 3.18.0, but documentation was neglected.
=> CFE-4009: Added docs for sys.os_name_human and sys.os_version_major (3.18)

enterprise-cfengine-guide/alerts-custom-actions.markdown
Resized the images on the [custom alert page](https://docs.cfengine.com/docs/master/enterprise-cfengine-guide-alerts-custom-actions.html#top).
Ticket: ENT-8878
Changelog: Resized the image on the custom alert page
=> ENT-8878: Resized images on the custom alert page (master)

reference/promise-types/files.markdown, reference/promise-types/files/edit_line.markdown, reference/special-variables/edit.markdown
Ticket: ENT-5866
(cherry picked from commit ea9c87a916b722b7d1d0f8d4379866661dac2618)
=> ENT-5866: Added documentation for edit.empty_before_use special variable (3.18)

web-ui/hub_administration/policy-deployment.markdown
Resized the images in the [Policy Deployment page.](https://docs.cfengine.com/docs/master/web-ui-hub_administration-policy-deployment.html)
Ticket: ENT-8883
Changelog: Resized the images in the Policy Deployment page
=> ENT-8883: Resized the images in the Policy Deployment page

web-ui/hub_administration/custom-ldap-port.markdown
Resized the images in custom [LDAP page](https://docs.cfengine.com/docs/master/web-ui-hub_administration-custom-ldap-port.html)
Ticket: ENT-8883
Changelog: Resized the images in custom LDAP page
=> ENT-8883: Resized the image in the custom LDAP page

examples/tutorials/high-availability.markdown
Resized the image size on the High availability page and deleted ha_degraded_details.png as the content of the image had already been included in the ha_degraded_indicator.png image. 
Ticket: ENT-8882
Changelog: Resized the image size on the High availability page and deleted duplicate content images.
=> ENT-8882: Resized the image size on the High availability page (master)

reference/promise-types/custom.markdown
Specification of line_based/json_based is actually required.
=> Fix custom promise module initial exchange header spec

reference/components/cf-monitord.markdown
=> ENT-7426: Added documentation about where cf-monitord stores data

reference/components/cf-monitord.markdown
Ticket: ENT-7426
(cherry picked from commit 928625fb4a013ef43d66284fd4685e91f4e32639)
=> ENT-7426: Added documentation about where cf-monitord stores data (3.18)

reference/components/cf-monitord.markdown
Ticket: ENT-7426
(cherry picked from commit 928625fb4a013ef43d66284fd4685e91f4e32639)
=> ENT-7426: Added documentation about where cf-monitord stores data (3.15)

generator/_scripts/_run_jekyll.sh
Sometimes it caused unexpanded (unstyled) *.html files to be copied,
instead of proper ones, on line 14 of generator/_scripts/_publish.sh.
Ticket: ENT-8967
=> remove generator from pages

generator/_scripts/_run_jekyll.sh
Sometimes it caused unexpanded (unstyled) *.html files to be copied,
instead of proper ones, on line 14 of generator/_scripts/_publish.sh.
Ticket: ENT-8967
(cherry picked from commit aa7635f0c458367be414bf8c8bab4fda46d7948e)
=> remove generator from pages - 3.18

generator/_scripts/_run_jekyll.sh
Sometimes it caused unexpanded (unstyled) *.html files to be copied,
instead of proper ones, on line 14 of generator/_scripts/_publish.sh.
Ticket: ENT-8967
(cherry picked from commit aa7635f0c458367be414bf8c8bab4fda46d7948e)
=> Remove generator from pages - 3.15

generator/_includes/footer.html
Use branch version instead of the current master CFEnigne version
=> Fixed `Download all documentation` link

examples/tutorials/write-cfengine-policy.markdown, resources/faq/bootstrap-failed.markdown, resources/faq/enterprise-report-collection.markdown, resources/faq/enterprise.markdown, resources/faq/fhs.markdown, resources/faq/fix-undefined-body-error.markdown, resources/faq/manual-execution.markdown, resources/faq/output-email.markdown, resources/faq/show-classes-and-vars.markdown, resources/faq/uninstall-reinstall.markdown, resources/faq/users.markdown, resources/faq/what-did-cfengine-change.markdown
- ENT-8434: Added some short summary sentences to FAQ pages
- Corrected capitalization of CFEngine in a few places
- Fixed some bad h1 headers in FAQ
=> Various cleanups in FAQ

index.markdown
The getting started links currently point to some of the old installation instructions, etc.
Better to highlight the new content.
=> Updated getting started links on docs home page

reference/promise-types/files.markdown
Ticket: ENT-9194
(cherry picked from commit bc2e964862a10de603676ba507f66a8f4522028c)
=> ENT-9194: Cleaned up history for acl attribute

generator/_includes/head.html
See ticket:
https://tracker.mender.io/browse/ENT-9202
=> ENT-9202: Changed order of docs page titles to highlight more specific part first

reference/components/cf-agent.markdown
This change switches the example to a full runnable example from core and
clarifies the description of the attribute.
Ticket: CFE-4065
=> CFE-4065: Improved documentation for files_auto_define

api/enterprise-api-ref/cmdb-api.markdown
There needs to be a blank line before the first item in the list.
=> Fix formatting for the first param in CMDB API docs

reference/functions/accumulated.markdown, reference/functions/ago.markdown, reference/functions/irange.markdown, reference/functions/now.markdown, reference/promise-types/files.markdown, reference/promise-types/processes.markdown
Ticket: CFE-4095
(cherry picked from commit d9a942d0cdba7aaf40b52ebedd00812583ec330c)
=> CFE-4095: Added cross references for function irange() (3.18)

reference/functions/accumulated.markdown, reference/functions/ago.markdown, reference/functions/irange.markdown, reference/functions/now.markdown, reference/promise-types/files.markdown, reference/promise-types/processes.markdown
Ticket: CFE-4095
(cherry picked from commit d9a942d0cdba7aaf40b52ebedd00812583ec330c)
=> CFE-4095: Added cross references for function irange() (3.15)

web-ui/settings.markdown
This change simply tries to make it clear that roles matching the LDAP groups
you wish to synchronize must be created in Mission Portal for LDAP group syncing
to have effect.
Ticket: ENT-9586
=> ENT-9586: Added note that LDAP group sync does not add or remove Mission Portal roles

enterprise-cfengine-guide/settings.markdown
This change simply tries to make it clear that roles matching the LDAP groups
you wish to synchronize must be created in Mission Portal for LDAP group syncing
to have effect.
Ticket: ENT-9586
(cherry picked from commit 010f20d40e99901be7f1ece82f7894d055341436)
=> ENT-9586: Added note that LDAP group sync does not add or remove Mission Portal roles (3.18)

reference/functions/classfiltercsv.markdown, reference/functions/data_expand.markdown, reference/functions/mergedata.markdown, reference/functions/readcsv.markdown, reference/functions/readdata.markdown, reference/functions/readenvfile.markdown, reference/functions/readjson.markdown, reference/functions/readyaml.markdown
Most functions that return data (notably, functions that read content from a
file, e.g. readjson() ) do not de-reference CFEngine variables within that data.
This change simply cross references functions that return data where someone
might have expected CFEngine variables to have been dereferenced with
data_expand() to bring more awareness.
Ticket: CFE-4098
=> CFE-4098: Added cross references related to data_expand()

generator/build/search/createIndex.js
Ticket: ENT-9471
This change fixes the case when headings are located in sequence and parsed as one heading
=> Fixed headers regex matching greedy and no space between tags in the search description

getting-started/installation/general-installation.markdown, getting-started/installation/general-installation/installation-enterprise.markdown
Especially now that the hub package has an external dependency on python it's
much nicer to use yum and apt which will try to auto-solve the dependencies
unlike rpm and dpkg.
=> ENT-9722: Updated package install commands for enterprise to use yum and apt

getting-started/installation/general-installation.markdown, getting-started/installation/general-installation/installation-enterprise.markdown
Especially now that the hub package has an external dependency on python it's
much nicer to use yum and apt which will try to auto-solve the dependencies
unlike rpm and dpkg.
Ticket: ENT-9722
(cherry picked from commit fdc77fb5246dcac21bd2ef3a83cffc79a2ad3ddd)
=> ENT-9722: Updated package install commands for enterprise to use yum and apt (3.21)

generator/_assets/js/dropdown.js
instead of relying on querySelector - since it's unreliable
=> Explicitly fallback to first available version in dropdown

release-notes/supported-platforms.markdown
- Added EL9 hub and agent
- Added Debian 11 hub and agent, x86-64 and arm64
- Added Ubuntu 22.04 hub and agent, x86-64 and arm64
- Removed SLES 11
- Removed Solaris 10 (UltraSparc & x86_64)
=> ENT-9421 Updated supported platforms with the release of 3.21.0

reference/functions/getusers.markdown
=> CFE-4127: Noted that getusers() takes comma separated strings as filters

reference/functions/readintlist.markdown
Macros help to keep the documentation consistent and an accurate reflection of
the current state.
Ticket: CFE-4133
=> CFE-4133: Updated readintlist() docs to leverage macros

reference/functions/readintlist.markdown
Macros help to keep the documentation consistent and an accurate reflection of
the current state.
=> CFE-4133: Updated readintlist() docs to leverage macros (3.21)

reference/language-concepts/augments.markdown
Ticket: CFE-4158
(cherry picked from commit 31e6a14ee918639980f4da48a3273fb21b836ef9)
=> CFE-4158: Clarified that Augments does not expand CFEngine variables (3.21)

reference/language-concepts/augments.markdown
Ticket: CFE-4158
(cherry picked from commit 31e6a14ee918639980f4da48a3273fb21b836ef9)
=> CFE-4158: Clarified that Augments does not expand CFEngine variables (3.18)

reference/functions/parsejson.markdown
=> CFE-4162: Added note that parsejson() does not parse primitives (3.21)

reference/special-variables/sys.markdown
The ticket seems to have been moved to a private project, so it has been cloned
back to the CFE project and this change simply updates the reference.
=> CFE-4174: Fixed reference to ticket

reference/special-variables/sys.markdown
The ticket seems to have been moved to a private project, so it has been cloned
back to the CFE project and this change simply updates the reference.
=> CFE-4147: Fixed reference to ticket (3.21)

reference/special-variables/sys.markdown
The ticket seems to have been moved to a private project, so it has been cloned
back to the CFE project and this change simply updates the reference.
=> CFE-4174: Fixed reference to ticket (3.18)

examples/example-snippets/promise-patterns/example_edit_motd.markdown, examples/tutorials/manage-ntp.markdown, examples/tutorials/render-files-with-mustache-templates.markdown
- Actually, this is simply an included example from core. https://github.com/cfengine/core/blob/558f212e9c6df679590b33d8718db3644b681459/examples/mustache_classes.cf#L40-L50
=> Wrap mustache_template_motd.cf with raw so that mustache will render

overview/client-server-communication.markdown, reference/components.markdown, reference/components/cf-serverd.markdown
The difference between body server control and body common control does not have
to do with directionality as much as it has to do with component behavior. body
server control settings do influence outbound connections, at least in the case
of client initiated reporting with CFEngine Enterprise.
While common control should impact behavior of non cf-serverd components it
currently only seems to impact cf-agent specifically. There are tickets about
correcting the behavior for other components like cf-hub and cf-runagent.
=> ENT-10203: Clarified how TLS settings impact behavior of various components (3.21)

guide/introduction/networking.markdown, reference/components.markdown, reference/components/cf-serverd.markdown
The difference between body server control and body common control does not have
to do with directionality as much as it has to do with component behavior. body
server control settings do influence outbound connections, at least in the case
of client initiated reporting with CFEngine Enterprise.
While common control should impact behavior of non cf-serverd components it
currently only seems to impact cf-agent specifically. There are tickets about
correcting the behavior for other components like cf-hub and cf-runagent.
=> ENT-10203: Clarified how TLS settings impact behavior of various components (3.18)

reference/language-concepts/modules.markdown
=> CFE-4180: Fixed broken link to read_module_protocol() (3.18)

api/enterprise-api-ref/build-api.markdown, api/enterprise-api-ref/federated-reporting-api.markdown, api/enterprise-api-ref/ssh-keys-api.markdown, examples/example-snippets/general.markdown, resources/additional-topics/agility.markdown, resources/additional-topics/application-management.markdown, resources/additional-topics/build-deploy-manage-audit.markdown, resources/additional-topics/change-management.markdown, resources/additional-topics/cloud-computing.markdown, resources/additional-topics/content-driven-policy.markdown, resources/additional-topics/devops.markdown, resources/additional-topics/distributed-scheduling.markdown, resources/additional-topics/file-content.markdown, resources/additional-topics/hierarchies.markdown, resources/additional-topics/iteration.markdown, resources/additional-topics/itil.markdown, resources/additional-topics/modularity.markdown, resources/additional-topics/open-nebula.markdown, resources/additional-topics/orchestration.markdown, resources/additional-topics/stigs.markdown, resources/additional-topics/teamwork.markdown
Don't use h1 within documentation articles, h1 is automatically added, it's the title of the page. First heading should be h2 and so on.
Ticket: ENT-9968
(cherry picked from commit 1b58e536ab4072333d447b6cd73801bc42abbbf9)
=> ENT-9968: Increased heading level of many headings within docs (3.21)

examples/tutorials/masterfiles_policy_framework_upgrade.markdown, generator/build/run.sh
Inside of the container build we chown all files to jenkins:jenkins but this results
in the host having incorrect ownership after the run which then causes problems
when CI comes back again to checkout with git.
Fix is to chown back to the local uid/gid regardless of outcome of run.sh (the build).
Ticket: ENT-10474
=> ENT-10474: Fixed host ownership after container builds

examples/tutorials/masterfiles_policy_framework_upgrade.markdown, generator/build/run.sh
Inside of the container build we chown all files to jenkins:jenkins but this results
in the host having incorrect ownership after the run which then causes problems
when CI comes back again to checkout with git.
Fix is to chown back to the local uid/gid regardless of outcome of run.sh (the build).
Ticket: ENT-10474
=> ENT-10474: Fixed host ownership after container builds (3.18)

examples/tutorials/masterfiles_policy_framework_upgrade.markdown, generator/build/run.sh
Inside of the container build we chown all files to jenkins:jenkins but this results
in the host having incorrect ownership after the run which then causes problems
when CI comes back again to checkout with git.
Fix is to chown back to the local uid/gid regardless of outcome of run.sh (the build).
Ticket: ENT-10474
=> ENT-10474: Fixed host ownership after container builds (3.21)

reference/functions/findfiles.markdown, reference/functions/findfiles_up.markdown
Ticket: ENT-10250
(cherry picked from commit 2df0a7f5bcb22a27a848bd4c7f05a241e4c099f2)
=> ENT-10250 Now mentiones lack of square bracket glob expression support on Windows (3.21)

reference/functions/findfiles.markdown, reference/functions/findfiles_up.markdown
Ticket: ENT-10250
(cherry picked from commit 2df0a7f5bcb22a27a848bd4c7f05a241e4c099f2)
=> ENT-10250: Now mentiones lack of square bracket glob expression support on Windows (3.18)

reference/promise-types/commands.markdown
Removed incorrect claim that the `arglist` attribute of the `commands` promise type, preserves spaces in the arguments. I believe it is meant to be that way, but it currently isn't. Thus we can revert this commit from master, once it is implemented in one of the next minor releases. For patch releases, we should keep the behaviour as is, since it may be relied upon.
=> CFE-2724: Removed incorrect claim that `arglist` attribute preserve spaces

guide/latest-release/supported-platforms.markdown
We build 3.18 hub and client packages for Ubuntu 22.04 for both amd64 and arm64.
Ticket: ENT-10668
=> ENT-10668: Added Ubuntu 22.04 to supported platforms (3.18)

reference/language-concepts/augments.markdown
=> ENT-10721: Fixed documentation noting the default bundle scope of variables in host_specific.json

reference/language-concepts/augments.markdown
Ticket: ENT-10721
(cherry picked from commit 9c2d645e14280a3e9691714adb2d91318d0317cc)
=> ENT-10721: Fixed documentation noting the default bundle scope of variables in host_specific.json (3.21)

reference/language-concepts/augments.markdown
Ticket: ENT-10721
(cherry picked from commit 9c2d645e14280a3e9691714adb2d91318d0317cc)
=> ENT-10721: Fixed documentation noting the default bundle scope of variables in host_specific.json (3.18)

reference/functions/findfiles.markdown, reference/functions/findfiles_up.markdown
- Revert "Merge pull request #3085 from larsewi/glob"
- Added warning against using glob patterns on Windows
Back-ported from https://github.com/cfengine/documentation/pull/3088
=> ENT-10250, ENT-10490: Added warning against using glob patterns on Windows (3.21)

reference/functions/findfiles.markdown, reference/functions/findfiles_up.markdown
- Revert "Merge pull request #3085 from larsewi/glob"
- Added warning against using glob patterns on Windows
Back-ported from https://github.com/cfengine/documentation/pull/3088
=> ENT-10250, ENT-10490: Added warning against using glob patterns on Windows (3.18)

cheatsheet.markdown, examples/tutorials/writing-and-serving-policy/controlling-frequency.markdown, overview/directory-structure.markdown, reference/components/cf-agent.markdown
Quick link to preview pages that changed:
- http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-415/output/_site/examples-tutorials-writing-and-serving-policy-controlling-frequency.html
- http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-415/output/_site/overview-directory-structure.html#state-cf_lock-lmdb
- http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-415/output/_site/markdown-cheatsheet.html
Ticket: ENT-10930
=> ENT-10930: Added notes about lock purging

reference/components/cf-agent.markdown
Without a blank line, the list renders all on a single line.
=> ENT-10930: Fixed rendering for list

reference/components/cf-agent.markdown
Without a blank line, the list renders all on a single line.
(cherry picked from commit e4ebc3718619c75e17f4249140bd34154c618991)
=> ENT-10903: Fixed rendering for list (3.23)

reference/components/cf-agent.markdown
Without a blank line, the list renders all on a single line.
(cherry picked from commit e4ebc3718619c75e17f4249140bd34154c618991)
=> ENT-10903: Fixed rendering for list (3.21)

reference/components/cf-agent.markdown
Without a blank line, the list renders all on a single line.
(cherry picked from commit e4ebc3718619c75e17f4249140bd34154c618991)
=> ENT-10903: Fixed rendering for list (3.18)

examples/tutorials/writing-and-serving-policy/controlling-frequency.markdown
(cherry picked from commit f47b75689685d82308474a45cada621808488c65)
=> ENT-10903: Improved readability of note about promise lock purging (3.21)

guide/writing-and-serving-policy/controlling-frequency.markdown
(cherry picked from commit f47b75689685d82308474a45cada621808488c65)
=> ENT-10903: Improved readability of note about promise lock purging (3.18)

generator/build/README.md, generator/build/clone.sh, generator/build/install.sh, generator/build/main.sh
I tried the docker build and failed. These changes are my quick try for improvement.
- Tidied documentation for readability
- Added clone.sh script to make it easier to get the necessary repos
- Moved installation of execjs before redcarpet to avoid pulling it in with the wrong version as a dependency
```
Building native extensions.  This could take a while...
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for COPYING, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for COPYING, skipping
Successfully installed redcarpet-2.2.2
1 gem installed
Installing ri documentation for redcarpet-2.2.2...
Installing RDoc documentation for redcarpet-2.2.2...
ERROR:  Error installing uglifier:
execjs requires Ruby version …
```
=> Docker fixups

generator/_assets/styles/less/article.less
=> ENT-9832: Long title text causes disposition of the gh button

redirects.conf
This can be useful as a nice shorthand to share in other documents.
Especially if we'd like to move some of this information around
later.
=> Added redirects for /licenses

legal.markdown
- legal.markdown: Removed redis
- legal.markdown: Added a clarifying sentence to the general legal disclaimer
- legal.markdown: Clarified the sections
- legal.markdown: Fixed small typos, grammar, capitalization
- legal.markdown: Removed commented out unused dependency
- legal.markdown: Fixed several URLS
- legal.markdown: Removed unused dependency
=> Improvements to legal and licenses page

legal.markdown
For CodeIgniter we use version 3.x from composer install which is based on a github repo, not codeigniter.com
=> More legal fixes, made some references more precise

generator/_assets/styles/less/article.less, generator/_assets/styles/less/base.less, generator/_assets/styles/less/header.less, generator/_assets/styles/less/home.less, generator/_assets/styles/less/pages.less
See:
https://github.com/cfengine/website/pull/890
(cherry picked from commit 9f8e73a7f71a3dcf6ef2ed1a6fc7347829b2de1f)
=> Added fallback fonts to reduce differences while red hat font is loading (3.21)

generator/_assets/js/custom.js, generator/_assets/styles/less/menu.less
https://github.com/cfengine/documentation/assets/23060634/a946b89f-3f2c-4bc9-9ec4-1af37f91e5af
Ticket: ENT-10267
=>  ENT-10267: docs navigation doesn't show user's location

generator/build/main.sh, generator/build/search/createIndex.js, generator/package-lock.json, generator/package.json, generator/webpack.config.js
this PR fixes missing search index
=> Moved build commands from main.sh to npm scripts

generator/_assets/styles/less/header.less
=> ENT-9757: Main navigation width adjustment

legal.markdown
For CodeIgniter we use version 3.x from composer install which is based on a github repo, not codeigniter.com
(cherry picked from commit ad8738e36b6ad47a8dafb1bee91523ae7ff8200c)
=> More legal fixes, made some references more precise (3.18)

legal.markdown
For CodeIgniter we use version 3.x from composer install which is based on a github repo, not codeigniter.com
(cherry picked from commit ad8738e36b6ad47a8dafb1bee91523ae7ff8200c)
=> More legal fixes, made some references more precise (3.21)

generator/build/main.sh
A package happened to have "deb" in it's commit hash so was included in the downloads list.
Ticket: ENT-11149
together
https://github.com/cfengine/misc/pull/153
https://github.com/cfengine/documentation/pull/3169
=> ENT-11149: Adjusted generator/build/main.sh to be more specific about package URLs

generator/build/main.sh
Seems like this commit introduced an accident which broke the build:
https://github.com/cfengine/documentation/commit/5a31f28c676cf6d886260082b94184209be3f1ee
=> Added back parenthesis

.github/workflows/shellcheck.yml, Makefile, generator/build/install.sh, generator/build/main.sh, generator/build/run.sh
=> ENT-11156: Added shellcheck make target and github action workflow

.github/workflows/shellcheck.yml, Makefile, generator/build/install.sh, generator/build/main.sh, generator/build/run.sh
Ticket: ENT-11156
(cherry picked from commit 22d0236a2a2eff79942bde733017576440129793)
=> ENT-11156: Added shellcheck make target and github action workflow (3.21)

examples/tutorials/manage-packages.markdown
Somehow a video for templating files with mustache got placed instead of a video
about package management. I could not find the correct old video in a short
search and since it's so old anyway, I decided to just remove it.
Ticket: ENT-11185
=> ENT-11185: Removed mismatching video for tutorial

examples/tutorials/manage-packages.markdown
Somehow a video for templating files with mustache got placed instead of a video
about package management. I could not find the correct old video in a short
search and since it's so old anyway, I decided to just remove it.
Ticket: ENT-11185
(cherry picked from commit fe46e979c71a157450806f09a77c29f35e3dc537)
=> ENT-11185: Removed mismatching video for tutorial (3.21)

examples/tutorials/manage-packages.markdown
Somehow a video for templating files with mustache got placed instead of a video
about package management. I could not find the correct old video in a short
search and since it's so old anyway, I decided to just remove it.
Ticket: ENT-11185
(cherry picked from commit fe46e979c71a157450806f09a77c29f35e3dc537)
=> ENT-11185: Removed mismatching video for tutorial (3.18)

.github/workflows/shellcheck.yml, Makefile, generator/build/install.sh, generator/build/main.sh, generator/build/run.sh
Ticket: ENT-11156
(cherry picked from commit 22d0236a2a2eff79942bde733017576440129793)
Conflicts:
generator/build/install.sh
generator/build/main.sh
generator/build/run.sh
=> ENT-11156: Added shellcheck make target and github action workflow (3.18)

.github/workflows/markdowner.py, reference/components/cf-agent.markdown
- cf-agent.markdown: Small formatting fixes
- markdowner.py: Fixed typo
=> Fixed small typo and formatting differences

reference/promise-types/commands.markdown
- Revert "Removed incorrect claim that `arglist` attribute preserve spaces"
- Added note on the use of `arglist` with `useshell` or Windows
=> CFE-2724: Update docs to reflect change in behavior of `arglist` attribute

generator/_includes/footer.html
Was working before due to redirect. Might as well go directly.
(cherry picked from commit ddbaa8059111f3a4fbc4cd9f0d340353932f16e0)
=> Updated legal link in footer (3.21)

generator/_assets/js/custom.js, generator/_assets/styles/less/pages.less
=> ENT-11202: TOC scrolls with view

generator/_assets/js/custom.js
Ticket: ENT-11202 ENT-11335 ENT-11305
=> ENT-11202, ENT-11335, ENT-11305: TOC bug-fixes

generator/_scripts/cfdoc_linkresolver.py
Because of the order of replace commands ' - ' was becoming '--' incorrectly.
The other side of things where the reference is generated works properly so the links were not matching even though the header and reference matched.
Ticket: CFE-4336
=> CFE-4336: Fixed anchor generation when ' - ' is found

reference/promise-types/custom.markdown
The auto-linked target for meta was targeting the meta promise type, but here
the meta attribute was meant. It's global attribute that can be applied to any
promise type and those are documented on the Promise types page in the Common
promise attributes section.
Ticket: ENT-11392
(cherry picked from commit 2f68477834324df9ed97e9ec22a08846c34ea23d)
=> ENT-11392: Fixed link for meta attribute (3.21)

reference/promise-types/custom.markdown
- Custom promise types: Fixed python examples to use metadata parameter
- Custom promise types: Fixed syntax, highlighting and indentation for CFEngine and JSON code
=> Custom promise types: Fixed outdated examples and some syntax / formatting / highlighting

reference/promise-types/custom.markdown
These end up not being rendered because conf is not a
recognized language.
See:
https://northerntech.atlassian.net/browse/ENT-11407
=> Removed use of unknown syntax highlighting language conf

generator/_scripts/cfdoc_metadata.py
Implemented the smallest / safest fix I could think of,
when you're done processing / editing the first frontmatter
block skip the rest, don't look for more in the same file.
This issue would cause code blocks which had triple
dashes at the start of lines (like an RSA public key),
to get some funny looking metadata inserted into them.
=> Fixed detection of markdown frontmatter blocks

generator/_scripts/cfdoc_metadata.py
Implemented the smallest / safest fix I could think of, when you're done processing / editing the first frontmatter block skip the rest, don't look for more in the same file.
This issue would cause code blocks which had triple dashes at the start of lines (like an RSA public key), to get some funny looking metadata inserted into them.
=> Fixed detection of markdown frontmatter blocks (3.21)

api/enterprise-api-ref/inventory.markdown, api/enterprise-api-ref/personal-groups.markdown, api/enterprise-api-ref/shared-groups.markdown
=> Adjusted Inventory and Group API hostFilter documention

web-ui/custom-actions-for-alerts.markdown
Maybe the buggy behavior is only around the newlines, and
this commit could've been done without removing the line?
https://github.com/cfengine/documentation/pull/3258/commits/fba219f045c30909ccfd10caf0b38e0884df5782
=> Custom actions: Reintroduced file label to make it a file component

examples/tutorials/distribute-files-from-a-central-location.markdown
Fix missing code block in [1] due to wrong language identifier (`cf` instead of `cf3`)
[1] https://docs.cfengine.com/docs/master/examples-tutorials-distribute-files-from-a-central-location.html#define-locations
=> examples: Fix missing code block

examples/example-snippets/set_up_hpc_clusters.cf, reference/components/cf-execd.markdown, reference/components/cf-hub.markdown
Using ranged classes for scheduling can result in multiple executions during
that period of time as cf-execd should wake up once during each minute to
determine if exec_command should be scheduled.
Ticket: ENT-11752
(cherry picked from commit 15787d517f8ff777d3f2226eb1b41d94ea9ab0f7)
=> ENT-11752: Adjusted cf-execd schedule examples to not show ranged minute classes (3.21)

web-ui/hub_administration/custom-https-certificate.markdown
The default private key is called
`/var/cfengine/httpd/ssl/private/<hostname>.key`, not
`/var/cfengine/httpd/ssl/private/<hostname>.cert`.
Ticket: ENT-11847
Back ported to:
- https://github.com/cfengine/documentation/pull/3290
- https://github.com/cfengine/documentation/pull/3291
=> ENT-11847: Fixed wrong filename of private key for Custom SSL certs

web-ui/hub_administration/custom-https-certificate.markdown
The default private key is called
`/var/cfengine/httpd/ssl/private/<hostname>.key`, not
`/var/cfengine/httpd/ssl/private/<hostname>.cert`.
Ticket: ENT-11847
(cherry picked from commit 8da8fb833624d10f5eb8f2a13d8f8043fa906067)
Back ported from https://github.com/cfengine/documentation/pull/3289
=> ENT-11847: Fixed wrong filename of private key for Custom SSL certs (3.21)

enterprise-cfengine-guide/hub_administration/custom-https-certificate.markdown
The default private key is called
`/var/cfengine/httpd/ssl/private/<hostname>.key`, not
`/var/cfengine/httpd/ssl/private/<hostname>.cert`.
Ticket: ENT-11847
(cherry picked from commit 8da8fb833624d10f5eb8f2a13d8f8043fa906067)
Back ported from https://github.com/cfengine/documentation/pull/3289
=> ENT-11847: Fixed wrong filename of private key for Custom SSL certs (3.18)

release-notes/supported-platforms.markdown
- Removed Ubuntu 16.04 hub from supported platforms
- Added Ubuntu 24.04 to supported platforms
- Aligned supported platforms tables
Back ported to:
- https://github.com/cfengine/documentation/pull/3293
- https://github.com/cfengine/documentation/pull/3294
=> ENT-11309: Updated supported platforms and versions

release-notes/supported-platforms.markdown
- Added Ubuntu 24.04 to supported platforms
- Aligned supported platforms tables
=> ENT-11309: Updated supported platforms and versions (3.21)

guide/latest-release/supported-platforms.markdown
- Added Ubuntu 24.04 to supported platforms
- Aligned supported platforms tables
=> ENT-11309: Updated supported platforms and versions (3.18)

guide/installation-and-configuration/general-installation/installation-enterprise-vagrant.markdown
The vagrant environment moved to a centos 9 stream base and 3.18 doesn't support
el9, so 3.18.7 was the last vagrant environment built for 3.18.
=> ENT-11893: Pegged latest patch release for vagrant environment to 7

reference/components/cf-serverd.markdown
Ticket: CFE-4413
(cherry picked from commit fab263fccdbc56629b1cfd7b80353d3b120e352f)
=> CFE-4413: Added documentation for log level influencing signals for cf-serverd (3.18)

generator/build/latest_nightly.sh
Ubuntu-16 hub packages are removed in master/3.24.0
=> Migrate to ubuntu-22 hub package for generating docs.

reference/components/cf-runagent.markdown, reference/promise-types/access.markdown
=> ENT-11987: Clarify that cf-runagent --remote-bundles requires explicit bundle resource_type access promises

reference/components/cf-runagent.markdown, reference/promise-types/access.markdown
Ticket: ENT-11987
(cherry picked from commit e7571517fbb2308babd277a8c81cb63da2c3d3a4)
=> ENT-11987: Clarify that cf-runagent --remote-bundles requires explicit bundle resource_type access promises (3.24)

api/enterprise-api-ref/two-factor-authentication.markdown, api/enterprise-api-ref/users-rbac.markdown
=> Added Two-factor authentication API documentation

getting-started/developing-modules.markdown
This comes in handy when you are working on a PR in a branch such as for cfengine/modules
(cherry picked from commit cbb1e9d0b2e9c47b5c95814e565ccedf591b655d)
=> Mention that you can add a module by repo AND commit (3.24)

examples/tutorials/writing-and-serving-policy/policy-style.markdown, reference/functions.markdown, reference/language-concepts.markdown, reference/language-concepts/classes.markdown, reference/language-concepts/policy-evaluation.markdown, reference/promise-types.markdown, reference/promise-types/custom.markdown, reference/promise-types/vars.markdown, resources/faq/manual-execution.markdown
I think that Policy evaluation is a more general term that someone not educated
in CFEngine would understand.
=> Renamed Normal ordering to Policy evaluation

examples/tutorials/custom_inventory.markdown
Typo correction:
`if => isvaribale( "my_owner" );`
changed to
`if => isvariable( "my_owner" );`
(cherry picked from commit 91d1bdf0355d50b589bc2e5b0b5285a20c089399)
=> Update custom_inventory.markdown (3.24)

examples/tutorials/write-cfengine-policy.markdown
Command to check the user policy corrected.
`cf-agent -cf /var/cfengine/masterfiles/promises.cf` changed to
`cf-promises -cf /var/cfengine/masterfiles/promises.cf`
=> Update write-cfengine-policy.markdown (3.24)

examples/tutorials/write-cfengine-policy.markdown
Command to check the user policy corrected.
`cf-agent -cf /var/cfengine/masterfiles/promises.cf` changed to
`cf-promises -cf /var/cfengine/masterfiles/promises.cf`
=> Update write-cfengine-policy.markdown (3.21)

resources/additional-topics/application-management.markdown
(cherry picked from commit e23f81f5c4edfab15ec3f19bc1468c292d648c6c)
=> Typo in adapting to windows content (3.24)

resources/additional-topics/application-management.markdown
(cherry picked from commit e23f81f5c4edfab15ec3f19bc1468c292d648c6c)
=> Typo in adapting to windows content (3.21)

getting-started/installation/general-installation/installation-enterprise-vagrant.markdown
Ticket: ENT-12445
Changelog: Vagrant environment now defaults to use Debian instead of CentOS.
=> Updated vagrant instructions after changing default platform to Debian

getting-started/installation/general-installation/installation-enterprise-vagrant.markdown
Ticket: ENT-12445
Changelog: Vagrant environment now defaults to use Debian instead of CentOS.
(cherry picked from commit 00715ccb89e393b8e34a44871039f16b7b8614e6)
=> Updated vagrant instructions after changing default platform to Debian (3.24)

getting-started/installation/general-installation/installation-enterprise-vagrant.markdown
Ticket: ENT-12445
Changelog: Vagrant environment now defaults to use Debian instead of CentOS.
(cherry picked from commit 00715ccb89e393b8e34a44871039f16b7b8614e6)
=> Updated vagrant instructions after changing default platform to Debian (3.21)

getting-started/developing-modules.markdown
Ticket: CFE-4457
Signed-off-by: Victor Moene <victor.moene@northern.tech>
(cherry picked from commit 406c16f6b7288398fcf5820f67162ac8452803b4)
=> Changed wrong command in developing modules (3.24)

overview/directory-structure.markdown
=> ENT-12569: Added documentation about promise_execution.log, variable.cache.tmp, and context.cache.tmp state files (3.21)

getting-started/installation/general-installation/installation-community.markdown
=> ENT-12515: Replaced instructions for quick-install-cfengine-community with cf-remote (3.25)

getting-started/installation/general-installation/installation-community.markdown
=> ENT-12515: Replaced instructions for quick-install-cfengine-community with cf-remote (3.24)

getting-started/installation/general-installation/installation-community.markdown
=> ENT-12515: Replaced instructions for quick-install-cfengine-community with cf-remote (3.21)

reference/functions/classesmatching.markdown
=> CFE-4495: Added docs indicating classesmatching() returns an empty list when no classes match

reference/functions/classesmatching.markdown
=> CFE-4495: Added docs indicating classesmatching() returns an empty list when no classes match (3.24)

reference/functions/classesmatching.markdown
=> CFE-4495: Added docs indicating classesmatching() returns an empty list when no classes match (3.21)

reference/functions/is_type.markdown
https://github.com/cfengine/core/pull/5691
https://github.com/cfengine/documentation/pull/3391
=> Added is_type function

reference/masterfiles-policy-framework/lib.markdown
=> Fixed typo in stdlib introductory paragraph

reference/masterfiles-policy-framework/lib.markdown
s/akak/aka/
Ticket: none
(cherry picked from commit 82ab2337836cf0a4132ef8d89767f1308618c4c2)
=> Fixed typo in stdlib introductory paragraph (3.24)

reference/masterfiles-policy-framework/lib.markdown
s/akak/aka/
Ticket: none
(cherry picked from commit 82ab2337836cf0a4132ef8d89767f1308618c4c2)
=> Fixed typo in stdlib introductory paragraph (3.21)

api/enterprise-api-ref/status-settings.markdown, api/enterprise-api-ref/users-rbac.markdown
=> ENT-10841: Updated Settings and Users APIs documentations

reference/functions/isconnectable.markdown
I removed the output in the core/example because the example won't succeed in various testing environments.
Ticket: ENT-12753
=> Fixed isconnectable function docs example

api/enterprise-api-ref/reset-password.markdown
=> Added the Reset password API documentation

generator/_config.yml
- Updated latest patch release for 3.24.2 release
- Bumped vagrant from 2.4.3 to 2.4.5 and virtualbox from 7.0.16 to 7.1.8
=> Update versions after release of 3.24.2 (3.24)

reference/functions/getacls.markdown
3.27.0 is more correct and less ambiguous.
=> Fixed version getacls() was introduced in

content/reference/promise-types/files/_index.markdown
=> ENT-10961, CFE-1840: Added documentation on body fsattrs and the immutable constraint

generator/build/install_hugo.sh
=> ENT-13123: Fixed verification of hugo sha256 sum

content/reference/functions/classfilterdata.markdown
Ticket: CFE-4562
Depends on https://github.com/cfengine/core/pull/5850
=> CFE-4562: classfilterdata(): added docs for object of arrays/objects

Jenkinsfile
=> Adjusted Jenkinsfile DOCS_BRANCH for ssh publisher to get dynamically when it is needed

generator/build/main.sh
On LTS branches, BRANCH=3.21 without the .x suffix and cf-remote doesn't understand this.
Ticket: ENT-12581
(cherry picked from commit 6b7cb38a6804cb2909c75c69e764b66fd442ff47)
=> Fixed version installed by cf-remote via fast-build(Jenkinsfile) on LTS branches

generator/_scripts/_run.sh, generator/_scripts/cfdoc_codeblock_resolver.py, generator/_scripts/cfdoc_preprocess.py
together: https://github.com/NorthernTechHQ/nt-docs/pull/5
=> Stop docs generation if npm build:all script failed & added codeblock pre-processor

content/reference/language-concepts/bodies.markdown
Clarified the explanation of default bodies, added CFEngine code examples for
their definition and application, and included historical context.
Ticket: CFE-4583
=> CFE-4583: Enhanced default bodies documentation and examples

Jenkinsfile, generator/build/Dockerfile, generator/build/main.sh, generator/build/run.sh
=> Back port Jenkinsfile and associated changes to generator/build (3.21)

reference/promise-types/methods.markdown, reference/promise-types/roles.markdown, reference/promise-types/services.markdown
Also fix a typo
(cherry picked from commit 88d702e29e2b2ec365e0b23a3bd6f2bb0d5c47eb)
=> methods: Fix inherit example (3.21)

content/getting-started/installation/_index.markdown, content/getting-started/installation/local-virtual-machine.markdown, content/getting-started/modules-from-cfengine-build.markdown, content/getting-started/reporting-and-web-ui.markdown
These are getting outdated and don't align with what we want to
show in the new getting started tutorial structure for 3.27+.
Removing them and maybe we'll record new ones when the new
tutorials are ready.
=> Removed videos from getting started tutorials
